// Code generated by ent, DO NOT EDIT.

package upstreamchangeevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProviderID applies equality check predicate on the "provider_id" field. It's identical to ProviderIDEQ.
func ProviderID(v int64) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldEQ(FieldProviderID, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldEQ(FieldType, v))
}

// Summary applies equality check predicate on the "summary" field. It's identical to SummaryEQ.
func Summary(v string) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldEQ(FieldSummary, v))
}

// Notified applies equality check predicate on the "notified" field. It's identical to NotifiedEQ.
func Notified(v bool) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldEQ(FieldNotified, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldLTE(FieldUpdatedAt, v))
}

// ProviderIDEQ applies the EQ predicate on the "provider_id" field.
func ProviderIDEQ(v int64) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldEQ(FieldProviderID, v))
}

// ProviderIDNEQ applies the NEQ predicate on the "provider_id" field.
func ProviderIDNEQ(v int64) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldNEQ(FieldProviderID, v))
}

// ProviderIDIn applies the In predicate on the "provider_id" field.
func ProviderIDIn(vs ...int64) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldIn(FieldProviderID, vs...))
}

// ProviderIDNotIn applies the NotIn predicate on the "provider_id" field.
func ProviderIDNotIn(vs ...int64) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldNotIn(FieldProviderID, vs...))
}

// ProviderIDGT applies the GT predicate on the "provider_id" field.
func ProviderIDGT(v int64) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldGT(FieldProviderID, v))
}

// ProviderIDGTE applies the GTE predicate on the "provider_id" field.
func ProviderIDGTE(v int64) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldGTE(FieldProviderID, v))
}

// ProviderIDLT applies the LT predicate on the "provider_id" field.
func ProviderIDLT(v int64) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldLT(FieldProviderID, v))
}

// ProviderIDLTE applies the LTE predicate on the "provider_id" field.
func ProviderIDLTE(v int64) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldLTE(FieldProviderID, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldContainsFold(FieldType, v))
}

// SummaryEQ applies the EQ predicate on the "summary" field.
func SummaryEQ(v string) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldEQ(FieldSummary, v))
}

// SummaryNEQ applies the NEQ predicate on the "summary" field.
func SummaryNEQ(v string) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldNEQ(FieldSummary, v))
}

// SummaryIn applies the In predicate on the "summary" field.
func SummaryIn(vs ...string) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldIn(FieldSummary, vs...))
}

// SummaryNotIn applies the NotIn predicate on the "summary" field.
func SummaryNotIn(vs ...string) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldNotIn(FieldSummary, vs...))
}

// SummaryGT applies the GT predicate on the "summary" field.
func SummaryGT(v string) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldGT(FieldSummary, v))
}

// SummaryGTE applies the GTE predicate on the "summary" field.
func SummaryGTE(v string) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldGTE(FieldSummary, v))
}

// SummaryLT applies the LT predicate on the "summary" field.
func SummaryLT(v string) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldLT(FieldSummary, v))
}

// SummaryLTE applies the LTE predicate on the "summary" field.
func SummaryLTE(v string) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldLTE(FieldSummary, v))
}

// SummaryContains applies the Contains predicate on the "summary" field.
func SummaryContains(v string) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldContains(FieldSummary, v))
}

// SummaryHasPrefix applies the HasPrefix predicate on the "summary" field.
func SummaryHasPrefix(v string) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldHasPrefix(FieldSummary, v))
}

// SummaryHasSuffix applies the HasSuffix predicate on the "summary" field.
func SummaryHasSuffix(v string) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldHasSuffix(FieldSummary, v))
}

// SummaryEqualFold applies the EqualFold predicate on the "summary" field.
func SummaryEqualFold(v string) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldEqualFold(FieldSummary, v))
}

// SummaryContainsFold applies the ContainsFold predicate on the "summary" field.
func SummaryContainsFold(v string) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldContainsFold(FieldSummary, v))
}

// DetailIsNil applies the IsNil predicate on the "detail" field.
func DetailIsNil() predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldIsNull(FieldDetail))
}

// DetailNotNil applies the NotNil predicate on the "detail" field.
func DetailNotNil() predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldNotNull(FieldDetail))
}

// NotifiedEQ applies the EQ predicate on the "notified" field.
func NotifiedEQ(v bool) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldEQ(FieldNotified, v))
}

// NotifiedNEQ applies the NEQ predicate on the "notified" field.
func NotifiedNEQ(v bool) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.FieldNEQ(FieldNotified, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UpstreamChangeEvent) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UpstreamChangeEvent) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UpstreamChangeEvent) predicate.UpstreamChangeEvent {
	return predicate.UpstreamChangeEvent(sql.NotPredicates(p))
}
