// Code generated by ent, DO NOT EDIT.

package upstreamusagedaily

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProviderID applies equality check predicate on the "provider_id" field. It's identical to ProviderIDEQ.
func ProviderID(v int64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldEQ(FieldProviderID, v))
}

// Day applies equality check predicate on the "day" field. It's identical to DayEQ.
func Day(v time.Time) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldEQ(FieldDay, v))
}

// ScopeType applies equality check predicate on the "scope_type" field. It's identical to ScopeTypeEQ.
func ScopeType(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldEQ(FieldScopeType, v))
}

// ScopeKey applies equality check predicate on the "scope_key" field. It's identical to ScopeKeyEQ.
func ScopeKey(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldEQ(FieldScopeKey, v))
}

// ScopeName applies equality check predicate on the "scope_name" field. It's identical to ScopeNameEQ.
func ScopeName(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldEQ(FieldScopeName, v))
}

// Requests applies equality check predicate on the "requests" field. It's identical to RequestsEQ.
func Requests(v int) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldEQ(FieldRequests, v))
}

// Tokens applies equality check predicate on the "tokens" field. It's identical to TokensEQ.
func Tokens(v int64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldEQ(FieldTokens, v))
}

// CostUsd applies equality check predicate on the "cost_usd" field. It's identical to CostUsdEQ.
func CostUsd(v float64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldEQ(FieldCostUsd, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldLTE(FieldUpdatedAt, v))
}

// ProviderIDEQ applies the EQ predicate on the "provider_id" field.
func ProviderIDEQ(v int64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldEQ(FieldProviderID, v))
}

// ProviderIDNEQ applies the NEQ predicate on the "provider_id" field.
func ProviderIDNEQ(v int64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldNEQ(FieldProviderID, v))
}

// ProviderIDIn applies the In predicate on the "provider_id" field.
func ProviderIDIn(vs ...int64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldIn(FieldProviderID, vs...))
}

// ProviderIDNotIn applies the NotIn predicate on the "provider_id" field.
func ProviderIDNotIn(vs ...int64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldNotIn(FieldProviderID, vs...))
}

// ProviderIDGT applies the GT predicate on the "provider_id" field.
func ProviderIDGT(v int64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldGT(FieldProviderID, v))
}

// ProviderIDGTE applies the GTE predicate on the "provider_id" field.
func ProviderIDGTE(v int64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldGTE(FieldProviderID, v))
}

// ProviderIDLT applies the LT predicate on the "provider_id" field.
func ProviderIDLT(v int64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldLT(FieldProviderID, v))
}

// ProviderIDLTE applies the LTE predicate on the "provider_id" field.
func ProviderIDLTE(v int64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldLTE(FieldProviderID, v))
}

// DayEQ applies the EQ predicate on the "day" field.
func DayEQ(v time.Time) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldEQ(FieldDay, v))
}

// DayNEQ applies the NEQ predicate on the "day" field.
func DayNEQ(v time.Time) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldNEQ(FieldDay, v))
}

// DayIn applies the In predicate on the "day" field.
func DayIn(vs ...time.Time) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldIn(FieldDay, vs...))
}

// DayNotIn applies the NotIn predicate on the "day" field.
func DayNotIn(vs ...time.Time) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldNotIn(FieldDay, vs...))
}

// DayGT applies the GT predicate on the "day" field.
func DayGT(v time.Time) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldGT(FieldDay, v))
}

// DayGTE applies the GTE predicate on the "day" field.
func DayGTE(v time.Time) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldGTE(FieldDay, v))
}

// DayLT applies the LT predicate on the "day" field.
func DayLT(v time.Time) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldLT(FieldDay, v))
}

// DayLTE applies the LTE predicate on the "day" field.
func DayLTE(v time.Time) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldLTE(FieldDay, v))
}

// ScopeTypeEQ applies the EQ predicate on the "scope_type" field.
func ScopeTypeEQ(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldEQ(FieldScopeType, v))
}

// ScopeTypeNEQ applies the NEQ predicate on the "scope_type" field.
func ScopeTypeNEQ(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldNEQ(FieldScopeType, v))
}

// ScopeTypeIn applies the In predicate on the "scope_type" field.
func ScopeTypeIn(vs ...string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldIn(FieldScopeType, vs...))
}

// ScopeTypeNotIn applies the NotIn predicate on the "scope_type" field.
func ScopeTypeNotIn(vs ...string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldNotIn(FieldScopeType, vs...))
}

// ScopeTypeGT applies the GT predicate on the "scope_type" field.
func ScopeTypeGT(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldGT(FieldScopeType, v))
}

// ScopeTypeGTE applies the GTE predicate on the "scope_type" field.
func ScopeTypeGTE(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldGTE(FieldScopeType, v))
}

// ScopeTypeLT applies the LT predicate on the "scope_type" field.
func ScopeTypeLT(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldLT(FieldScopeType, v))
}

// ScopeTypeLTE applies the LTE predicate on the "scope_type" field.
func ScopeTypeLTE(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldLTE(FieldScopeType, v))
}

// ScopeTypeContains applies the Contains predicate on the "scope_type" field.
func ScopeTypeContains(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldContains(FieldScopeType, v))
}

// ScopeTypeHasPrefix applies the HasPrefix predicate on the "scope_type" field.
func ScopeTypeHasPrefix(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldHasPrefix(FieldScopeType, v))
}

// ScopeTypeHasSuffix applies the HasSuffix predicate on the "scope_type" field.
func ScopeTypeHasSuffix(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldHasSuffix(FieldScopeType, v))
}

// ScopeTypeEqualFold applies the EqualFold predicate on the "scope_type" field.
func ScopeTypeEqualFold(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldEqualFold(FieldScopeType, v))
}

// ScopeTypeContainsFold applies the ContainsFold predicate on the "scope_type" field.
func ScopeTypeContainsFold(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldContainsFold(FieldScopeType, v))
}

// ScopeKeyEQ applies the EQ predicate on the "scope_key" field.
func ScopeKeyEQ(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldEQ(FieldScopeKey, v))
}

// ScopeKeyNEQ applies the NEQ predicate on the "scope_key" field.
func ScopeKeyNEQ(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldNEQ(FieldScopeKey, v))
}

// ScopeKeyIn applies the In predicate on the "scope_key" field.
func ScopeKeyIn(vs ...string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldIn(FieldScopeKey, vs...))
}

// ScopeKeyNotIn applies the NotIn predicate on the "scope_key" field.
func ScopeKeyNotIn(vs ...string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldNotIn(FieldScopeKey, vs...))
}

// ScopeKeyGT applies the GT predicate on the "scope_key" field.
func ScopeKeyGT(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldGT(FieldScopeKey, v))
}

// ScopeKeyGTE applies the GTE predicate on the "scope_key" field.
func ScopeKeyGTE(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldGTE(FieldScopeKey, v))
}

// ScopeKeyLT applies the LT predicate on the "scope_key" field.
func ScopeKeyLT(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldLT(FieldScopeKey, v))
}

// ScopeKeyLTE applies the LTE predicate on the "scope_key" field.
func ScopeKeyLTE(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldLTE(FieldScopeKey, v))
}

// ScopeKeyContains applies the Contains predicate on the "scope_key" field.
func ScopeKeyContains(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldContains(FieldScopeKey, v))
}

// ScopeKeyHasPrefix applies the HasPrefix predicate on the "scope_key" field.
func ScopeKeyHasPrefix(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldHasPrefix(FieldScopeKey, v))
}

// ScopeKeyHasSuffix applies the HasSuffix predicate on the "scope_key" field.
func ScopeKeyHasSuffix(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldHasSuffix(FieldScopeKey, v))
}

// ScopeKeyEqualFold applies the EqualFold predicate on the "scope_key" field.
func ScopeKeyEqualFold(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldEqualFold(FieldScopeKey, v))
}

// ScopeKeyContainsFold applies the ContainsFold predicate on the "scope_key" field.
func ScopeKeyContainsFold(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldContainsFold(FieldScopeKey, v))
}

// ScopeNameEQ applies the EQ predicate on the "scope_name" field.
func ScopeNameEQ(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldEQ(FieldScopeName, v))
}

// ScopeNameNEQ applies the NEQ predicate on the "scope_name" field.
func ScopeNameNEQ(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldNEQ(FieldScopeName, v))
}

// ScopeNameIn applies the In predicate on the "scope_name" field.
func ScopeNameIn(vs ...string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldIn(FieldScopeName, vs...))
}

// ScopeNameNotIn applies the NotIn predicate on the "scope_name" field.
func ScopeNameNotIn(vs ...string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldNotIn(FieldScopeName, vs...))
}

// ScopeNameGT applies the GT predicate on the "scope_name" field.
func ScopeNameGT(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldGT(FieldScopeName, v))
}

// ScopeNameGTE applies the GTE predicate on the "scope_name" field.
func ScopeNameGTE(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldGTE(FieldScopeName, v))
}

// ScopeNameLT applies the LT predicate on the "scope_name" field.
func ScopeNameLT(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldLT(FieldScopeName, v))
}

// ScopeNameLTE applies the LTE predicate on the "scope_name" field.
func ScopeNameLTE(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldLTE(FieldScopeName, v))
}

// ScopeNameContains applies the Contains predicate on the "scope_name" field.
func ScopeNameContains(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldContains(FieldScopeName, v))
}

// ScopeNameHasPrefix applies the HasPrefix predicate on the "scope_name" field.
func ScopeNameHasPrefix(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldHasPrefix(FieldScopeName, v))
}

// ScopeNameHasSuffix applies the HasSuffix predicate on the "scope_name" field.
func ScopeNameHasSuffix(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldHasSuffix(FieldScopeName, v))
}

// ScopeNameEqualFold applies the EqualFold predicate on the "scope_name" field.
func ScopeNameEqualFold(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldEqualFold(FieldScopeName, v))
}

// ScopeNameContainsFold applies the ContainsFold predicate on the "scope_name" field.
func ScopeNameContainsFold(v string) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldContainsFold(FieldScopeName, v))
}

// RequestsEQ applies the EQ predicate on the "requests" field.
func RequestsEQ(v int) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldEQ(FieldRequests, v))
}

// RequestsNEQ applies the NEQ predicate on the "requests" field.
func RequestsNEQ(v int) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldNEQ(FieldRequests, v))
}

// RequestsIn applies the In predicate on the "requests" field.
func RequestsIn(vs ...int) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldIn(FieldRequests, vs...))
}

// RequestsNotIn applies the NotIn predicate on the "requests" field.
func RequestsNotIn(vs ...int) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldNotIn(FieldRequests, vs...))
}

// RequestsGT applies the GT predicate on the "requests" field.
func RequestsGT(v int) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldGT(FieldRequests, v))
}

// RequestsGTE applies the GTE predicate on the "requests" field.
func RequestsGTE(v int) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldGTE(FieldRequests, v))
}

// RequestsLT applies the LT predicate on the "requests" field.
func RequestsLT(v int) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldLT(FieldRequests, v))
}

// RequestsLTE applies the LTE predicate on the "requests" field.
func RequestsLTE(v int) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldLTE(FieldRequests, v))
}

// TokensEQ applies the EQ predicate on the "tokens" field.
func TokensEQ(v int64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldEQ(FieldTokens, v))
}

// TokensNEQ applies the NEQ predicate on the "tokens" field.
func TokensNEQ(v int64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldNEQ(FieldTokens, v))
}

// TokensIn applies the In predicate on the "tokens" field.
func TokensIn(vs ...int64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldIn(FieldTokens, vs...))
}

// TokensNotIn applies the NotIn predicate on the "tokens" field.
func TokensNotIn(vs ...int64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldNotIn(FieldTokens, vs...))
}

// TokensGT applies the GT predicate on the "tokens" field.
func TokensGT(v int64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldGT(FieldTokens, v))
}

// TokensGTE applies the GTE predicate on the "tokens" field.
func TokensGTE(v int64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldGTE(FieldTokens, v))
}

// TokensLT applies the LT predicate on the "tokens" field.
func TokensLT(v int64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldLT(FieldTokens, v))
}

// TokensLTE applies the LTE predicate on the "tokens" field.
func TokensLTE(v int64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldLTE(FieldTokens, v))
}

// CostUsdEQ applies the EQ predicate on the "cost_usd" field.
func CostUsdEQ(v float64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldEQ(FieldCostUsd, v))
}

// CostUsdNEQ applies the NEQ predicate on the "cost_usd" field.
func CostUsdNEQ(v float64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldNEQ(FieldCostUsd, v))
}

// CostUsdIn applies the In predicate on the "cost_usd" field.
func CostUsdIn(vs ...float64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldIn(FieldCostUsd, vs...))
}

// CostUsdNotIn applies the NotIn predicate on the "cost_usd" field.
func CostUsdNotIn(vs ...float64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldNotIn(FieldCostUsd, vs...))
}

// CostUsdGT applies the GT predicate on the "cost_usd" field.
func CostUsdGT(v float64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldGT(FieldCostUsd, v))
}

// CostUsdGTE applies the GTE predicate on the "cost_usd" field.
func CostUsdGTE(v float64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldGTE(FieldCostUsd, v))
}

// CostUsdLT applies the LT predicate on the "cost_usd" field.
func CostUsdLT(v float64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldLT(FieldCostUsd, v))
}

// CostUsdLTE applies the LTE predicate on the "cost_usd" field.
func CostUsdLTE(v float64) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.FieldLTE(FieldCostUsd, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UpstreamUsageDaily) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UpstreamUsageDaily) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UpstreamUsageDaily) predicate.UpstreamUsageDaily {
	return predicate.UpstreamUsageDaily(sql.NotPredicates(p))
}
