// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/extensionconfig"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// ExtensionConfigCreate is the builder for creating a ExtensionConfig entity.
type ExtensionConfigCreate struct {
	config
	mutation *ExtensionConfigMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ExtensionConfigCreate) SetCreatedAt(v time.Time) *ExtensionConfigCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ExtensionConfigCreate) SetNillableCreatedAt(v *time.Time) *ExtensionConfigCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ExtensionConfigCreate) SetUpdatedAt(v time.Time) *ExtensionConfigCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ExtensionConfigCreate) SetNillableUpdatedAt(v *time.Time) *ExtensionConfigCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAgentID sets the "agent_id" field.
func (_c *ExtensionConfigCreate) SetAgentID(v string) *ExtensionConfigCreate {
	_c.mutation.SetAgentID(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *ExtensionConfigCreate) SetPayload(v domain.ExtensionConfigPayload) *ExtensionConfigCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_c *ExtensionConfigCreate) SetNillablePayload(v *domain.ExtensionConfigPayload) *ExtensionConfigCreate {
	if v != nil {
		_c.SetPayload(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *ExtensionConfigCreate) SetUpdatedBy(v int64) *ExtensionConfigCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *ExtensionConfigCreate) SetNillableUpdatedBy(v *int64) *ExtensionConfigCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// Mutation returns the ExtensionConfigMutation object of the builder.
func (_c *ExtensionConfigCreate) Mutation() *ExtensionConfigMutation {
	return _c.mutation
}

// Save creates the ExtensionConfig in the database.
func (_c *ExtensionConfigCreate) Save(ctx context.Context) (*ExtensionConfig, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ExtensionConfigCreate) SaveX(ctx context.Context) *ExtensionConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExtensionConfigCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExtensionConfigCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ExtensionConfigCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := extensionconfig.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := extensionconfig.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Payload(); !ok {
		v := extensionconfig.DefaultPayload
		_c.mutation.SetPayload(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ExtensionConfigCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ExtensionConfig.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ExtensionConfig.updated_at"`)}
	}
	if _, ok := _c.mutation.AgentID(); !ok {
		return &ValidationError{Name: "agent_id", err: errors.New(`ent: missing required field "ExtensionConfig.agent_id"`)}
	}
	if v, ok := _c.mutation.AgentID(); ok {
		if err := extensionconfig.AgentIDValidator(v); err != nil {
			return &ValidationError{Name: "agent_id", err: fmt.Errorf(`ent: validator failed for field "ExtensionConfig.agent_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "ExtensionConfig.payload"`)}
	}
	return nil
}

func (_c *ExtensionConfigCreate) sqlSave(ctx context.Context) (*ExtensionConfig, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ExtensionConfigCreate) createSpec() (*ExtensionConfig, *sqlgraph.CreateSpec) {
	var (
		_node = &ExtensionConfig{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(extensionconfig.Table, sqlgraph.NewFieldSpec(extensionconfig.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(extensionconfig.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(extensionconfig.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AgentID(); ok {
		_spec.SetField(extensionconfig.FieldAgentID, field.TypeString, value)
		_node.AgentID = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(extensionconfig.FieldPayload, field.TypeJSON, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(extensionconfig.FieldUpdatedBy, field.TypeInt64, value)
		_node.UpdatedBy = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ExtensionConfig.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExtensionConfigUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ExtensionConfigCreate) OnConflict(opts ...sql.ConflictOption) *ExtensionConfigUpsertOne {
	_c.conflict = opts
	return &ExtensionConfigUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ExtensionConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExtensionConfigCreate) OnConflictColumns(columns ...string) *ExtensionConfigUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExtensionConfigUpsertOne{
		create: _c,
	}
}

type (
	// ExtensionConfigUpsertOne is the builder for "upsert"-ing
	//  one ExtensionConfig node.
	ExtensionConfigUpsertOne struct {
		create *ExtensionConfigCreate
	}

	// ExtensionConfigUpsert is the "OnConflict" setter.
	ExtensionConfigUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ExtensionConfigUpsert) SetUpdatedAt(v time.Time) *ExtensionConfigUpsert {
	u.Set(extensionconfig.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExtensionConfigUpsert) UpdateUpdatedAt() *ExtensionConfigUpsert {
	u.SetExcluded(extensionconfig.FieldUpdatedAt)
	return u
}

// SetAgentID sets the "agent_id" field.
func (u *ExtensionConfigUpsert) SetAgentID(v string) *ExtensionConfigUpsert {
	u.Set(extensionconfig.FieldAgentID, v)
	return u
}

// UpdateAgentID sets the "agent_id" field to the value that was provided on create.
func (u *ExtensionConfigUpsert) UpdateAgentID() *ExtensionConfigUpsert {
	u.SetExcluded(extensionconfig.FieldAgentID)
	return u
}

// SetPayload sets the "payload" field.
func (u *ExtensionConfigUpsert) SetPayload(v domain.ExtensionConfigPayload) *ExtensionConfigUpsert {
	u.Set(extensionconfig.FieldPayload, v)
	return u
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *ExtensionConfigUpsert) UpdatePayload() *ExtensionConfigUpsert {
	u.SetExcluded(extensionconfig.FieldPayload)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ExtensionConfigUpsert) SetUpdatedBy(v int64) *ExtensionConfigUpsert {
	u.Set(extensionconfig.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ExtensionConfigUpsert) UpdateUpdatedBy() *ExtensionConfigUpsert {
	u.SetExcluded(extensionconfig.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ExtensionConfigUpsert) AddUpdatedBy(v int64) *ExtensionConfigUpsert {
	u.Add(extensionconfig.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ExtensionConfigUpsert) ClearUpdatedBy() *ExtensionConfigUpsert {
	u.SetNull(extensionconfig.FieldUpdatedBy)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ExtensionConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ExtensionConfigUpsertOne) UpdateNewValues() *ExtensionConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(extensionconfig.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ExtensionConfig.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ExtensionConfigUpsertOne) Ignore() *ExtensionConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExtensionConfigUpsertOne) DoNothing() *ExtensionConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExtensionConfigCreate.OnConflict
// documentation for more info.
func (u *ExtensionConfigUpsertOne) Update(set func(*ExtensionConfigUpsert)) *ExtensionConfigUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExtensionConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ExtensionConfigUpsertOne) SetUpdatedAt(v time.Time) *ExtensionConfigUpsertOne {
	return u.Update(func(s *ExtensionConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExtensionConfigUpsertOne) UpdateUpdatedAt() *ExtensionConfigUpsertOne {
	return u.Update(func(s *ExtensionConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAgentID sets the "agent_id" field.
func (u *ExtensionConfigUpsertOne) SetAgentID(v string) *ExtensionConfigUpsertOne {
	return u.Update(func(s *ExtensionConfigUpsert) {
		s.SetAgentID(v)
	})
}

// UpdateAgentID sets the "agent_id" field to the value that was provided on create.
func (u *ExtensionConfigUpsertOne) UpdateAgentID() *ExtensionConfigUpsertOne {
	return u.Update(func(s *ExtensionConfigUpsert) {
		s.UpdateAgentID()
	})
}

// SetPayload sets the "payload" field.
func (u *ExtensionConfigUpsertOne) SetPayload(v domain.ExtensionConfigPayload) *ExtensionConfigUpsertOne {
	return u.Update(func(s *ExtensionConfigUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *ExtensionConfigUpsertOne) UpdatePayload() *ExtensionConfigUpsertOne {
	return u.Update(func(s *ExtensionConfigUpsert) {
		s.UpdatePayload()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ExtensionConfigUpsertOne) SetUpdatedBy(v int64) *ExtensionConfigUpsertOne {
	return u.Update(func(s *ExtensionConfigUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ExtensionConfigUpsertOne) AddUpdatedBy(v int64) *ExtensionConfigUpsertOne {
	return u.Update(func(s *ExtensionConfigUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ExtensionConfigUpsertOne) UpdateUpdatedBy() *ExtensionConfigUpsertOne {
	return u.Update(func(s *ExtensionConfigUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ExtensionConfigUpsertOne) ClearUpdatedBy() *ExtensionConfigUpsertOne {
	return u.Update(func(s *ExtensionConfigUpsert) {
		s.ClearUpdatedBy()
	})
}

// Exec executes the query.
func (u *ExtensionConfigUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ExtensionConfigCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExtensionConfigUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ExtensionConfigUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ExtensionConfigUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ExtensionConfigCreateBulk is the builder for creating many ExtensionConfig entities in bulk.
type ExtensionConfigCreateBulk struct {
	config
	err      error
	builders []*ExtensionConfigCreate
	conflict []sql.ConflictOption
}

// Save creates the ExtensionConfig entities in the database.
func (_c *ExtensionConfigCreateBulk) Save(ctx context.Context) ([]*ExtensionConfig, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ExtensionConfig, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ExtensionConfigMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ExtensionConfigCreateBulk) SaveX(ctx context.Context) []*ExtensionConfig {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ExtensionConfigCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ExtensionConfigCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ExtensionConfig.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ExtensionConfigUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ExtensionConfigCreateBulk) OnConflict(opts ...sql.ConflictOption) *ExtensionConfigUpsertBulk {
	_c.conflict = opts
	return &ExtensionConfigUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ExtensionConfig.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ExtensionConfigCreateBulk) OnConflictColumns(columns ...string) *ExtensionConfigUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ExtensionConfigUpsertBulk{
		create: _c,
	}
}

// ExtensionConfigUpsertBulk is the builder for "upsert"-ing
// a bulk of ExtensionConfig nodes.
type ExtensionConfigUpsertBulk struct {
	create *ExtensionConfigCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ExtensionConfig.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ExtensionConfigUpsertBulk) UpdateNewValues() *ExtensionConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(extensionconfig.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ExtensionConfig.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ExtensionConfigUpsertBulk) Ignore() *ExtensionConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ExtensionConfigUpsertBulk) DoNothing() *ExtensionConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ExtensionConfigCreateBulk.OnConflict
// documentation for more info.
func (u *ExtensionConfigUpsertBulk) Update(set func(*ExtensionConfigUpsert)) *ExtensionConfigUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ExtensionConfigUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ExtensionConfigUpsertBulk) SetUpdatedAt(v time.Time) *ExtensionConfigUpsertBulk {
	return u.Update(func(s *ExtensionConfigUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ExtensionConfigUpsertBulk) UpdateUpdatedAt() *ExtensionConfigUpsertBulk {
	return u.Update(func(s *ExtensionConfigUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAgentID sets the "agent_id" field.
func (u *ExtensionConfigUpsertBulk) SetAgentID(v string) *ExtensionConfigUpsertBulk {
	return u.Update(func(s *ExtensionConfigUpsert) {
		s.SetAgentID(v)
	})
}

// UpdateAgentID sets the "agent_id" field to the value that was provided on create.
func (u *ExtensionConfigUpsertBulk) UpdateAgentID() *ExtensionConfigUpsertBulk {
	return u.Update(func(s *ExtensionConfigUpsert) {
		s.UpdateAgentID()
	})
}

// SetPayload sets the "payload" field.
func (u *ExtensionConfigUpsertBulk) SetPayload(v domain.ExtensionConfigPayload) *ExtensionConfigUpsertBulk {
	return u.Update(func(s *ExtensionConfigUpsert) {
		s.SetPayload(v)
	})
}

// UpdatePayload sets the "payload" field to the value that was provided on create.
func (u *ExtensionConfigUpsertBulk) UpdatePayload() *ExtensionConfigUpsertBulk {
	return u.Update(func(s *ExtensionConfigUpsert) {
		s.UpdatePayload()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *ExtensionConfigUpsertBulk) SetUpdatedBy(v int64) *ExtensionConfigUpsertBulk {
	return u.Update(func(s *ExtensionConfigUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *ExtensionConfigUpsertBulk) AddUpdatedBy(v int64) *ExtensionConfigUpsertBulk {
	return u.Update(func(s *ExtensionConfigUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *ExtensionConfigUpsertBulk) UpdateUpdatedBy() *ExtensionConfigUpsertBulk {
	return u.Update(func(s *ExtensionConfigUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *ExtensionConfigUpsertBulk) ClearUpdatedBy() *ExtensionConfigUpsertBulk {
	return u.Update(func(s *ExtensionConfigUpsert) {
		s.ClearUpdatedBy()
	})
}

// Exec executes the query.
func (u *ExtensionConfigUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ExtensionConfigCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ExtensionConfigCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ExtensionConfigUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
