// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/notifychannel"
)

// NotifyChannelCreate is the builder for creating a NotifyChannel entity.
type NotifyChannelCreate struct {
	config
	mutation *NotifyChannelMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *NotifyChannelCreate) SetCreatedAt(v time.Time) *NotifyChannelCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NotifyChannelCreate) SetNillableCreatedAt(v *time.Time) *NotifyChannelCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *NotifyChannelCreate) SetUpdatedAt(v time.Time) *NotifyChannelCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *NotifyChannelCreate) SetNillableUpdatedAt(v *time.Time) *NotifyChannelCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *NotifyChannelCreate) SetName(v string) *NotifyChannelCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetType sets the "type" field.
func (_c *NotifyChannelCreate) SetType(v string) *NotifyChannelCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetScope sets the "scope" field.
func (_c *NotifyChannelCreate) SetScope(v string) *NotifyChannelCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *NotifyChannelCreate) SetEnabled(v bool) *NotifyChannelCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *NotifyChannelCreate) SetNillableEnabled(v *bool) *NotifyChannelCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetEvents sets the "events" field.
func (_c *NotifyChannelCreate) SetEvents(v []string) *NotifyChannelCreate {
	_c.mutation.SetEvents(v)
	return _c
}

// SetConfig sets the "config" field.
func (_c *NotifyChannelCreate) SetConfig(v map[string]interface{}) *NotifyChannelCreate {
	_c.mutation.SetConfig(v)
	return _c
}

// SetLastSentAt sets the "last_sent_at" field.
func (_c *NotifyChannelCreate) SetLastSentAt(v time.Time) *NotifyChannelCreate {
	_c.mutation.SetLastSentAt(v)
	return _c
}

// SetNillableLastSentAt sets the "last_sent_at" field if the given value is not nil.
func (_c *NotifyChannelCreate) SetNillableLastSentAt(v *time.Time) *NotifyChannelCreate {
	if v != nil {
		_c.SetLastSentAt(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *NotifyChannelCreate) SetLastError(v string) *NotifyChannelCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *NotifyChannelCreate) SetNillableLastError(v *string) *NotifyChannelCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// Mutation returns the NotifyChannelMutation object of the builder.
func (_c *NotifyChannelCreate) Mutation() *NotifyChannelMutation {
	return _c.mutation
}

// Save creates the NotifyChannel in the database.
func (_c *NotifyChannelCreate) Save(ctx context.Context) (*NotifyChannel, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NotifyChannelCreate) SaveX(ctx context.Context) *NotifyChannel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotifyChannelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotifyChannelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NotifyChannelCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := notifychannel.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := notifychannel.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := notifychannel.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.LastError(); !ok {
		v := notifychannel.DefaultLastError
		_c.mutation.SetLastError(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NotifyChannelCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "NotifyChannel.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "NotifyChannel.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "NotifyChannel.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := notifychannel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "NotifyChannel.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "NotifyChannel.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := notifychannel.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "NotifyChannel.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "NotifyChannel.scope"`)}
	}
	if v, ok := _c.mutation.Scope(); ok {
		if err := notifychannel.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "NotifyChannel.scope": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "NotifyChannel.enabled"`)}
	}
	if _, ok := _c.mutation.Config(); !ok {
		return &ValidationError{Name: "config", err: errors.New(`ent: missing required field "NotifyChannel.config"`)}
	}
	if _, ok := _c.mutation.LastError(); !ok {
		return &ValidationError{Name: "last_error", err: errors.New(`ent: missing required field "NotifyChannel.last_error"`)}
	}
	return nil
}

func (_c *NotifyChannelCreate) sqlSave(ctx context.Context) (*NotifyChannel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NotifyChannelCreate) createSpec() (*NotifyChannel, *sqlgraph.CreateSpec) {
	var (
		_node = &NotifyChannel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(notifychannel.Table, sqlgraph.NewFieldSpec(notifychannel.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(notifychannel.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(notifychannel.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(notifychannel.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(notifychannel.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(notifychannel.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(notifychannel.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Events(); ok {
		_spec.SetField(notifychannel.FieldEvents, field.TypeJSON, value)
		_node.Events = value
	}
	if value, ok := _c.mutation.Config(); ok {
		_spec.SetField(notifychannel.FieldConfig, field.TypeJSON, value)
		_node.Config = value
	}
	if value, ok := _c.mutation.LastSentAt(); ok {
		_spec.SetField(notifychannel.FieldLastSentAt, field.TypeTime, value)
		_node.LastSentAt = &value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(notifychannel.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NotifyChannel.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NotifyChannelUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *NotifyChannelCreate) OnConflict(opts ...sql.ConflictOption) *NotifyChannelUpsertOne {
	_c.conflict = opts
	return &NotifyChannelUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NotifyChannel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NotifyChannelCreate) OnConflictColumns(columns ...string) *NotifyChannelUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NotifyChannelUpsertOne{
		create: _c,
	}
}

type (
	// NotifyChannelUpsertOne is the builder for "upsert"-ing
	//  one NotifyChannel node.
	NotifyChannelUpsertOne struct {
		create *NotifyChannelCreate
	}

	// NotifyChannelUpsert is the "OnConflict" setter.
	NotifyChannelUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *NotifyChannelUpsert) SetUpdatedAt(v time.Time) *NotifyChannelUpsert {
	u.Set(notifychannel.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NotifyChannelUpsert) UpdateUpdatedAt() *NotifyChannelUpsert {
	u.SetExcluded(notifychannel.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *NotifyChannelUpsert) SetName(v string) *NotifyChannelUpsert {
	u.Set(notifychannel.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *NotifyChannelUpsert) UpdateName() *NotifyChannelUpsert {
	u.SetExcluded(notifychannel.FieldName)
	return u
}

// SetType sets the "type" field.
func (u *NotifyChannelUpsert) SetType(v string) *NotifyChannelUpsert {
	u.Set(notifychannel.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *NotifyChannelUpsert) UpdateType() *NotifyChannelUpsert {
	u.SetExcluded(notifychannel.FieldType)
	return u
}

// SetScope sets the "scope" field.
func (u *NotifyChannelUpsert) SetScope(v string) *NotifyChannelUpsert {
	u.Set(notifychannel.FieldScope, v)
	return u
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *NotifyChannelUpsert) UpdateScope() *NotifyChannelUpsert {
	u.SetExcluded(notifychannel.FieldScope)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *NotifyChannelUpsert) SetEnabled(v bool) *NotifyChannelUpsert {
	u.Set(notifychannel.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *NotifyChannelUpsert) UpdateEnabled() *NotifyChannelUpsert {
	u.SetExcluded(notifychannel.FieldEnabled)
	return u
}

// SetEvents sets the "events" field.
func (u *NotifyChannelUpsert) SetEvents(v []string) *NotifyChannelUpsert {
	u.Set(notifychannel.FieldEvents, v)
	return u
}

// UpdateEvents sets the "events" field to the value that was provided on create.
func (u *NotifyChannelUpsert) UpdateEvents() *NotifyChannelUpsert {
	u.SetExcluded(notifychannel.FieldEvents)
	return u
}

// ClearEvents clears the value of the "events" field.
func (u *NotifyChannelUpsert) ClearEvents() *NotifyChannelUpsert {
	u.SetNull(notifychannel.FieldEvents)
	return u
}

// SetConfig sets the "config" field.
func (u *NotifyChannelUpsert) SetConfig(v map[string]interface{}) *NotifyChannelUpsert {
	u.Set(notifychannel.FieldConfig, v)
	return u
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *NotifyChannelUpsert) UpdateConfig() *NotifyChannelUpsert {
	u.SetExcluded(notifychannel.FieldConfig)
	return u
}

// SetLastSentAt sets the "last_sent_at" field.
func (u *NotifyChannelUpsert) SetLastSentAt(v time.Time) *NotifyChannelUpsert {
	u.Set(notifychannel.FieldLastSentAt, v)
	return u
}

// UpdateLastSentAt sets the "last_sent_at" field to the value that was provided on create.
func (u *NotifyChannelUpsert) UpdateLastSentAt() *NotifyChannelUpsert {
	u.SetExcluded(notifychannel.FieldLastSentAt)
	return u
}

// ClearLastSentAt clears the value of the "last_sent_at" field.
func (u *NotifyChannelUpsert) ClearLastSentAt() *NotifyChannelUpsert {
	u.SetNull(notifychannel.FieldLastSentAt)
	return u
}

// SetLastError sets the "last_error" field.
func (u *NotifyChannelUpsert) SetLastError(v string) *NotifyChannelUpsert {
	u.Set(notifychannel.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *NotifyChannelUpsert) UpdateLastError() *NotifyChannelUpsert {
	u.SetExcluded(notifychannel.FieldLastError)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.NotifyChannel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *NotifyChannelUpsertOne) UpdateNewValues() *NotifyChannelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(notifychannel.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NotifyChannel.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *NotifyChannelUpsertOne) Ignore() *NotifyChannelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NotifyChannelUpsertOne) DoNothing() *NotifyChannelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NotifyChannelCreate.OnConflict
// documentation for more info.
func (u *NotifyChannelUpsertOne) Update(set func(*NotifyChannelUpsert)) *NotifyChannelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NotifyChannelUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *NotifyChannelUpsertOne) SetUpdatedAt(v time.Time) *NotifyChannelUpsertOne {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NotifyChannelUpsertOne) UpdateUpdatedAt() *NotifyChannelUpsertOne {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *NotifyChannelUpsertOne) SetName(v string) *NotifyChannelUpsertOne {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *NotifyChannelUpsertOne) UpdateName() *NotifyChannelUpsertOne {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.UpdateName()
	})
}

// SetType sets the "type" field.
func (u *NotifyChannelUpsertOne) SetType(v string) *NotifyChannelUpsertOne {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *NotifyChannelUpsertOne) UpdateType() *NotifyChannelUpsertOne {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.UpdateType()
	})
}

// SetScope sets the "scope" field.
func (u *NotifyChannelUpsertOne) SetScope(v string) *NotifyChannelUpsertOne {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *NotifyChannelUpsertOne) UpdateScope() *NotifyChannelUpsertOne {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.UpdateScope()
	})
}

// SetEnabled sets the "enabled" field.
func (u *NotifyChannelUpsertOne) SetEnabled(v bool) *NotifyChannelUpsertOne {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *NotifyChannelUpsertOne) UpdateEnabled() *NotifyChannelUpsertOne {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.UpdateEnabled()
	})
}

// SetEvents sets the "events" field.
func (u *NotifyChannelUpsertOne) SetEvents(v []string) *NotifyChannelUpsertOne {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.SetEvents(v)
	})
}

// UpdateEvents sets the "events" field to the value that was provided on create.
func (u *NotifyChannelUpsertOne) UpdateEvents() *NotifyChannelUpsertOne {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.UpdateEvents()
	})
}

// ClearEvents clears the value of the "events" field.
func (u *NotifyChannelUpsertOne) ClearEvents() *NotifyChannelUpsertOne {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.ClearEvents()
	})
}

// SetConfig sets the "config" field.
func (u *NotifyChannelUpsertOne) SetConfig(v map[string]interface{}) *NotifyChannelUpsertOne {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.SetConfig(v)
	})
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *NotifyChannelUpsertOne) UpdateConfig() *NotifyChannelUpsertOne {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.UpdateConfig()
	})
}

// SetLastSentAt sets the "last_sent_at" field.
func (u *NotifyChannelUpsertOne) SetLastSentAt(v time.Time) *NotifyChannelUpsertOne {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.SetLastSentAt(v)
	})
}

// UpdateLastSentAt sets the "last_sent_at" field to the value that was provided on create.
func (u *NotifyChannelUpsertOne) UpdateLastSentAt() *NotifyChannelUpsertOne {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.UpdateLastSentAt()
	})
}

// ClearLastSentAt clears the value of the "last_sent_at" field.
func (u *NotifyChannelUpsertOne) ClearLastSentAt() *NotifyChannelUpsertOne {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.ClearLastSentAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *NotifyChannelUpsertOne) SetLastError(v string) *NotifyChannelUpsertOne {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *NotifyChannelUpsertOne) UpdateLastError() *NotifyChannelUpsertOne {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.UpdateLastError()
	})
}

// Exec executes the query.
func (u *NotifyChannelUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NotifyChannelCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NotifyChannelUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *NotifyChannelUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *NotifyChannelUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// NotifyChannelCreateBulk is the builder for creating many NotifyChannel entities in bulk.
type NotifyChannelCreateBulk struct {
	config
	err      error
	builders []*NotifyChannelCreate
	conflict []sql.ConflictOption
}

// Save creates the NotifyChannel entities in the database.
func (_c *NotifyChannelCreateBulk) Save(ctx context.Context) ([]*NotifyChannel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*NotifyChannel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotifyChannelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NotifyChannelCreateBulk) SaveX(ctx context.Context) []*NotifyChannel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NotifyChannelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NotifyChannelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.NotifyChannel.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.NotifyChannelUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *NotifyChannelCreateBulk) OnConflict(opts ...sql.ConflictOption) *NotifyChannelUpsertBulk {
	_c.conflict = opts
	return &NotifyChannelUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.NotifyChannel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *NotifyChannelCreateBulk) OnConflictColumns(columns ...string) *NotifyChannelUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &NotifyChannelUpsertBulk{
		create: _c,
	}
}

// NotifyChannelUpsertBulk is the builder for "upsert"-ing
// a bulk of NotifyChannel nodes.
type NotifyChannelUpsertBulk struct {
	create *NotifyChannelCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.NotifyChannel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *NotifyChannelUpsertBulk) UpdateNewValues() *NotifyChannelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(notifychannel.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.NotifyChannel.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *NotifyChannelUpsertBulk) Ignore() *NotifyChannelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *NotifyChannelUpsertBulk) DoNothing() *NotifyChannelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the NotifyChannelCreateBulk.OnConflict
// documentation for more info.
func (u *NotifyChannelUpsertBulk) Update(set func(*NotifyChannelUpsert)) *NotifyChannelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&NotifyChannelUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *NotifyChannelUpsertBulk) SetUpdatedAt(v time.Time) *NotifyChannelUpsertBulk {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *NotifyChannelUpsertBulk) UpdateUpdatedAt() *NotifyChannelUpsertBulk {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *NotifyChannelUpsertBulk) SetName(v string) *NotifyChannelUpsertBulk {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *NotifyChannelUpsertBulk) UpdateName() *NotifyChannelUpsertBulk {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.UpdateName()
	})
}

// SetType sets the "type" field.
func (u *NotifyChannelUpsertBulk) SetType(v string) *NotifyChannelUpsertBulk {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *NotifyChannelUpsertBulk) UpdateType() *NotifyChannelUpsertBulk {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.UpdateType()
	})
}

// SetScope sets the "scope" field.
func (u *NotifyChannelUpsertBulk) SetScope(v string) *NotifyChannelUpsertBulk {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *NotifyChannelUpsertBulk) UpdateScope() *NotifyChannelUpsertBulk {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.UpdateScope()
	})
}

// SetEnabled sets the "enabled" field.
func (u *NotifyChannelUpsertBulk) SetEnabled(v bool) *NotifyChannelUpsertBulk {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *NotifyChannelUpsertBulk) UpdateEnabled() *NotifyChannelUpsertBulk {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.UpdateEnabled()
	})
}

// SetEvents sets the "events" field.
func (u *NotifyChannelUpsertBulk) SetEvents(v []string) *NotifyChannelUpsertBulk {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.SetEvents(v)
	})
}

// UpdateEvents sets the "events" field to the value that was provided on create.
func (u *NotifyChannelUpsertBulk) UpdateEvents() *NotifyChannelUpsertBulk {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.UpdateEvents()
	})
}

// ClearEvents clears the value of the "events" field.
func (u *NotifyChannelUpsertBulk) ClearEvents() *NotifyChannelUpsertBulk {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.ClearEvents()
	})
}

// SetConfig sets the "config" field.
func (u *NotifyChannelUpsertBulk) SetConfig(v map[string]interface{}) *NotifyChannelUpsertBulk {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.SetConfig(v)
	})
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *NotifyChannelUpsertBulk) UpdateConfig() *NotifyChannelUpsertBulk {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.UpdateConfig()
	})
}

// SetLastSentAt sets the "last_sent_at" field.
func (u *NotifyChannelUpsertBulk) SetLastSentAt(v time.Time) *NotifyChannelUpsertBulk {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.SetLastSentAt(v)
	})
}

// UpdateLastSentAt sets the "last_sent_at" field to the value that was provided on create.
func (u *NotifyChannelUpsertBulk) UpdateLastSentAt() *NotifyChannelUpsertBulk {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.UpdateLastSentAt()
	})
}

// ClearLastSentAt clears the value of the "last_sent_at" field.
func (u *NotifyChannelUpsertBulk) ClearLastSentAt() *NotifyChannelUpsertBulk {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.ClearLastSentAt()
	})
}

// SetLastError sets the "last_error" field.
func (u *NotifyChannelUpsertBulk) SetLastError(v string) *NotifyChannelUpsertBulk {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *NotifyChannelUpsertBulk) UpdateLastError() *NotifyChannelUpsertBulk {
	return u.Update(func(s *NotifyChannelUpsert) {
		s.UpdateLastError()
	})
}

// Exec executes the query.
func (u *NotifyChannelUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the NotifyChannelCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for NotifyChannelCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *NotifyChannelUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
