// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/notifychannel"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// NotifyChannelUpdate is the builder for updating NotifyChannel entities.
type NotifyChannelUpdate struct {
	config
	hooks    []Hook
	mutation *NotifyChannelMutation
}

// Where appends a list predicates to the NotifyChannelUpdate builder.
func (_u *NotifyChannelUpdate) Where(ps ...predicate.NotifyChannel) *NotifyChannelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotifyChannelUpdate) SetUpdatedAt(v time.Time) *NotifyChannelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *NotifyChannelUpdate) SetName(v string) *NotifyChannelUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *NotifyChannelUpdate) SetNillableName(v *string) *NotifyChannelUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *NotifyChannelUpdate) SetType(v string) *NotifyChannelUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *NotifyChannelUpdate) SetNillableType(v *string) *NotifyChannelUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetScope sets the "scope" field.
func (_u *NotifyChannelUpdate) SetScope(v string) *NotifyChannelUpdate {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *NotifyChannelUpdate) SetNillableScope(v *string) *NotifyChannelUpdate {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *NotifyChannelUpdate) SetEnabled(v bool) *NotifyChannelUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *NotifyChannelUpdate) SetNillableEnabled(v *bool) *NotifyChannelUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetEvents sets the "events" field.
func (_u *NotifyChannelUpdate) SetEvents(v []string) *NotifyChannelUpdate {
	_u.mutation.SetEvents(v)
	return _u
}

// AppendEvents appends value to the "events" field.
func (_u *NotifyChannelUpdate) AppendEvents(v []string) *NotifyChannelUpdate {
	_u.mutation.AppendEvents(v)
	return _u
}

// ClearEvents clears the value of the "events" field.
func (_u *NotifyChannelUpdate) ClearEvents() *NotifyChannelUpdate {
	_u.mutation.ClearEvents()
	return _u
}

// SetConfig sets the "config" field.
func (_u *NotifyChannelUpdate) SetConfig(v map[string]interface{}) *NotifyChannelUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// SetLastSentAt sets the "last_sent_at" field.
func (_u *NotifyChannelUpdate) SetLastSentAt(v time.Time) *NotifyChannelUpdate {
	_u.mutation.SetLastSentAt(v)
	return _u
}

// SetNillableLastSentAt sets the "last_sent_at" field if the given value is not nil.
func (_u *NotifyChannelUpdate) SetNillableLastSentAt(v *time.Time) *NotifyChannelUpdate {
	if v != nil {
		_u.SetLastSentAt(*v)
	}
	return _u
}

// ClearLastSentAt clears the value of the "last_sent_at" field.
func (_u *NotifyChannelUpdate) ClearLastSentAt() *NotifyChannelUpdate {
	_u.mutation.ClearLastSentAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *NotifyChannelUpdate) SetLastError(v string) *NotifyChannelUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *NotifyChannelUpdate) SetNillableLastError(v *string) *NotifyChannelUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// Mutation returns the NotifyChannelMutation object of the builder.
func (_u *NotifyChannelUpdate) Mutation() *NotifyChannelMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NotifyChannelUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotifyChannelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NotifyChannelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotifyChannelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NotifyChannelUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := notifychannel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotifyChannelUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := notifychannel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "NotifyChannel.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := notifychannel.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "NotifyChannel.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Scope(); ok {
		if err := notifychannel.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "NotifyChannel.scope": %w`, err)}
		}
	}
	return nil
}

func (_u *NotifyChannelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notifychannel.Table, notifychannel.Columns, sqlgraph.NewFieldSpec(notifychannel.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notifychannel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(notifychannel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(notifychannel.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(notifychannel.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(notifychannel.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Events(); ok {
		_spec.SetField(notifychannel.FieldEvents, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEvents(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, notifychannel.FieldEvents, value)
		})
	}
	if _u.mutation.EventsCleared() {
		_spec.ClearField(notifychannel.FieldEvents, field.TypeJSON)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(notifychannel.FieldConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.LastSentAt(); ok {
		_spec.SetField(notifychannel.FieldLastSentAt, field.TypeTime, value)
	}
	if _u.mutation.LastSentAtCleared() {
		_spec.ClearField(notifychannel.FieldLastSentAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(notifychannel.FieldLastError, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notifychannel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NotifyChannelUpdateOne is the builder for updating a single NotifyChannel entity.
type NotifyChannelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotifyChannelMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NotifyChannelUpdateOne) SetUpdatedAt(v time.Time) *NotifyChannelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *NotifyChannelUpdateOne) SetName(v string) *NotifyChannelUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *NotifyChannelUpdateOne) SetNillableName(v *string) *NotifyChannelUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *NotifyChannelUpdateOne) SetType(v string) *NotifyChannelUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *NotifyChannelUpdateOne) SetNillableType(v *string) *NotifyChannelUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetScope sets the "scope" field.
func (_u *NotifyChannelUpdateOne) SetScope(v string) *NotifyChannelUpdateOne {
	_u.mutation.SetScope(v)
	return _u
}

// SetNillableScope sets the "scope" field if the given value is not nil.
func (_u *NotifyChannelUpdateOne) SetNillableScope(v *string) *NotifyChannelUpdateOne {
	if v != nil {
		_u.SetScope(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *NotifyChannelUpdateOne) SetEnabled(v bool) *NotifyChannelUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *NotifyChannelUpdateOne) SetNillableEnabled(v *bool) *NotifyChannelUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetEvents sets the "events" field.
func (_u *NotifyChannelUpdateOne) SetEvents(v []string) *NotifyChannelUpdateOne {
	_u.mutation.SetEvents(v)
	return _u
}

// AppendEvents appends value to the "events" field.
func (_u *NotifyChannelUpdateOne) AppendEvents(v []string) *NotifyChannelUpdateOne {
	_u.mutation.AppendEvents(v)
	return _u
}

// ClearEvents clears the value of the "events" field.
func (_u *NotifyChannelUpdateOne) ClearEvents() *NotifyChannelUpdateOne {
	_u.mutation.ClearEvents()
	return _u
}

// SetConfig sets the "config" field.
func (_u *NotifyChannelUpdateOne) SetConfig(v map[string]interface{}) *NotifyChannelUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// SetLastSentAt sets the "last_sent_at" field.
func (_u *NotifyChannelUpdateOne) SetLastSentAt(v time.Time) *NotifyChannelUpdateOne {
	_u.mutation.SetLastSentAt(v)
	return _u
}

// SetNillableLastSentAt sets the "last_sent_at" field if the given value is not nil.
func (_u *NotifyChannelUpdateOne) SetNillableLastSentAt(v *time.Time) *NotifyChannelUpdateOne {
	if v != nil {
		_u.SetLastSentAt(*v)
	}
	return _u
}

// ClearLastSentAt clears the value of the "last_sent_at" field.
func (_u *NotifyChannelUpdateOne) ClearLastSentAt() *NotifyChannelUpdateOne {
	_u.mutation.ClearLastSentAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *NotifyChannelUpdateOne) SetLastError(v string) *NotifyChannelUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *NotifyChannelUpdateOne) SetNillableLastError(v *string) *NotifyChannelUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// Mutation returns the NotifyChannelMutation object of the builder.
func (_u *NotifyChannelUpdateOne) Mutation() *NotifyChannelMutation {
	return _u.mutation
}

// Where appends a list predicates to the NotifyChannelUpdate builder.
func (_u *NotifyChannelUpdateOne) Where(ps ...predicate.NotifyChannel) *NotifyChannelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NotifyChannelUpdateOne) Select(field string, fields ...string) *NotifyChannelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated NotifyChannel entity.
func (_u *NotifyChannelUpdateOne) Save(ctx context.Context) (*NotifyChannel, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NotifyChannelUpdateOne) SaveX(ctx context.Context) *NotifyChannel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NotifyChannelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NotifyChannelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NotifyChannelUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := notifychannel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NotifyChannelUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := notifychannel.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "NotifyChannel.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := notifychannel.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "NotifyChannel.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Scope(); ok {
		if err := notifychannel.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "NotifyChannel.scope": %w`, err)}
		}
	}
	return nil
}

func (_u *NotifyChannelUpdateOne) sqlSave(ctx context.Context) (_node *NotifyChannel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notifychannel.Table, notifychannel.Columns, sqlgraph.NewFieldSpec(notifychannel.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "NotifyChannel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notifychannel.FieldID)
		for _, f := range fields {
			if !notifychannel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notifychannel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(notifychannel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(notifychannel.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(notifychannel.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scope(); ok {
		_spec.SetField(notifychannel.FieldScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(notifychannel.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Events(); ok {
		_spec.SetField(notifychannel.FieldEvents, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedEvents(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, notifychannel.FieldEvents, value)
		})
	}
	if _u.mutation.EventsCleared() {
		_spec.ClearField(notifychannel.FieldEvents, field.TypeJSON)
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(notifychannel.FieldConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.LastSentAt(); ok {
		_spec.SetField(notifychannel.FieldLastSentAt, field.TypeTime, value)
	}
	if _u.mutation.LastSentAtCleared() {
		_spec.ClearField(notifychannel.FieldLastSentAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(notifychannel.FieldLastError, field.TypeString, value)
	}
	_node = &NotifyChannel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notifychannel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
