// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/upstreamusagedaily"
)

// UpstreamUsageDailyCreate is the builder for creating a UpstreamUsageDaily entity.
type UpstreamUsageDailyCreate struct {
	config
	mutation *UpstreamUsageDailyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UpstreamUsageDailyCreate) SetCreatedAt(v time.Time) *UpstreamUsageDailyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UpstreamUsageDailyCreate) SetNillableCreatedAt(v *time.Time) *UpstreamUsageDailyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UpstreamUsageDailyCreate) SetUpdatedAt(v time.Time) *UpstreamUsageDailyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UpstreamUsageDailyCreate) SetNillableUpdatedAt(v *time.Time) *UpstreamUsageDailyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetProviderID sets the "provider_id" field.
func (_c *UpstreamUsageDailyCreate) SetProviderID(v int64) *UpstreamUsageDailyCreate {
	_c.mutation.SetProviderID(v)
	return _c
}

// SetDay sets the "day" field.
func (_c *UpstreamUsageDailyCreate) SetDay(v time.Time) *UpstreamUsageDailyCreate {
	_c.mutation.SetDay(v)
	return _c
}

// SetScopeType sets the "scope_type" field.
func (_c *UpstreamUsageDailyCreate) SetScopeType(v string) *UpstreamUsageDailyCreate {
	_c.mutation.SetScopeType(v)
	return _c
}

// SetScopeKey sets the "scope_key" field.
func (_c *UpstreamUsageDailyCreate) SetScopeKey(v string) *UpstreamUsageDailyCreate {
	_c.mutation.SetScopeKey(v)
	return _c
}

// SetNillableScopeKey sets the "scope_key" field if the given value is not nil.
func (_c *UpstreamUsageDailyCreate) SetNillableScopeKey(v *string) *UpstreamUsageDailyCreate {
	if v != nil {
		_c.SetScopeKey(*v)
	}
	return _c
}

// SetScopeName sets the "scope_name" field.
func (_c *UpstreamUsageDailyCreate) SetScopeName(v string) *UpstreamUsageDailyCreate {
	_c.mutation.SetScopeName(v)
	return _c
}

// SetNillableScopeName sets the "scope_name" field if the given value is not nil.
func (_c *UpstreamUsageDailyCreate) SetNillableScopeName(v *string) *UpstreamUsageDailyCreate {
	if v != nil {
		_c.SetScopeName(*v)
	}
	return _c
}

// SetRequests sets the "requests" field.
func (_c *UpstreamUsageDailyCreate) SetRequests(v int) *UpstreamUsageDailyCreate {
	_c.mutation.SetRequests(v)
	return _c
}

// SetNillableRequests sets the "requests" field if the given value is not nil.
func (_c *UpstreamUsageDailyCreate) SetNillableRequests(v *int) *UpstreamUsageDailyCreate {
	if v != nil {
		_c.SetRequests(*v)
	}
	return _c
}

// SetTokens sets the "tokens" field.
func (_c *UpstreamUsageDailyCreate) SetTokens(v int64) *UpstreamUsageDailyCreate {
	_c.mutation.SetTokens(v)
	return _c
}

// SetNillableTokens sets the "tokens" field if the given value is not nil.
func (_c *UpstreamUsageDailyCreate) SetNillableTokens(v *int64) *UpstreamUsageDailyCreate {
	if v != nil {
		_c.SetTokens(*v)
	}
	return _c
}

// SetCostUsd sets the "cost_usd" field.
func (_c *UpstreamUsageDailyCreate) SetCostUsd(v float64) *UpstreamUsageDailyCreate {
	_c.mutation.SetCostUsd(v)
	return _c
}

// SetNillableCostUsd sets the "cost_usd" field if the given value is not nil.
func (_c *UpstreamUsageDailyCreate) SetNillableCostUsd(v *float64) *UpstreamUsageDailyCreate {
	if v != nil {
		_c.SetCostUsd(*v)
	}
	return _c
}

// Mutation returns the UpstreamUsageDailyMutation object of the builder.
func (_c *UpstreamUsageDailyCreate) Mutation() *UpstreamUsageDailyMutation {
	return _c.mutation
}

// Save creates the UpstreamUsageDaily in the database.
func (_c *UpstreamUsageDailyCreate) Save(ctx context.Context) (*UpstreamUsageDaily, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UpstreamUsageDailyCreate) SaveX(ctx context.Context) *UpstreamUsageDaily {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamUsageDailyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamUsageDailyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UpstreamUsageDailyCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := upstreamusagedaily.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := upstreamusagedaily.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ScopeKey(); !ok {
		v := upstreamusagedaily.DefaultScopeKey
		_c.mutation.SetScopeKey(v)
	}
	if _, ok := _c.mutation.ScopeName(); !ok {
		v := upstreamusagedaily.DefaultScopeName
		_c.mutation.SetScopeName(v)
	}
	if _, ok := _c.mutation.Requests(); !ok {
		v := upstreamusagedaily.DefaultRequests
		_c.mutation.SetRequests(v)
	}
	if _, ok := _c.mutation.Tokens(); !ok {
		v := upstreamusagedaily.DefaultTokens
		_c.mutation.SetTokens(v)
	}
	if _, ok := _c.mutation.CostUsd(); !ok {
		v := upstreamusagedaily.DefaultCostUsd
		_c.mutation.SetCostUsd(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UpstreamUsageDailyCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UpstreamUsageDaily.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UpstreamUsageDaily.updated_at"`)}
	}
	if _, ok := _c.mutation.ProviderID(); !ok {
		return &ValidationError{Name: "provider_id", err: errors.New(`ent: missing required field "UpstreamUsageDaily.provider_id"`)}
	}
	if _, ok := _c.mutation.Day(); !ok {
		return &ValidationError{Name: "day", err: errors.New(`ent: missing required field "UpstreamUsageDaily.day"`)}
	}
	if _, ok := _c.mutation.ScopeType(); !ok {
		return &ValidationError{Name: "scope_type", err: errors.New(`ent: missing required field "UpstreamUsageDaily.scope_type"`)}
	}
	if v, ok := _c.mutation.ScopeType(); ok {
		if err := upstreamusagedaily.ScopeTypeValidator(v); err != nil {
			return &ValidationError{Name: "scope_type", err: fmt.Errorf(`ent: validator failed for field "UpstreamUsageDaily.scope_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ScopeKey(); !ok {
		return &ValidationError{Name: "scope_key", err: errors.New(`ent: missing required field "UpstreamUsageDaily.scope_key"`)}
	}
	if v, ok := _c.mutation.ScopeKey(); ok {
		if err := upstreamusagedaily.ScopeKeyValidator(v); err != nil {
			return &ValidationError{Name: "scope_key", err: fmt.Errorf(`ent: validator failed for field "UpstreamUsageDaily.scope_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ScopeName(); !ok {
		return &ValidationError{Name: "scope_name", err: errors.New(`ent: missing required field "UpstreamUsageDaily.scope_name"`)}
	}
	if v, ok := _c.mutation.ScopeName(); ok {
		if err := upstreamusagedaily.ScopeNameValidator(v); err != nil {
			return &ValidationError{Name: "scope_name", err: fmt.Errorf(`ent: validator failed for field "UpstreamUsageDaily.scope_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Requests(); !ok {
		return &ValidationError{Name: "requests", err: errors.New(`ent: missing required field "UpstreamUsageDaily.requests"`)}
	}
	if _, ok := _c.mutation.Tokens(); !ok {
		return &ValidationError{Name: "tokens", err: errors.New(`ent: missing required field "UpstreamUsageDaily.tokens"`)}
	}
	if _, ok := _c.mutation.CostUsd(); !ok {
		return &ValidationError{Name: "cost_usd", err: errors.New(`ent: missing required field "UpstreamUsageDaily.cost_usd"`)}
	}
	return nil
}

func (_c *UpstreamUsageDailyCreate) sqlSave(ctx context.Context) (*UpstreamUsageDaily, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UpstreamUsageDailyCreate) createSpec() (*UpstreamUsageDaily, *sqlgraph.CreateSpec) {
	var (
		_node = &UpstreamUsageDaily{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(upstreamusagedaily.Table, sqlgraph.NewFieldSpec(upstreamusagedaily.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(upstreamusagedaily.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamusagedaily.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ProviderID(); ok {
		_spec.SetField(upstreamusagedaily.FieldProviderID, field.TypeInt64, value)
		_node.ProviderID = value
	}
	if value, ok := _c.mutation.Day(); ok {
		_spec.SetField(upstreamusagedaily.FieldDay, field.TypeTime, value)
		_node.Day = value
	}
	if value, ok := _c.mutation.ScopeType(); ok {
		_spec.SetField(upstreamusagedaily.FieldScopeType, field.TypeString, value)
		_node.ScopeType = value
	}
	if value, ok := _c.mutation.ScopeKey(); ok {
		_spec.SetField(upstreamusagedaily.FieldScopeKey, field.TypeString, value)
		_node.ScopeKey = value
	}
	if value, ok := _c.mutation.ScopeName(); ok {
		_spec.SetField(upstreamusagedaily.FieldScopeName, field.TypeString, value)
		_node.ScopeName = value
	}
	if value, ok := _c.mutation.Requests(); ok {
		_spec.SetField(upstreamusagedaily.FieldRequests, field.TypeInt, value)
		_node.Requests = value
	}
	if value, ok := _c.mutation.Tokens(); ok {
		_spec.SetField(upstreamusagedaily.FieldTokens, field.TypeInt64, value)
		_node.Tokens = value
	}
	if value, ok := _c.mutation.CostUsd(); ok {
		_spec.SetField(upstreamusagedaily.FieldCostUsd, field.TypeFloat64, value)
		_node.CostUsd = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamUsageDaily.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamUsageDailyUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamUsageDailyCreate) OnConflict(opts ...sql.ConflictOption) *UpstreamUsageDailyUpsertOne {
	_c.conflict = opts
	return &UpstreamUsageDailyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamUsageDaily.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamUsageDailyCreate) OnConflictColumns(columns ...string) *UpstreamUsageDailyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamUsageDailyUpsertOne{
		create: _c,
	}
}

type (
	// UpstreamUsageDailyUpsertOne is the builder for "upsert"-ing
	//  one UpstreamUsageDaily node.
	UpstreamUsageDailyUpsertOne struct {
		create *UpstreamUsageDailyCreate
	}

	// UpstreamUsageDailyUpsert is the "OnConflict" setter.
	UpstreamUsageDailyUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamUsageDailyUpsert) SetUpdatedAt(v time.Time) *UpstreamUsageDailyUpsert {
	u.Set(upstreamusagedaily.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamUsageDailyUpsert) UpdateUpdatedAt() *UpstreamUsageDailyUpsert {
	u.SetExcluded(upstreamusagedaily.FieldUpdatedAt)
	return u
}

// SetProviderID sets the "provider_id" field.
func (u *UpstreamUsageDailyUpsert) SetProviderID(v int64) *UpstreamUsageDailyUpsert {
	u.Set(upstreamusagedaily.FieldProviderID, v)
	return u
}

// UpdateProviderID sets the "provider_id" field to the value that was provided on create.
func (u *UpstreamUsageDailyUpsert) UpdateProviderID() *UpstreamUsageDailyUpsert {
	u.SetExcluded(upstreamusagedaily.FieldProviderID)
	return u
}

// AddProviderID adds v to the "provider_id" field.
func (u *UpstreamUsageDailyUpsert) AddProviderID(v int64) *UpstreamUsageDailyUpsert {
	u.Add(upstreamusagedaily.FieldProviderID, v)
	return u
}

// SetDay sets the "day" field.
func (u *UpstreamUsageDailyUpsert) SetDay(v time.Time) *UpstreamUsageDailyUpsert {
	u.Set(upstreamusagedaily.FieldDay, v)
	return u
}

// UpdateDay sets the "day" field to the value that was provided on create.
func (u *UpstreamUsageDailyUpsert) UpdateDay() *UpstreamUsageDailyUpsert {
	u.SetExcluded(upstreamusagedaily.FieldDay)
	return u
}

// SetScopeType sets the "scope_type" field.
func (u *UpstreamUsageDailyUpsert) SetScopeType(v string) *UpstreamUsageDailyUpsert {
	u.Set(upstreamusagedaily.FieldScopeType, v)
	return u
}

// UpdateScopeType sets the "scope_type" field to the value that was provided on create.
func (u *UpstreamUsageDailyUpsert) UpdateScopeType() *UpstreamUsageDailyUpsert {
	u.SetExcluded(upstreamusagedaily.FieldScopeType)
	return u
}

// SetScopeKey sets the "scope_key" field.
func (u *UpstreamUsageDailyUpsert) SetScopeKey(v string) *UpstreamUsageDailyUpsert {
	u.Set(upstreamusagedaily.FieldScopeKey, v)
	return u
}

// UpdateScopeKey sets the "scope_key" field to the value that was provided on create.
func (u *UpstreamUsageDailyUpsert) UpdateScopeKey() *UpstreamUsageDailyUpsert {
	u.SetExcluded(upstreamusagedaily.FieldScopeKey)
	return u
}

// SetScopeName sets the "scope_name" field.
func (u *UpstreamUsageDailyUpsert) SetScopeName(v string) *UpstreamUsageDailyUpsert {
	u.Set(upstreamusagedaily.FieldScopeName, v)
	return u
}

// UpdateScopeName sets the "scope_name" field to the value that was provided on create.
func (u *UpstreamUsageDailyUpsert) UpdateScopeName() *UpstreamUsageDailyUpsert {
	u.SetExcluded(upstreamusagedaily.FieldScopeName)
	return u
}

// SetRequests sets the "requests" field.
func (u *UpstreamUsageDailyUpsert) SetRequests(v int) *UpstreamUsageDailyUpsert {
	u.Set(upstreamusagedaily.FieldRequests, v)
	return u
}

// UpdateRequests sets the "requests" field to the value that was provided on create.
func (u *UpstreamUsageDailyUpsert) UpdateRequests() *UpstreamUsageDailyUpsert {
	u.SetExcluded(upstreamusagedaily.FieldRequests)
	return u
}

// AddRequests adds v to the "requests" field.
func (u *UpstreamUsageDailyUpsert) AddRequests(v int) *UpstreamUsageDailyUpsert {
	u.Add(upstreamusagedaily.FieldRequests, v)
	return u
}

// SetTokens sets the "tokens" field.
func (u *UpstreamUsageDailyUpsert) SetTokens(v int64) *UpstreamUsageDailyUpsert {
	u.Set(upstreamusagedaily.FieldTokens, v)
	return u
}

// UpdateTokens sets the "tokens" field to the value that was provided on create.
func (u *UpstreamUsageDailyUpsert) UpdateTokens() *UpstreamUsageDailyUpsert {
	u.SetExcluded(upstreamusagedaily.FieldTokens)
	return u
}

// AddTokens adds v to the "tokens" field.
func (u *UpstreamUsageDailyUpsert) AddTokens(v int64) *UpstreamUsageDailyUpsert {
	u.Add(upstreamusagedaily.FieldTokens, v)
	return u
}

// SetCostUsd sets the "cost_usd" field.
func (u *UpstreamUsageDailyUpsert) SetCostUsd(v float64) *UpstreamUsageDailyUpsert {
	u.Set(upstreamusagedaily.FieldCostUsd, v)
	return u
}

// UpdateCostUsd sets the "cost_usd" field to the value that was provided on create.
func (u *UpstreamUsageDailyUpsert) UpdateCostUsd() *UpstreamUsageDailyUpsert {
	u.SetExcluded(upstreamusagedaily.FieldCostUsd)
	return u
}

// AddCostUsd adds v to the "cost_usd" field.
func (u *UpstreamUsageDailyUpsert) AddCostUsd(v float64) *UpstreamUsageDailyUpsert {
	u.Add(upstreamusagedaily.FieldCostUsd, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UpstreamUsageDaily.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamUsageDailyUpsertOne) UpdateNewValues() *UpstreamUsageDailyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(upstreamusagedaily.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamUsageDaily.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UpstreamUsageDailyUpsertOne) Ignore() *UpstreamUsageDailyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamUsageDailyUpsertOne) DoNothing() *UpstreamUsageDailyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamUsageDailyCreate.OnConflict
// documentation for more info.
func (u *UpstreamUsageDailyUpsertOne) Update(set func(*UpstreamUsageDailyUpsert)) *UpstreamUsageDailyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamUsageDailyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamUsageDailyUpsertOne) SetUpdatedAt(v time.Time) *UpstreamUsageDailyUpsertOne {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamUsageDailyUpsertOne) UpdateUpdatedAt() *UpstreamUsageDailyUpsertOne {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetProviderID sets the "provider_id" field.
func (u *UpstreamUsageDailyUpsertOne) SetProviderID(v int64) *UpstreamUsageDailyUpsertOne {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.SetProviderID(v)
	})
}

// AddProviderID adds v to the "provider_id" field.
func (u *UpstreamUsageDailyUpsertOne) AddProviderID(v int64) *UpstreamUsageDailyUpsertOne {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.AddProviderID(v)
	})
}

// UpdateProviderID sets the "provider_id" field to the value that was provided on create.
func (u *UpstreamUsageDailyUpsertOne) UpdateProviderID() *UpstreamUsageDailyUpsertOne {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.UpdateProviderID()
	})
}

// SetDay sets the "day" field.
func (u *UpstreamUsageDailyUpsertOne) SetDay(v time.Time) *UpstreamUsageDailyUpsertOne {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.SetDay(v)
	})
}

// UpdateDay sets the "day" field to the value that was provided on create.
func (u *UpstreamUsageDailyUpsertOne) UpdateDay() *UpstreamUsageDailyUpsertOne {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.UpdateDay()
	})
}

// SetScopeType sets the "scope_type" field.
func (u *UpstreamUsageDailyUpsertOne) SetScopeType(v string) *UpstreamUsageDailyUpsertOne {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.SetScopeType(v)
	})
}

// UpdateScopeType sets the "scope_type" field to the value that was provided on create.
func (u *UpstreamUsageDailyUpsertOne) UpdateScopeType() *UpstreamUsageDailyUpsertOne {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.UpdateScopeType()
	})
}

// SetScopeKey sets the "scope_key" field.
func (u *UpstreamUsageDailyUpsertOne) SetScopeKey(v string) *UpstreamUsageDailyUpsertOne {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.SetScopeKey(v)
	})
}

// UpdateScopeKey sets the "scope_key" field to the value that was provided on create.
func (u *UpstreamUsageDailyUpsertOne) UpdateScopeKey() *UpstreamUsageDailyUpsertOne {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.UpdateScopeKey()
	})
}

// SetScopeName sets the "scope_name" field.
func (u *UpstreamUsageDailyUpsertOne) SetScopeName(v string) *UpstreamUsageDailyUpsertOne {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.SetScopeName(v)
	})
}

// UpdateScopeName sets the "scope_name" field to the value that was provided on create.
func (u *UpstreamUsageDailyUpsertOne) UpdateScopeName() *UpstreamUsageDailyUpsertOne {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.UpdateScopeName()
	})
}

// SetRequests sets the "requests" field.
func (u *UpstreamUsageDailyUpsertOne) SetRequests(v int) *UpstreamUsageDailyUpsertOne {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.SetRequests(v)
	})
}

// AddRequests adds v to the "requests" field.
func (u *UpstreamUsageDailyUpsertOne) AddRequests(v int) *UpstreamUsageDailyUpsertOne {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.AddRequests(v)
	})
}

// UpdateRequests sets the "requests" field to the value that was provided on create.
func (u *UpstreamUsageDailyUpsertOne) UpdateRequests() *UpstreamUsageDailyUpsertOne {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.UpdateRequests()
	})
}

// SetTokens sets the "tokens" field.
func (u *UpstreamUsageDailyUpsertOne) SetTokens(v int64) *UpstreamUsageDailyUpsertOne {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.SetTokens(v)
	})
}

// AddTokens adds v to the "tokens" field.
func (u *UpstreamUsageDailyUpsertOne) AddTokens(v int64) *UpstreamUsageDailyUpsertOne {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.AddTokens(v)
	})
}

// UpdateTokens sets the "tokens" field to the value that was provided on create.
func (u *UpstreamUsageDailyUpsertOne) UpdateTokens() *UpstreamUsageDailyUpsertOne {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.UpdateTokens()
	})
}

// SetCostUsd sets the "cost_usd" field.
func (u *UpstreamUsageDailyUpsertOne) SetCostUsd(v float64) *UpstreamUsageDailyUpsertOne {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.SetCostUsd(v)
	})
}

// AddCostUsd adds v to the "cost_usd" field.
func (u *UpstreamUsageDailyUpsertOne) AddCostUsd(v float64) *UpstreamUsageDailyUpsertOne {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.AddCostUsd(v)
	})
}

// UpdateCostUsd sets the "cost_usd" field to the value that was provided on create.
func (u *UpstreamUsageDailyUpsertOne) UpdateCostUsd() *UpstreamUsageDailyUpsertOne {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.UpdateCostUsd()
	})
}

// Exec executes the query.
func (u *UpstreamUsageDailyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamUsageDailyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamUsageDailyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UpstreamUsageDailyUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UpstreamUsageDailyUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UpstreamUsageDailyCreateBulk is the builder for creating many UpstreamUsageDaily entities in bulk.
type UpstreamUsageDailyCreateBulk struct {
	config
	err      error
	builders []*UpstreamUsageDailyCreate
	conflict []sql.ConflictOption
}

// Save creates the UpstreamUsageDaily entities in the database.
func (_c *UpstreamUsageDailyCreateBulk) Save(ctx context.Context) ([]*UpstreamUsageDaily, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UpstreamUsageDaily, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpstreamUsageDailyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UpstreamUsageDailyCreateBulk) SaveX(ctx context.Context) []*UpstreamUsageDaily {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamUsageDailyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamUsageDailyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamUsageDaily.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamUsageDailyUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamUsageDailyCreateBulk) OnConflict(opts ...sql.ConflictOption) *UpstreamUsageDailyUpsertBulk {
	_c.conflict = opts
	return &UpstreamUsageDailyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamUsageDaily.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamUsageDailyCreateBulk) OnConflictColumns(columns ...string) *UpstreamUsageDailyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamUsageDailyUpsertBulk{
		create: _c,
	}
}

// UpstreamUsageDailyUpsertBulk is the builder for "upsert"-ing
// a bulk of UpstreamUsageDaily nodes.
type UpstreamUsageDailyUpsertBulk struct {
	create *UpstreamUsageDailyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UpstreamUsageDaily.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamUsageDailyUpsertBulk) UpdateNewValues() *UpstreamUsageDailyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(upstreamusagedaily.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamUsageDaily.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UpstreamUsageDailyUpsertBulk) Ignore() *UpstreamUsageDailyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamUsageDailyUpsertBulk) DoNothing() *UpstreamUsageDailyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamUsageDailyCreateBulk.OnConflict
// documentation for more info.
func (u *UpstreamUsageDailyUpsertBulk) Update(set func(*UpstreamUsageDailyUpsert)) *UpstreamUsageDailyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamUsageDailyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamUsageDailyUpsertBulk) SetUpdatedAt(v time.Time) *UpstreamUsageDailyUpsertBulk {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamUsageDailyUpsertBulk) UpdateUpdatedAt() *UpstreamUsageDailyUpsertBulk {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetProviderID sets the "provider_id" field.
func (u *UpstreamUsageDailyUpsertBulk) SetProviderID(v int64) *UpstreamUsageDailyUpsertBulk {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.SetProviderID(v)
	})
}

// AddProviderID adds v to the "provider_id" field.
func (u *UpstreamUsageDailyUpsertBulk) AddProviderID(v int64) *UpstreamUsageDailyUpsertBulk {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.AddProviderID(v)
	})
}

// UpdateProviderID sets the "provider_id" field to the value that was provided on create.
func (u *UpstreamUsageDailyUpsertBulk) UpdateProviderID() *UpstreamUsageDailyUpsertBulk {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.UpdateProviderID()
	})
}

// SetDay sets the "day" field.
func (u *UpstreamUsageDailyUpsertBulk) SetDay(v time.Time) *UpstreamUsageDailyUpsertBulk {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.SetDay(v)
	})
}

// UpdateDay sets the "day" field to the value that was provided on create.
func (u *UpstreamUsageDailyUpsertBulk) UpdateDay() *UpstreamUsageDailyUpsertBulk {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.UpdateDay()
	})
}

// SetScopeType sets the "scope_type" field.
func (u *UpstreamUsageDailyUpsertBulk) SetScopeType(v string) *UpstreamUsageDailyUpsertBulk {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.SetScopeType(v)
	})
}

// UpdateScopeType sets the "scope_type" field to the value that was provided on create.
func (u *UpstreamUsageDailyUpsertBulk) UpdateScopeType() *UpstreamUsageDailyUpsertBulk {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.UpdateScopeType()
	})
}

// SetScopeKey sets the "scope_key" field.
func (u *UpstreamUsageDailyUpsertBulk) SetScopeKey(v string) *UpstreamUsageDailyUpsertBulk {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.SetScopeKey(v)
	})
}

// UpdateScopeKey sets the "scope_key" field to the value that was provided on create.
func (u *UpstreamUsageDailyUpsertBulk) UpdateScopeKey() *UpstreamUsageDailyUpsertBulk {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.UpdateScopeKey()
	})
}

// SetScopeName sets the "scope_name" field.
func (u *UpstreamUsageDailyUpsertBulk) SetScopeName(v string) *UpstreamUsageDailyUpsertBulk {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.SetScopeName(v)
	})
}

// UpdateScopeName sets the "scope_name" field to the value that was provided on create.
func (u *UpstreamUsageDailyUpsertBulk) UpdateScopeName() *UpstreamUsageDailyUpsertBulk {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.UpdateScopeName()
	})
}

// SetRequests sets the "requests" field.
func (u *UpstreamUsageDailyUpsertBulk) SetRequests(v int) *UpstreamUsageDailyUpsertBulk {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.SetRequests(v)
	})
}

// AddRequests adds v to the "requests" field.
func (u *UpstreamUsageDailyUpsertBulk) AddRequests(v int) *UpstreamUsageDailyUpsertBulk {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.AddRequests(v)
	})
}

// UpdateRequests sets the "requests" field to the value that was provided on create.
func (u *UpstreamUsageDailyUpsertBulk) UpdateRequests() *UpstreamUsageDailyUpsertBulk {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.UpdateRequests()
	})
}

// SetTokens sets the "tokens" field.
func (u *UpstreamUsageDailyUpsertBulk) SetTokens(v int64) *UpstreamUsageDailyUpsertBulk {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.SetTokens(v)
	})
}

// AddTokens adds v to the "tokens" field.
func (u *UpstreamUsageDailyUpsertBulk) AddTokens(v int64) *UpstreamUsageDailyUpsertBulk {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.AddTokens(v)
	})
}

// UpdateTokens sets the "tokens" field to the value that was provided on create.
func (u *UpstreamUsageDailyUpsertBulk) UpdateTokens() *UpstreamUsageDailyUpsertBulk {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.UpdateTokens()
	})
}

// SetCostUsd sets the "cost_usd" field.
func (u *UpstreamUsageDailyUpsertBulk) SetCostUsd(v float64) *UpstreamUsageDailyUpsertBulk {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.SetCostUsd(v)
	})
}

// AddCostUsd adds v to the "cost_usd" field.
func (u *UpstreamUsageDailyUpsertBulk) AddCostUsd(v float64) *UpstreamUsageDailyUpsertBulk {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.AddCostUsd(v)
	})
}

// UpdateCostUsd sets the "cost_usd" field to the value that was provided on create.
func (u *UpstreamUsageDailyUpsertBulk) UpdateCostUsd() *UpstreamUsageDailyUpsertBulk {
	return u.Update(func(s *UpstreamUsageDailyUpsert) {
		s.UpdateCostUsd()
	})
}

// Exec executes the query.
func (u *UpstreamUsageDailyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UpstreamUsageDailyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamUsageDailyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamUsageDailyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
