// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/upstreamprovider"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// UpstreamProviderUpdate is the builder for updating UpstreamProvider entities.
type UpstreamProviderUpdate struct {
	config
	hooks    []Hook
	mutation *UpstreamProviderMutation
}

// Where appends a list predicates to the UpstreamProviderUpdate builder.
func (_u *UpstreamProviderUpdate) Where(ps ...predicate.UpstreamProvider) *UpstreamProviderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UpstreamProviderUpdate) SetUpdatedAt(v time.Time) *UpstreamProviderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *UpstreamProviderUpdate) SetName(v string) *UpstreamProviderUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableName(v *string) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *UpstreamProviderUpdate) SetType(v string) *UpstreamProviderUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableType(v *string) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetSiteURL sets the "site_url" field.
func (_u *UpstreamProviderUpdate) SetSiteURL(v string) *UpstreamProviderUpdate {
	_u.mutation.SetSiteURL(v)
	return _u
}

// SetNillableSiteURL sets the "site_url" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableSiteURL(v *string) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetSiteURL(*v)
	}
	return _u
}

// SetAPIBaseURL sets the "api_base_url" field.
func (_u *UpstreamProviderUpdate) SetAPIBaseURL(v string) *UpstreamProviderUpdate {
	_u.mutation.SetAPIBaseURL(v)
	return _u
}

// SetNillableAPIBaseURL sets the "api_base_url" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableAPIBaseURL(v *string) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetAPIBaseURL(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *UpstreamProviderUpdate) SetStatus(v string) *UpstreamProviderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableStatus(v *string) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCredentials sets the "credentials" field.
func (_u *UpstreamProviderUpdate) SetCredentials(v map[string]interface{}) *UpstreamProviderUpdate {
	_u.mutation.SetCredentials(v)
	return _u
}

// SetBalanceThreshold sets the "balance_threshold" field.
func (_u *UpstreamProviderUpdate) SetBalanceThreshold(v float64) *UpstreamProviderUpdate {
	_u.mutation.ResetBalanceThreshold()
	_u.mutation.SetBalanceThreshold(v)
	return _u
}

// SetNillableBalanceThreshold sets the "balance_threshold" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableBalanceThreshold(v *float64) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetBalanceThreshold(*v)
	}
	return _u
}

// AddBalanceThreshold adds value to the "balance_threshold" field.
func (_u *UpstreamProviderUpdate) AddBalanceThreshold(v float64) *UpstreamProviderUpdate {
	_u.mutation.AddBalanceThreshold(v)
	return _u
}

// ClearBalanceThreshold clears the value of the "balance_threshold" field.
func (_u *UpstreamProviderUpdate) ClearBalanceThreshold() *UpstreamProviderUpdate {
	_u.mutation.ClearBalanceThreshold()
	return _u
}

// SetNotifyOnPriceChange sets the "notify_on_price_change" field.
func (_u *UpstreamProviderUpdate) SetNotifyOnPriceChange(v bool) *UpstreamProviderUpdate {
	_u.mutation.SetNotifyOnPriceChange(v)
	return _u
}

// SetNillableNotifyOnPriceChange sets the "notify_on_price_change" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableNotifyOnPriceChange(v *bool) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetNotifyOnPriceChange(*v)
	}
	return _u
}

// SetRechargeRatio sets the "recharge_ratio" field.
func (_u *UpstreamProviderUpdate) SetRechargeRatio(v float64) *UpstreamProviderUpdate {
	_u.mutation.ResetRechargeRatio()
	_u.mutation.SetRechargeRatio(v)
	return _u
}

// SetNillableRechargeRatio sets the "recharge_ratio" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableRechargeRatio(v *float64) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetRechargeRatio(*v)
	}
	return _u
}

// AddRechargeRatio adds value to the "recharge_ratio" field.
func (_u *UpstreamProviderUpdate) AddRechargeRatio(v float64) *UpstreamProviderUpdate {
	_u.mutation.AddRechargeRatio(v)
	return _u
}

// SetRefreshIntervalMinutes sets the "refresh_interval_minutes" field.
func (_u *UpstreamProviderUpdate) SetRefreshIntervalMinutes(v int) *UpstreamProviderUpdate {
	_u.mutation.ResetRefreshIntervalMinutes()
	_u.mutation.SetRefreshIntervalMinutes(v)
	return _u
}

// SetNillableRefreshIntervalMinutes sets the "refresh_interval_minutes" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableRefreshIntervalMinutes(v *int) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetRefreshIntervalMinutes(*v)
	}
	return _u
}

// AddRefreshIntervalMinutes adds value to the "refresh_interval_minutes" field.
func (_u *UpstreamProviderUpdate) AddRefreshIntervalMinutes(v int) *UpstreamProviderUpdate {
	_u.mutation.AddRefreshIntervalMinutes(v)
	return _u
}

// SetLatestSnapshot sets the "latest_snapshot" field.
func (_u *UpstreamProviderUpdate) SetLatestSnapshot(v *domain.UpstreamSnapshot) *UpstreamProviderUpdate {
	_u.mutation.SetLatestSnapshot(v)
	return _u
}

// ClearLatestSnapshot clears the value of the "latest_snapshot" field.
func (_u *UpstreamProviderUpdate) ClearLatestSnapshot() *UpstreamProviderUpdate {
	_u.mutation.ClearLatestSnapshot()
	return _u
}

// SetLastRefreshedAt sets the "last_refreshed_at" field.
func (_u *UpstreamProviderUpdate) SetLastRefreshedAt(v time.Time) *UpstreamProviderUpdate {
	_u.mutation.SetLastRefreshedAt(v)
	return _u
}

// SetNillableLastRefreshedAt sets the "last_refreshed_at" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableLastRefreshedAt(v *time.Time) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetLastRefreshedAt(*v)
	}
	return _u
}

// ClearLastRefreshedAt clears the value of the "last_refreshed_at" field.
func (_u *UpstreamProviderUpdate) ClearLastRefreshedAt() *UpstreamProviderUpdate {
	_u.mutation.ClearLastRefreshedAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *UpstreamProviderUpdate) SetLastError(v string) *UpstreamProviderUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableLastError(v *string) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (_u *UpstreamProviderUpdate) SetConsecutiveFailures(v int) *UpstreamProviderUpdate {
	_u.mutation.ResetConsecutiveFailures()
	_u.mutation.SetConsecutiveFailures(v)
	return _u
}

// SetNillableConsecutiveFailures sets the "consecutive_failures" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableConsecutiveFailures(v *int) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetConsecutiveFailures(*v)
	}
	return _u
}

// AddConsecutiveFailures adds value to the "consecutive_failures" field.
func (_u *UpstreamProviderUpdate) AddConsecutiveFailures(v int) *UpstreamProviderUpdate {
	_u.mutation.AddConsecutiveFailures(v)
	return _u
}

// SetBalanceAlerted sets the "balance_alerted" field.
func (_u *UpstreamProviderUpdate) SetBalanceAlerted(v bool) *UpstreamProviderUpdate {
	_u.mutation.SetBalanceAlerted(v)
	return _u
}

// SetNillableBalanceAlerted sets the "balance_alerted" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableBalanceAlerted(v *bool) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetBalanceAlerted(*v)
	}
	return _u
}

// SetRefreshStartedAt sets the "refresh_started_at" field.
func (_u *UpstreamProviderUpdate) SetRefreshStartedAt(v time.Time) *UpstreamProviderUpdate {
	_u.mutation.SetRefreshStartedAt(v)
	return _u
}

// SetNillableRefreshStartedAt sets the "refresh_started_at" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableRefreshStartedAt(v *time.Time) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetRefreshStartedAt(*v)
	}
	return _u
}

// ClearRefreshStartedAt clears the value of the "refresh_started_at" field.
func (_u *UpstreamProviderUpdate) ClearRefreshStartedAt() *UpstreamProviderUpdate {
	_u.mutation.ClearRefreshStartedAt()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *UpstreamProviderUpdate) SetRemark(v string) *UpstreamProviderUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *UpstreamProviderUpdate) SetNillableRemark(v *string) *UpstreamProviderUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// Mutation returns the UpstreamProviderMutation object of the builder.
func (_u *UpstreamProviderUpdate) Mutation() *UpstreamProviderMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UpstreamProviderUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamProviderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UpstreamProviderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamProviderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UpstreamProviderUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := upstreamprovider.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamProviderUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := upstreamprovider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := upstreamprovider.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SiteURL(); ok {
		if err := upstreamprovider.SiteURLValidator(v); err != nil {
			return &ValidationError{Name: "site_url", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.site_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIBaseURL(); ok {
		if err := upstreamprovider.APIBaseURLValidator(v); err != nil {
			return &ValidationError{Name: "api_base_url", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.api_base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := upstreamprovider.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.status": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamProviderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamprovider.Table, upstreamprovider.Columns, sqlgraph.NewFieldSpec(upstreamprovider.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamprovider.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(upstreamprovider.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(upstreamprovider.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SiteURL(); ok {
		_spec.SetField(upstreamprovider.FieldSiteURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIBaseURL(); ok {
		_spec.SetField(upstreamprovider.FieldAPIBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(upstreamprovider.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Credentials(); ok {
		_spec.SetField(upstreamprovider.FieldCredentials, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.BalanceThreshold(); ok {
		_spec.SetField(upstreamprovider.FieldBalanceThreshold, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceThreshold(); ok {
		_spec.AddField(upstreamprovider.FieldBalanceThreshold, field.TypeFloat64, value)
	}
	if _u.mutation.BalanceThresholdCleared() {
		_spec.ClearField(upstreamprovider.FieldBalanceThreshold, field.TypeFloat64)
	}
	if value, ok := _u.mutation.NotifyOnPriceChange(); ok {
		_spec.SetField(upstreamprovider.FieldNotifyOnPriceChange, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RechargeRatio(); ok {
		_spec.SetField(upstreamprovider.FieldRechargeRatio, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRechargeRatio(); ok {
		_spec.AddField(upstreamprovider.FieldRechargeRatio, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RefreshIntervalMinutes(); ok {
		_spec.SetField(upstreamprovider.FieldRefreshIntervalMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRefreshIntervalMinutes(); ok {
		_spec.AddField(upstreamprovider.FieldRefreshIntervalMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LatestSnapshot(); ok {
		_spec.SetField(upstreamprovider.FieldLatestSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.LatestSnapshotCleared() {
		_spec.ClearField(upstreamprovider.FieldLatestSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.LastRefreshedAt(); ok {
		_spec.SetField(upstreamprovider.FieldLastRefreshedAt, field.TypeTime, value)
	}
	if _u.mutation.LastRefreshedAtCleared() {
		_spec.ClearField(upstreamprovider.FieldLastRefreshedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(upstreamprovider.FieldLastError, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConsecutiveFailures(); ok {
		_spec.SetField(upstreamprovider.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveFailures(); ok {
		_spec.AddField(upstreamprovider.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BalanceAlerted(); ok {
		_spec.SetField(upstreamprovider.FieldBalanceAlerted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RefreshStartedAt(); ok {
		_spec.SetField(upstreamprovider.FieldRefreshStartedAt, field.TypeTime, value)
	}
	if _u.mutation.RefreshStartedAtCleared() {
		_spec.ClearField(upstreamprovider.FieldRefreshStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(upstreamprovider.FieldRemark, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UpstreamProviderUpdateOne is the builder for updating a single UpstreamProvider entity.
type UpstreamProviderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UpstreamProviderMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UpstreamProviderUpdateOne) SetUpdatedAt(v time.Time) *UpstreamProviderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *UpstreamProviderUpdateOne) SetName(v string) *UpstreamProviderUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableName(v *string) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *UpstreamProviderUpdateOne) SetType(v string) *UpstreamProviderUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableType(v *string) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetSiteURL sets the "site_url" field.
func (_u *UpstreamProviderUpdateOne) SetSiteURL(v string) *UpstreamProviderUpdateOne {
	_u.mutation.SetSiteURL(v)
	return _u
}

// SetNillableSiteURL sets the "site_url" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableSiteURL(v *string) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetSiteURL(*v)
	}
	return _u
}

// SetAPIBaseURL sets the "api_base_url" field.
func (_u *UpstreamProviderUpdateOne) SetAPIBaseURL(v string) *UpstreamProviderUpdateOne {
	_u.mutation.SetAPIBaseURL(v)
	return _u
}

// SetNillableAPIBaseURL sets the "api_base_url" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableAPIBaseURL(v *string) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetAPIBaseURL(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *UpstreamProviderUpdateOne) SetStatus(v string) *UpstreamProviderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableStatus(v *string) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCredentials sets the "credentials" field.
func (_u *UpstreamProviderUpdateOne) SetCredentials(v map[string]interface{}) *UpstreamProviderUpdateOne {
	_u.mutation.SetCredentials(v)
	return _u
}

// SetBalanceThreshold sets the "balance_threshold" field.
func (_u *UpstreamProviderUpdateOne) SetBalanceThreshold(v float64) *UpstreamProviderUpdateOne {
	_u.mutation.ResetBalanceThreshold()
	_u.mutation.SetBalanceThreshold(v)
	return _u
}

// SetNillableBalanceThreshold sets the "balance_threshold" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableBalanceThreshold(v *float64) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetBalanceThreshold(*v)
	}
	return _u
}

// AddBalanceThreshold adds value to the "balance_threshold" field.
func (_u *UpstreamProviderUpdateOne) AddBalanceThreshold(v float64) *UpstreamProviderUpdateOne {
	_u.mutation.AddBalanceThreshold(v)
	return _u
}

// ClearBalanceThreshold clears the value of the "balance_threshold" field.
func (_u *UpstreamProviderUpdateOne) ClearBalanceThreshold() *UpstreamProviderUpdateOne {
	_u.mutation.ClearBalanceThreshold()
	return _u
}

// SetNotifyOnPriceChange sets the "notify_on_price_change" field.
func (_u *UpstreamProviderUpdateOne) SetNotifyOnPriceChange(v bool) *UpstreamProviderUpdateOne {
	_u.mutation.SetNotifyOnPriceChange(v)
	return _u
}

// SetNillableNotifyOnPriceChange sets the "notify_on_price_change" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableNotifyOnPriceChange(v *bool) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetNotifyOnPriceChange(*v)
	}
	return _u
}

// SetRechargeRatio sets the "recharge_ratio" field.
func (_u *UpstreamProviderUpdateOne) SetRechargeRatio(v float64) *UpstreamProviderUpdateOne {
	_u.mutation.ResetRechargeRatio()
	_u.mutation.SetRechargeRatio(v)
	return _u
}

// SetNillableRechargeRatio sets the "recharge_ratio" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableRechargeRatio(v *float64) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetRechargeRatio(*v)
	}
	return _u
}

// AddRechargeRatio adds value to the "recharge_ratio" field.
func (_u *UpstreamProviderUpdateOne) AddRechargeRatio(v float64) *UpstreamProviderUpdateOne {
	_u.mutation.AddRechargeRatio(v)
	return _u
}

// SetRefreshIntervalMinutes sets the "refresh_interval_minutes" field.
func (_u *UpstreamProviderUpdateOne) SetRefreshIntervalMinutes(v int) *UpstreamProviderUpdateOne {
	_u.mutation.ResetRefreshIntervalMinutes()
	_u.mutation.SetRefreshIntervalMinutes(v)
	return _u
}

// SetNillableRefreshIntervalMinutes sets the "refresh_interval_minutes" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableRefreshIntervalMinutes(v *int) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetRefreshIntervalMinutes(*v)
	}
	return _u
}

// AddRefreshIntervalMinutes adds value to the "refresh_interval_minutes" field.
func (_u *UpstreamProviderUpdateOne) AddRefreshIntervalMinutes(v int) *UpstreamProviderUpdateOne {
	_u.mutation.AddRefreshIntervalMinutes(v)
	return _u
}

// SetLatestSnapshot sets the "latest_snapshot" field.
func (_u *UpstreamProviderUpdateOne) SetLatestSnapshot(v *domain.UpstreamSnapshot) *UpstreamProviderUpdateOne {
	_u.mutation.SetLatestSnapshot(v)
	return _u
}

// ClearLatestSnapshot clears the value of the "latest_snapshot" field.
func (_u *UpstreamProviderUpdateOne) ClearLatestSnapshot() *UpstreamProviderUpdateOne {
	_u.mutation.ClearLatestSnapshot()
	return _u
}

// SetLastRefreshedAt sets the "last_refreshed_at" field.
func (_u *UpstreamProviderUpdateOne) SetLastRefreshedAt(v time.Time) *UpstreamProviderUpdateOne {
	_u.mutation.SetLastRefreshedAt(v)
	return _u
}

// SetNillableLastRefreshedAt sets the "last_refreshed_at" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableLastRefreshedAt(v *time.Time) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetLastRefreshedAt(*v)
	}
	return _u
}

// ClearLastRefreshedAt clears the value of the "last_refreshed_at" field.
func (_u *UpstreamProviderUpdateOne) ClearLastRefreshedAt() *UpstreamProviderUpdateOne {
	_u.mutation.ClearLastRefreshedAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *UpstreamProviderUpdateOne) SetLastError(v string) *UpstreamProviderUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableLastError(v *string) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// SetConsecutiveFailures sets the "consecutive_failures" field.
func (_u *UpstreamProviderUpdateOne) SetConsecutiveFailures(v int) *UpstreamProviderUpdateOne {
	_u.mutation.ResetConsecutiveFailures()
	_u.mutation.SetConsecutiveFailures(v)
	return _u
}

// SetNillableConsecutiveFailures sets the "consecutive_failures" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableConsecutiveFailures(v *int) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetConsecutiveFailures(*v)
	}
	return _u
}

// AddConsecutiveFailures adds value to the "consecutive_failures" field.
func (_u *UpstreamProviderUpdateOne) AddConsecutiveFailures(v int) *UpstreamProviderUpdateOne {
	_u.mutation.AddConsecutiveFailures(v)
	return _u
}

// SetBalanceAlerted sets the "balance_alerted" field.
func (_u *UpstreamProviderUpdateOne) SetBalanceAlerted(v bool) *UpstreamProviderUpdateOne {
	_u.mutation.SetBalanceAlerted(v)
	return _u
}

// SetNillableBalanceAlerted sets the "balance_alerted" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableBalanceAlerted(v *bool) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetBalanceAlerted(*v)
	}
	return _u
}

// SetRefreshStartedAt sets the "refresh_started_at" field.
func (_u *UpstreamProviderUpdateOne) SetRefreshStartedAt(v time.Time) *UpstreamProviderUpdateOne {
	_u.mutation.SetRefreshStartedAt(v)
	return _u
}

// SetNillableRefreshStartedAt sets the "refresh_started_at" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableRefreshStartedAt(v *time.Time) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetRefreshStartedAt(*v)
	}
	return _u
}

// ClearRefreshStartedAt clears the value of the "refresh_started_at" field.
func (_u *UpstreamProviderUpdateOne) ClearRefreshStartedAt() *UpstreamProviderUpdateOne {
	_u.mutation.ClearRefreshStartedAt()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *UpstreamProviderUpdateOne) SetRemark(v string) *UpstreamProviderUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *UpstreamProviderUpdateOne) SetNillableRemark(v *string) *UpstreamProviderUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// Mutation returns the UpstreamProviderMutation object of the builder.
func (_u *UpstreamProviderUpdateOne) Mutation() *UpstreamProviderMutation {
	return _u.mutation
}

// Where appends a list predicates to the UpstreamProviderUpdate builder.
func (_u *UpstreamProviderUpdateOne) Where(ps ...predicate.UpstreamProvider) *UpstreamProviderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UpstreamProviderUpdateOne) Select(field string, fields ...string) *UpstreamProviderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UpstreamProvider entity.
func (_u *UpstreamProviderUpdateOne) Save(ctx context.Context) (*UpstreamProvider, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamProviderUpdateOne) SaveX(ctx context.Context) *UpstreamProvider {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UpstreamProviderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamProviderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UpstreamProviderUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := upstreamprovider.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamProviderUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := upstreamprovider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := upstreamprovider.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SiteURL(); ok {
		if err := upstreamprovider.SiteURLValidator(v); err != nil {
			return &ValidationError{Name: "site_url", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.site_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.APIBaseURL(); ok {
		if err := upstreamprovider.APIBaseURLValidator(v); err != nil {
			return &ValidationError{Name: "api_base_url", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.api_base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := upstreamprovider.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UpstreamProvider.status": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamProviderUpdateOne) sqlSave(ctx context.Context) (_node *UpstreamProvider, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamprovider.Table, upstreamprovider.Columns, sqlgraph.NewFieldSpec(upstreamprovider.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UpstreamProvider.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upstreamprovider.FieldID)
		for _, f := range fields {
			if !upstreamprovider.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upstreamprovider.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamprovider.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(upstreamprovider.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(upstreamprovider.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.SiteURL(); ok {
		_spec.SetField(upstreamprovider.FieldSiteURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.APIBaseURL(); ok {
		_spec.SetField(upstreamprovider.FieldAPIBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(upstreamprovider.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Credentials(); ok {
		_spec.SetField(upstreamprovider.FieldCredentials, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.BalanceThreshold(); ok {
		_spec.SetField(upstreamprovider.FieldBalanceThreshold, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceThreshold(); ok {
		_spec.AddField(upstreamprovider.FieldBalanceThreshold, field.TypeFloat64, value)
	}
	if _u.mutation.BalanceThresholdCleared() {
		_spec.ClearField(upstreamprovider.FieldBalanceThreshold, field.TypeFloat64)
	}
	if value, ok := _u.mutation.NotifyOnPriceChange(); ok {
		_spec.SetField(upstreamprovider.FieldNotifyOnPriceChange, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RechargeRatio(); ok {
		_spec.SetField(upstreamprovider.FieldRechargeRatio, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRechargeRatio(); ok {
		_spec.AddField(upstreamprovider.FieldRechargeRatio, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RefreshIntervalMinutes(); ok {
		_spec.SetField(upstreamprovider.FieldRefreshIntervalMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRefreshIntervalMinutes(); ok {
		_spec.AddField(upstreamprovider.FieldRefreshIntervalMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LatestSnapshot(); ok {
		_spec.SetField(upstreamprovider.FieldLatestSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.LatestSnapshotCleared() {
		_spec.ClearField(upstreamprovider.FieldLatestSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.LastRefreshedAt(); ok {
		_spec.SetField(upstreamprovider.FieldLastRefreshedAt, field.TypeTime, value)
	}
	if _u.mutation.LastRefreshedAtCleared() {
		_spec.ClearField(upstreamprovider.FieldLastRefreshedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(upstreamprovider.FieldLastError, field.TypeString, value)
	}
	if value, ok := _u.mutation.ConsecutiveFailures(); ok {
		_spec.SetField(upstreamprovider.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConsecutiveFailures(); ok {
		_spec.AddField(upstreamprovider.FieldConsecutiveFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.BalanceAlerted(); ok {
		_spec.SetField(upstreamprovider.FieldBalanceAlerted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RefreshStartedAt(); ok {
		_spec.SetField(upstreamprovider.FieldRefreshStartedAt, field.TypeTime, value)
	}
	if _u.mutation.RefreshStartedAtCleared() {
		_spec.ClearField(upstreamprovider.FieldRefreshStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(upstreamprovider.FieldRemark, field.TypeString, value)
	}
	_node = &UpstreamProvider{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamprovider.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
