// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/upstreamusagedaily"
)

// UpstreamUsageDailyUpdate is the builder for updating UpstreamUsageDaily entities.
type UpstreamUsageDailyUpdate struct {
	config
	hooks    []Hook
	mutation *UpstreamUsageDailyMutation
}

// Where appends a list predicates to the UpstreamUsageDailyUpdate builder.
func (_u *UpstreamUsageDailyUpdate) Where(ps ...predicate.UpstreamUsageDaily) *UpstreamUsageDailyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UpstreamUsageDailyUpdate) SetUpdatedAt(v time.Time) *UpstreamUsageDailyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProviderID sets the "provider_id" field.
func (_u *UpstreamUsageDailyUpdate) SetProviderID(v int64) *UpstreamUsageDailyUpdate {
	_u.mutation.ResetProviderID()
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *UpstreamUsageDailyUpdate) SetNillableProviderID(v *int64) *UpstreamUsageDailyUpdate {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// AddProviderID adds value to the "provider_id" field.
func (_u *UpstreamUsageDailyUpdate) AddProviderID(v int64) *UpstreamUsageDailyUpdate {
	_u.mutation.AddProviderID(v)
	return _u
}

// SetDay sets the "day" field.
func (_u *UpstreamUsageDailyUpdate) SetDay(v time.Time) *UpstreamUsageDailyUpdate {
	_u.mutation.SetDay(v)
	return _u
}

// SetNillableDay sets the "day" field if the given value is not nil.
func (_u *UpstreamUsageDailyUpdate) SetNillableDay(v *time.Time) *UpstreamUsageDailyUpdate {
	if v != nil {
		_u.SetDay(*v)
	}
	return _u
}

// SetScopeType sets the "scope_type" field.
func (_u *UpstreamUsageDailyUpdate) SetScopeType(v string) *UpstreamUsageDailyUpdate {
	_u.mutation.SetScopeType(v)
	return _u
}

// SetNillableScopeType sets the "scope_type" field if the given value is not nil.
func (_u *UpstreamUsageDailyUpdate) SetNillableScopeType(v *string) *UpstreamUsageDailyUpdate {
	if v != nil {
		_u.SetScopeType(*v)
	}
	return _u
}

// SetScopeKey sets the "scope_key" field.
func (_u *UpstreamUsageDailyUpdate) SetScopeKey(v string) *UpstreamUsageDailyUpdate {
	_u.mutation.SetScopeKey(v)
	return _u
}

// SetNillableScopeKey sets the "scope_key" field if the given value is not nil.
func (_u *UpstreamUsageDailyUpdate) SetNillableScopeKey(v *string) *UpstreamUsageDailyUpdate {
	if v != nil {
		_u.SetScopeKey(*v)
	}
	return _u
}

// SetScopeName sets the "scope_name" field.
func (_u *UpstreamUsageDailyUpdate) SetScopeName(v string) *UpstreamUsageDailyUpdate {
	_u.mutation.SetScopeName(v)
	return _u
}

// SetNillableScopeName sets the "scope_name" field if the given value is not nil.
func (_u *UpstreamUsageDailyUpdate) SetNillableScopeName(v *string) *UpstreamUsageDailyUpdate {
	if v != nil {
		_u.SetScopeName(*v)
	}
	return _u
}

// SetRequests sets the "requests" field.
func (_u *UpstreamUsageDailyUpdate) SetRequests(v int) *UpstreamUsageDailyUpdate {
	_u.mutation.ResetRequests()
	_u.mutation.SetRequests(v)
	return _u
}

// SetNillableRequests sets the "requests" field if the given value is not nil.
func (_u *UpstreamUsageDailyUpdate) SetNillableRequests(v *int) *UpstreamUsageDailyUpdate {
	if v != nil {
		_u.SetRequests(*v)
	}
	return _u
}

// AddRequests adds value to the "requests" field.
func (_u *UpstreamUsageDailyUpdate) AddRequests(v int) *UpstreamUsageDailyUpdate {
	_u.mutation.AddRequests(v)
	return _u
}

// SetTokens sets the "tokens" field.
func (_u *UpstreamUsageDailyUpdate) SetTokens(v int64) *UpstreamUsageDailyUpdate {
	_u.mutation.ResetTokens()
	_u.mutation.SetTokens(v)
	return _u
}

// SetNillableTokens sets the "tokens" field if the given value is not nil.
func (_u *UpstreamUsageDailyUpdate) SetNillableTokens(v *int64) *UpstreamUsageDailyUpdate {
	if v != nil {
		_u.SetTokens(*v)
	}
	return _u
}

// AddTokens adds value to the "tokens" field.
func (_u *UpstreamUsageDailyUpdate) AddTokens(v int64) *UpstreamUsageDailyUpdate {
	_u.mutation.AddTokens(v)
	return _u
}

// SetCostUsd sets the "cost_usd" field.
func (_u *UpstreamUsageDailyUpdate) SetCostUsd(v float64) *UpstreamUsageDailyUpdate {
	_u.mutation.ResetCostUsd()
	_u.mutation.SetCostUsd(v)
	return _u
}

// SetNillableCostUsd sets the "cost_usd" field if the given value is not nil.
func (_u *UpstreamUsageDailyUpdate) SetNillableCostUsd(v *float64) *UpstreamUsageDailyUpdate {
	if v != nil {
		_u.SetCostUsd(*v)
	}
	return _u
}

// AddCostUsd adds value to the "cost_usd" field.
func (_u *UpstreamUsageDailyUpdate) AddCostUsd(v float64) *UpstreamUsageDailyUpdate {
	_u.mutation.AddCostUsd(v)
	return _u
}

// Mutation returns the UpstreamUsageDailyMutation object of the builder.
func (_u *UpstreamUsageDailyUpdate) Mutation() *UpstreamUsageDailyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UpstreamUsageDailyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamUsageDailyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UpstreamUsageDailyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamUsageDailyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UpstreamUsageDailyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := upstreamusagedaily.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamUsageDailyUpdate) check() error {
	if v, ok := _u.mutation.ScopeType(); ok {
		if err := upstreamusagedaily.ScopeTypeValidator(v); err != nil {
			return &ValidationError{Name: "scope_type", err: fmt.Errorf(`ent: validator failed for field "UpstreamUsageDaily.scope_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScopeKey(); ok {
		if err := upstreamusagedaily.ScopeKeyValidator(v); err != nil {
			return &ValidationError{Name: "scope_key", err: fmt.Errorf(`ent: validator failed for field "UpstreamUsageDaily.scope_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScopeName(); ok {
		if err := upstreamusagedaily.ScopeNameValidator(v); err != nil {
			return &ValidationError{Name: "scope_name", err: fmt.Errorf(`ent: validator failed for field "UpstreamUsageDaily.scope_name": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamUsageDailyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamusagedaily.Table, upstreamusagedaily.Columns, sqlgraph.NewFieldSpec(upstreamusagedaily.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamusagedaily.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ProviderID(); ok {
		_spec.SetField(upstreamusagedaily.FieldProviderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProviderID(); ok {
		_spec.AddField(upstreamusagedaily.FieldProviderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Day(); ok {
		_spec.SetField(upstreamusagedaily.FieldDay, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ScopeType(); ok {
		_spec.SetField(upstreamusagedaily.FieldScopeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScopeKey(); ok {
		_spec.SetField(upstreamusagedaily.FieldScopeKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScopeName(); ok {
		_spec.SetField(upstreamusagedaily.FieldScopeName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Requests(); ok {
		_spec.SetField(upstreamusagedaily.FieldRequests, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRequests(); ok {
		_spec.AddField(upstreamusagedaily.FieldRequests, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Tokens(); ok {
		_spec.SetField(upstreamusagedaily.FieldTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTokens(); ok {
		_spec.AddField(upstreamusagedaily.FieldTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CostUsd(); ok {
		_spec.SetField(upstreamusagedaily.FieldCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostUsd(); ok {
		_spec.AddField(upstreamusagedaily.FieldCostUsd, field.TypeFloat64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamusagedaily.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UpstreamUsageDailyUpdateOne is the builder for updating a single UpstreamUsageDaily entity.
type UpstreamUsageDailyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UpstreamUsageDailyMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UpstreamUsageDailyUpdateOne) SetUpdatedAt(v time.Time) *UpstreamUsageDailyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProviderID sets the "provider_id" field.
func (_u *UpstreamUsageDailyUpdateOne) SetProviderID(v int64) *UpstreamUsageDailyUpdateOne {
	_u.mutation.ResetProviderID()
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *UpstreamUsageDailyUpdateOne) SetNillableProviderID(v *int64) *UpstreamUsageDailyUpdateOne {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// AddProviderID adds value to the "provider_id" field.
func (_u *UpstreamUsageDailyUpdateOne) AddProviderID(v int64) *UpstreamUsageDailyUpdateOne {
	_u.mutation.AddProviderID(v)
	return _u
}

// SetDay sets the "day" field.
func (_u *UpstreamUsageDailyUpdateOne) SetDay(v time.Time) *UpstreamUsageDailyUpdateOne {
	_u.mutation.SetDay(v)
	return _u
}

// SetNillableDay sets the "day" field if the given value is not nil.
func (_u *UpstreamUsageDailyUpdateOne) SetNillableDay(v *time.Time) *UpstreamUsageDailyUpdateOne {
	if v != nil {
		_u.SetDay(*v)
	}
	return _u
}

// SetScopeType sets the "scope_type" field.
func (_u *UpstreamUsageDailyUpdateOne) SetScopeType(v string) *UpstreamUsageDailyUpdateOne {
	_u.mutation.SetScopeType(v)
	return _u
}

// SetNillableScopeType sets the "scope_type" field if the given value is not nil.
func (_u *UpstreamUsageDailyUpdateOne) SetNillableScopeType(v *string) *UpstreamUsageDailyUpdateOne {
	if v != nil {
		_u.SetScopeType(*v)
	}
	return _u
}

// SetScopeKey sets the "scope_key" field.
func (_u *UpstreamUsageDailyUpdateOne) SetScopeKey(v string) *UpstreamUsageDailyUpdateOne {
	_u.mutation.SetScopeKey(v)
	return _u
}

// SetNillableScopeKey sets the "scope_key" field if the given value is not nil.
func (_u *UpstreamUsageDailyUpdateOne) SetNillableScopeKey(v *string) *UpstreamUsageDailyUpdateOne {
	if v != nil {
		_u.SetScopeKey(*v)
	}
	return _u
}

// SetScopeName sets the "scope_name" field.
func (_u *UpstreamUsageDailyUpdateOne) SetScopeName(v string) *UpstreamUsageDailyUpdateOne {
	_u.mutation.SetScopeName(v)
	return _u
}

// SetNillableScopeName sets the "scope_name" field if the given value is not nil.
func (_u *UpstreamUsageDailyUpdateOne) SetNillableScopeName(v *string) *UpstreamUsageDailyUpdateOne {
	if v != nil {
		_u.SetScopeName(*v)
	}
	return _u
}

// SetRequests sets the "requests" field.
func (_u *UpstreamUsageDailyUpdateOne) SetRequests(v int) *UpstreamUsageDailyUpdateOne {
	_u.mutation.ResetRequests()
	_u.mutation.SetRequests(v)
	return _u
}

// SetNillableRequests sets the "requests" field if the given value is not nil.
func (_u *UpstreamUsageDailyUpdateOne) SetNillableRequests(v *int) *UpstreamUsageDailyUpdateOne {
	if v != nil {
		_u.SetRequests(*v)
	}
	return _u
}

// AddRequests adds value to the "requests" field.
func (_u *UpstreamUsageDailyUpdateOne) AddRequests(v int) *UpstreamUsageDailyUpdateOne {
	_u.mutation.AddRequests(v)
	return _u
}

// SetTokens sets the "tokens" field.
func (_u *UpstreamUsageDailyUpdateOne) SetTokens(v int64) *UpstreamUsageDailyUpdateOne {
	_u.mutation.ResetTokens()
	_u.mutation.SetTokens(v)
	return _u
}

// SetNillableTokens sets the "tokens" field if the given value is not nil.
func (_u *UpstreamUsageDailyUpdateOne) SetNillableTokens(v *int64) *UpstreamUsageDailyUpdateOne {
	if v != nil {
		_u.SetTokens(*v)
	}
	return _u
}

// AddTokens adds value to the "tokens" field.
func (_u *UpstreamUsageDailyUpdateOne) AddTokens(v int64) *UpstreamUsageDailyUpdateOne {
	_u.mutation.AddTokens(v)
	return _u
}

// SetCostUsd sets the "cost_usd" field.
func (_u *UpstreamUsageDailyUpdateOne) SetCostUsd(v float64) *UpstreamUsageDailyUpdateOne {
	_u.mutation.ResetCostUsd()
	_u.mutation.SetCostUsd(v)
	return _u
}

// SetNillableCostUsd sets the "cost_usd" field if the given value is not nil.
func (_u *UpstreamUsageDailyUpdateOne) SetNillableCostUsd(v *float64) *UpstreamUsageDailyUpdateOne {
	if v != nil {
		_u.SetCostUsd(*v)
	}
	return _u
}

// AddCostUsd adds value to the "cost_usd" field.
func (_u *UpstreamUsageDailyUpdateOne) AddCostUsd(v float64) *UpstreamUsageDailyUpdateOne {
	_u.mutation.AddCostUsd(v)
	return _u
}

// Mutation returns the UpstreamUsageDailyMutation object of the builder.
func (_u *UpstreamUsageDailyUpdateOne) Mutation() *UpstreamUsageDailyMutation {
	return _u.mutation
}

// Where appends a list predicates to the UpstreamUsageDailyUpdate builder.
func (_u *UpstreamUsageDailyUpdateOne) Where(ps ...predicate.UpstreamUsageDaily) *UpstreamUsageDailyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UpstreamUsageDailyUpdateOne) Select(field string, fields ...string) *UpstreamUsageDailyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UpstreamUsageDaily entity.
func (_u *UpstreamUsageDailyUpdateOne) Save(ctx context.Context) (*UpstreamUsageDaily, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamUsageDailyUpdateOne) SaveX(ctx context.Context) *UpstreamUsageDaily {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UpstreamUsageDailyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamUsageDailyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UpstreamUsageDailyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := upstreamusagedaily.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamUsageDailyUpdateOne) check() error {
	if v, ok := _u.mutation.ScopeType(); ok {
		if err := upstreamusagedaily.ScopeTypeValidator(v); err != nil {
			return &ValidationError{Name: "scope_type", err: fmt.Errorf(`ent: validator failed for field "UpstreamUsageDaily.scope_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScopeKey(); ok {
		if err := upstreamusagedaily.ScopeKeyValidator(v); err != nil {
			return &ValidationError{Name: "scope_key", err: fmt.Errorf(`ent: validator failed for field "UpstreamUsageDaily.scope_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ScopeName(); ok {
		if err := upstreamusagedaily.ScopeNameValidator(v); err != nil {
			return &ValidationError{Name: "scope_name", err: fmt.Errorf(`ent: validator failed for field "UpstreamUsageDaily.scope_name": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamUsageDailyUpdateOne) sqlSave(ctx context.Context) (_node *UpstreamUsageDaily, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamusagedaily.Table, upstreamusagedaily.Columns, sqlgraph.NewFieldSpec(upstreamusagedaily.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UpstreamUsageDaily.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upstreamusagedaily.FieldID)
		for _, f := range fields {
			if !upstreamusagedaily.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upstreamusagedaily.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamusagedaily.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ProviderID(); ok {
		_spec.SetField(upstreamusagedaily.FieldProviderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProviderID(); ok {
		_spec.AddField(upstreamusagedaily.FieldProviderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Day(); ok {
		_spec.SetField(upstreamusagedaily.FieldDay, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ScopeType(); ok {
		_spec.SetField(upstreamusagedaily.FieldScopeType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScopeKey(); ok {
		_spec.SetField(upstreamusagedaily.FieldScopeKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ScopeName(); ok {
		_spec.SetField(upstreamusagedaily.FieldScopeName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Requests(); ok {
		_spec.SetField(upstreamusagedaily.FieldRequests, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRequests(); ok {
		_spec.AddField(upstreamusagedaily.FieldRequests, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Tokens(); ok {
		_spec.SetField(upstreamusagedaily.FieldTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTokens(); ok {
		_spec.AddField(upstreamusagedaily.FieldTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CostUsd(); ok {
		_spec.SetField(upstreamusagedaily.FieldCostUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostUsd(); ok {
		_spec.AddField(upstreamusagedaily.FieldCostUsd, field.TypeFloat64, value)
	}
	_node = &UpstreamUsageDaily{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamusagedaily.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
