// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/upstreamusagecursor"
)

// UpstreamUsageCursorUpdate is the builder for updating UpstreamUsageCursor entities.
type UpstreamUsageCursorUpdate struct {
	config
	hooks    []Hook
	mutation *UpstreamUsageCursorMutation
}

// Where appends a list predicates to the UpstreamUsageCursorUpdate builder.
func (_u *UpstreamUsageCursorUpdate) Where(ps ...predicate.UpstreamUsageCursor) *UpstreamUsageCursorUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UpstreamUsageCursorUpdate) SetUpdatedAt(v time.Time) *UpstreamUsageCursorUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProviderID sets the "provider_id" field.
func (_u *UpstreamUsageCursorUpdate) SetProviderID(v int64) *UpstreamUsageCursorUpdate {
	_u.mutation.ResetProviderID()
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *UpstreamUsageCursorUpdate) SetNillableProviderID(v *int64) *UpstreamUsageCursorUpdate {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// AddProviderID adds value to the "provider_id" field.
func (_u *UpstreamUsageCursorUpdate) AddProviderID(v int64) *UpstreamUsageCursorUpdate {
	_u.mutation.AddProviderID(v)
	return _u
}

// SetCollectStartedAt sets the "collect_started_at" field.
func (_u *UpstreamUsageCursorUpdate) SetCollectStartedAt(v time.Time) *UpstreamUsageCursorUpdate {
	_u.mutation.SetCollectStartedAt(v)
	return _u
}

// SetNillableCollectStartedAt sets the "collect_started_at" field if the given value is not nil.
func (_u *UpstreamUsageCursorUpdate) SetNillableCollectStartedAt(v *time.Time) *UpstreamUsageCursorUpdate {
	if v != nil {
		_u.SetCollectStartedAt(*v)
	}
	return _u
}

// ClearCollectStartedAt clears the value of the "collect_started_at" field.
func (_u *UpstreamUsageCursorUpdate) ClearCollectStartedAt() *UpstreamUsageCursorUpdate {
	_u.mutation.ClearCollectStartedAt()
	return _u
}

// SetCollectedThroughDay sets the "collected_through_day" field.
func (_u *UpstreamUsageCursorUpdate) SetCollectedThroughDay(v time.Time) *UpstreamUsageCursorUpdate {
	_u.mutation.SetCollectedThroughDay(v)
	return _u
}

// SetNillableCollectedThroughDay sets the "collected_through_day" field if the given value is not nil.
func (_u *UpstreamUsageCursorUpdate) SetNillableCollectedThroughDay(v *time.Time) *UpstreamUsageCursorUpdate {
	if v != nil {
		_u.SetCollectedThroughDay(*v)
	}
	return _u
}

// ClearCollectedThroughDay clears the value of the "collected_through_day" field.
func (_u *UpstreamUsageCursorUpdate) ClearCollectedThroughDay() *UpstreamUsageCursorUpdate {
	_u.mutation.ClearCollectedThroughDay()
	return _u
}

// SetBackfillDone sets the "backfill_done" field.
func (_u *UpstreamUsageCursorUpdate) SetBackfillDone(v bool) *UpstreamUsageCursorUpdate {
	_u.mutation.SetBackfillDone(v)
	return _u
}

// SetNillableBackfillDone sets the "backfill_done" field if the given value is not nil.
func (_u *UpstreamUsageCursorUpdate) SetNillableBackfillDone(v *bool) *UpstreamUsageCursorUpdate {
	if v != nil {
		_u.SetBackfillDone(*v)
	}
	return _u
}

// SetBackfillOldestDay sets the "backfill_oldest_day" field.
func (_u *UpstreamUsageCursorUpdate) SetBackfillOldestDay(v time.Time) *UpstreamUsageCursorUpdate {
	_u.mutation.SetBackfillOldestDay(v)
	return _u
}

// SetNillableBackfillOldestDay sets the "backfill_oldest_day" field if the given value is not nil.
func (_u *UpstreamUsageCursorUpdate) SetNillableBackfillOldestDay(v *time.Time) *UpstreamUsageCursorUpdate {
	if v != nil {
		_u.SetBackfillOldestDay(*v)
	}
	return _u
}

// ClearBackfillOldestDay clears the value of the "backfill_oldest_day" field.
func (_u *UpstreamUsageCursorUpdate) ClearBackfillOldestDay() *UpstreamUsageCursorUpdate {
	_u.mutation.ClearBackfillOldestDay()
	return _u
}

// SetLastCollectedAt sets the "last_collected_at" field.
func (_u *UpstreamUsageCursorUpdate) SetLastCollectedAt(v time.Time) *UpstreamUsageCursorUpdate {
	_u.mutation.SetLastCollectedAt(v)
	return _u
}

// SetNillableLastCollectedAt sets the "last_collected_at" field if the given value is not nil.
func (_u *UpstreamUsageCursorUpdate) SetNillableLastCollectedAt(v *time.Time) *UpstreamUsageCursorUpdate {
	if v != nil {
		_u.SetLastCollectedAt(*v)
	}
	return _u
}

// ClearLastCollectedAt clears the value of the "last_collected_at" field.
func (_u *UpstreamUsageCursorUpdate) ClearLastCollectedAt() *UpstreamUsageCursorUpdate {
	_u.mutation.ClearLastCollectedAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *UpstreamUsageCursorUpdate) SetLastError(v string) *UpstreamUsageCursorUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *UpstreamUsageCursorUpdate) SetNillableLastError(v *string) *UpstreamUsageCursorUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// SetLastPartial sets the "last_partial" field.
func (_u *UpstreamUsageCursorUpdate) SetLastPartial(v bool) *UpstreamUsageCursorUpdate {
	_u.mutation.SetLastPartial(v)
	return _u
}

// SetNillableLastPartial sets the "last_partial" field if the given value is not nil.
func (_u *UpstreamUsageCursorUpdate) SetNillableLastPartial(v *bool) *UpstreamUsageCursorUpdate {
	if v != nil {
		_u.SetLastPartial(*v)
	}
	return _u
}

// SetPartialReason sets the "partial_reason" field.
func (_u *UpstreamUsageCursorUpdate) SetPartialReason(v string) *UpstreamUsageCursorUpdate {
	_u.mutation.SetPartialReason(v)
	return _u
}

// SetNillablePartialReason sets the "partial_reason" field if the given value is not nil.
func (_u *UpstreamUsageCursorUpdate) SetNillablePartialReason(v *string) *UpstreamUsageCursorUpdate {
	if v != nil {
		_u.SetPartialReason(*v)
	}
	return _u
}

// Mutation returns the UpstreamUsageCursorMutation object of the builder.
func (_u *UpstreamUsageCursorUpdate) Mutation() *UpstreamUsageCursorMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UpstreamUsageCursorUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamUsageCursorUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UpstreamUsageCursorUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamUsageCursorUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UpstreamUsageCursorUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := upstreamusagecursor.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamUsageCursorUpdate) check() error {
	if v, ok := _u.mutation.PartialReason(); ok {
		if err := upstreamusagecursor.PartialReasonValidator(v); err != nil {
			return &ValidationError{Name: "partial_reason", err: fmt.Errorf(`ent: validator failed for field "UpstreamUsageCursor.partial_reason": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamUsageCursorUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamusagecursor.Table, upstreamusagecursor.Columns, sqlgraph.NewFieldSpec(upstreamusagecursor.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamusagecursor.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ProviderID(); ok {
		_spec.SetField(upstreamusagecursor.FieldProviderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProviderID(); ok {
		_spec.AddField(upstreamusagecursor.FieldProviderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CollectStartedAt(); ok {
		_spec.SetField(upstreamusagecursor.FieldCollectStartedAt, field.TypeTime, value)
	}
	if _u.mutation.CollectStartedAtCleared() {
		_spec.ClearField(upstreamusagecursor.FieldCollectStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CollectedThroughDay(); ok {
		_spec.SetField(upstreamusagecursor.FieldCollectedThroughDay, field.TypeTime, value)
	}
	if _u.mutation.CollectedThroughDayCleared() {
		_spec.ClearField(upstreamusagecursor.FieldCollectedThroughDay, field.TypeTime)
	}
	if value, ok := _u.mutation.BackfillDone(); ok {
		_spec.SetField(upstreamusagecursor.FieldBackfillDone, field.TypeBool, value)
	}
	if value, ok := _u.mutation.BackfillOldestDay(); ok {
		_spec.SetField(upstreamusagecursor.FieldBackfillOldestDay, field.TypeTime, value)
	}
	if _u.mutation.BackfillOldestDayCleared() {
		_spec.ClearField(upstreamusagecursor.FieldBackfillOldestDay, field.TypeTime)
	}
	if value, ok := _u.mutation.LastCollectedAt(); ok {
		_spec.SetField(upstreamusagecursor.FieldLastCollectedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCollectedAtCleared() {
		_spec.ClearField(upstreamusagecursor.FieldLastCollectedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(upstreamusagecursor.FieldLastError, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastPartial(); ok {
		_spec.SetField(upstreamusagecursor.FieldLastPartial, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PartialReason(); ok {
		_spec.SetField(upstreamusagecursor.FieldPartialReason, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamusagecursor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UpstreamUsageCursorUpdateOne is the builder for updating a single UpstreamUsageCursor entity.
type UpstreamUsageCursorUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UpstreamUsageCursorMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UpstreamUsageCursorUpdateOne) SetUpdatedAt(v time.Time) *UpstreamUsageCursorUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProviderID sets the "provider_id" field.
func (_u *UpstreamUsageCursorUpdateOne) SetProviderID(v int64) *UpstreamUsageCursorUpdateOne {
	_u.mutation.ResetProviderID()
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *UpstreamUsageCursorUpdateOne) SetNillableProviderID(v *int64) *UpstreamUsageCursorUpdateOne {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// AddProviderID adds value to the "provider_id" field.
func (_u *UpstreamUsageCursorUpdateOne) AddProviderID(v int64) *UpstreamUsageCursorUpdateOne {
	_u.mutation.AddProviderID(v)
	return _u
}

// SetCollectStartedAt sets the "collect_started_at" field.
func (_u *UpstreamUsageCursorUpdateOne) SetCollectStartedAt(v time.Time) *UpstreamUsageCursorUpdateOne {
	_u.mutation.SetCollectStartedAt(v)
	return _u
}

// SetNillableCollectStartedAt sets the "collect_started_at" field if the given value is not nil.
func (_u *UpstreamUsageCursorUpdateOne) SetNillableCollectStartedAt(v *time.Time) *UpstreamUsageCursorUpdateOne {
	if v != nil {
		_u.SetCollectStartedAt(*v)
	}
	return _u
}

// ClearCollectStartedAt clears the value of the "collect_started_at" field.
func (_u *UpstreamUsageCursorUpdateOne) ClearCollectStartedAt() *UpstreamUsageCursorUpdateOne {
	_u.mutation.ClearCollectStartedAt()
	return _u
}

// SetCollectedThroughDay sets the "collected_through_day" field.
func (_u *UpstreamUsageCursorUpdateOne) SetCollectedThroughDay(v time.Time) *UpstreamUsageCursorUpdateOne {
	_u.mutation.SetCollectedThroughDay(v)
	return _u
}

// SetNillableCollectedThroughDay sets the "collected_through_day" field if the given value is not nil.
func (_u *UpstreamUsageCursorUpdateOne) SetNillableCollectedThroughDay(v *time.Time) *UpstreamUsageCursorUpdateOne {
	if v != nil {
		_u.SetCollectedThroughDay(*v)
	}
	return _u
}

// ClearCollectedThroughDay clears the value of the "collected_through_day" field.
func (_u *UpstreamUsageCursorUpdateOne) ClearCollectedThroughDay() *UpstreamUsageCursorUpdateOne {
	_u.mutation.ClearCollectedThroughDay()
	return _u
}

// SetBackfillDone sets the "backfill_done" field.
func (_u *UpstreamUsageCursorUpdateOne) SetBackfillDone(v bool) *UpstreamUsageCursorUpdateOne {
	_u.mutation.SetBackfillDone(v)
	return _u
}

// SetNillableBackfillDone sets the "backfill_done" field if the given value is not nil.
func (_u *UpstreamUsageCursorUpdateOne) SetNillableBackfillDone(v *bool) *UpstreamUsageCursorUpdateOne {
	if v != nil {
		_u.SetBackfillDone(*v)
	}
	return _u
}

// SetBackfillOldestDay sets the "backfill_oldest_day" field.
func (_u *UpstreamUsageCursorUpdateOne) SetBackfillOldestDay(v time.Time) *UpstreamUsageCursorUpdateOne {
	_u.mutation.SetBackfillOldestDay(v)
	return _u
}

// SetNillableBackfillOldestDay sets the "backfill_oldest_day" field if the given value is not nil.
func (_u *UpstreamUsageCursorUpdateOne) SetNillableBackfillOldestDay(v *time.Time) *UpstreamUsageCursorUpdateOne {
	if v != nil {
		_u.SetBackfillOldestDay(*v)
	}
	return _u
}

// ClearBackfillOldestDay clears the value of the "backfill_oldest_day" field.
func (_u *UpstreamUsageCursorUpdateOne) ClearBackfillOldestDay() *UpstreamUsageCursorUpdateOne {
	_u.mutation.ClearBackfillOldestDay()
	return _u
}

// SetLastCollectedAt sets the "last_collected_at" field.
func (_u *UpstreamUsageCursorUpdateOne) SetLastCollectedAt(v time.Time) *UpstreamUsageCursorUpdateOne {
	_u.mutation.SetLastCollectedAt(v)
	return _u
}

// SetNillableLastCollectedAt sets the "last_collected_at" field if the given value is not nil.
func (_u *UpstreamUsageCursorUpdateOne) SetNillableLastCollectedAt(v *time.Time) *UpstreamUsageCursorUpdateOne {
	if v != nil {
		_u.SetLastCollectedAt(*v)
	}
	return _u
}

// ClearLastCollectedAt clears the value of the "last_collected_at" field.
func (_u *UpstreamUsageCursorUpdateOne) ClearLastCollectedAt() *UpstreamUsageCursorUpdateOne {
	_u.mutation.ClearLastCollectedAt()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *UpstreamUsageCursorUpdateOne) SetLastError(v string) *UpstreamUsageCursorUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *UpstreamUsageCursorUpdateOne) SetNillableLastError(v *string) *UpstreamUsageCursorUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// SetLastPartial sets the "last_partial" field.
func (_u *UpstreamUsageCursorUpdateOne) SetLastPartial(v bool) *UpstreamUsageCursorUpdateOne {
	_u.mutation.SetLastPartial(v)
	return _u
}

// SetNillableLastPartial sets the "last_partial" field if the given value is not nil.
func (_u *UpstreamUsageCursorUpdateOne) SetNillableLastPartial(v *bool) *UpstreamUsageCursorUpdateOne {
	if v != nil {
		_u.SetLastPartial(*v)
	}
	return _u
}

// SetPartialReason sets the "partial_reason" field.
func (_u *UpstreamUsageCursorUpdateOne) SetPartialReason(v string) *UpstreamUsageCursorUpdateOne {
	_u.mutation.SetPartialReason(v)
	return _u
}

// SetNillablePartialReason sets the "partial_reason" field if the given value is not nil.
func (_u *UpstreamUsageCursorUpdateOne) SetNillablePartialReason(v *string) *UpstreamUsageCursorUpdateOne {
	if v != nil {
		_u.SetPartialReason(*v)
	}
	return _u
}

// Mutation returns the UpstreamUsageCursorMutation object of the builder.
func (_u *UpstreamUsageCursorUpdateOne) Mutation() *UpstreamUsageCursorMutation {
	return _u.mutation
}

// Where appends a list predicates to the UpstreamUsageCursorUpdate builder.
func (_u *UpstreamUsageCursorUpdateOne) Where(ps ...predicate.UpstreamUsageCursor) *UpstreamUsageCursorUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UpstreamUsageCursorUpdateOne) Select(field string, fields ...string) *UpstreamUsageCursorUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UpstreamUsageCursor entity.
func (_u *UpstreamUsageCursorUpdateOne) Save(ctx context.Context) (*UpstreamUsageCursor, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamUsageCursorUpdateOne) SaveX(ctx context.Context) *UpstreamUsageCursor {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UpstreamUsageCursorUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamUsageCursorUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UpstreamUsageCursorUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := upstreamusagecursor.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamUsageCursorUpdateOne) check() error {
	if v, ok := _u.mutation.PartialReason(); ok {
		if err := upstreamusagecursor.PartialReasonValidator(v); err != nil {
			return &ValidationError{Name: "partial_reason", err: fmt.Errorf(`ent: validator failed for field "UpstreamUsageCursor.partial_reason": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamUsageCursorUpdateOne) sqlSave(ctx context.Context) (_node *UpstreamUsageCursor, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamusagecursor.Table, upstreamusagecursor.Columns, sqlgraph.NewFieldSpec(upstreamusagecursor.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UpstreamUsageCursor.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upstreamusagecursor.FieldID)
		for _, f := range fields {
			if !upstreamusagecursor.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upstreamusagecursor.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamusagecursor.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ProviderID(); ok {
		_spec.SetField(upstreamusagecursor.FieldProviderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProviderID(); ok {
		_spec.AddField(upstreamusagecursor.FieldProviderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CollectStartedAt(); ok {
		_spec.SetField(upstreamusagecursor.FieldCollectStartedAt, field.TypeTime, value)
	}
	if _u.mutation.CollectStartedAtCleared() {
		_spec.ClearField(upstreamusagecursor.FieldCollectStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CollectedThroughDay(); ok {
		_spec.SetField(upstreamusagecursor.FieldCollectedThroughDay, field.TypeTime, value)
	}
	if _u.mutation.CollectedThroughDayCleared() {
		_spec.ClearField(upstreamusagecursor.FieldCollectedThroughDay, field.TypeTime)
	}
	if value, ok := _u.mutation.BackfillDone(); ok {
		_spec.SetField(upstreamusagecursor.FieldBackfillDone, field.TypeBool, value)
	}
	if value, ok := _u.mutation.BackfillOldestDay(); ok {
		_spec.SetField(upstreamusagecursor.FieldBackfillOldestDay, field.TypeTime, value)
	}
	if _u.mutation.BackfillOldestDayCleared() {
		_spec.ClearField(upstreamusagecursor.FieldBackfillOldestDay, field.TypeTime)
	}
	if value, ok := _u.mutation.LastCollectedAt(); ok {
		_spec.SetField(upstreamusagecursor.FieldLastCollectedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCollectedAtCleared() {
		_spec.ClearField(upstreamusagecursor.FieldLastCollectedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(upstreamusagecursor.FieldLastError, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastPartial(); ok {
		_spec.SetField(upstreamusagecursor.FieldLastPartial, field.TypeBool, value)
	}
	if value, ok := _u.mutation.PartialReason(); ok {
		_spec.SetField(upstreamusagecursor.FieldPartialReason, field.TypeString, value)
	}
	_node = &UpstreamUsageCursor{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamusagecursor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
