// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/upstreamchangeevent"
)

// UpstreamChangeEventCreate is the builder for creating a UpstreamChangeEvent entity.
type UpstreamChangeEventCreate struct {
	config
	mutation *UpstreamChangeEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UpstreamChangeEventCreate) SetCreatedAt(v time.Time) *UpstreamChangeEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UpstreamChangeEventCreate) SetNillableCreatedAt(v *time.Time) *UpstreamChangeEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UpstreamChangeEventCreate) SetUpdatedAt(v time.Time) *UpstreamChangeEventCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UpstreamChangeEventCreate) SetNillableUpdatedAt(v *time.Time) *UpstreamChangeEventCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetProviderID sets the "provider_id" field.
func (_c *UpstreamChangeEventCreate) SetProviderID(v int64) *UpstreamChangeEventCreate {
	_c.mutation.SetProviderID(v)
	return _c
}

// SetType sets the "type" field.
func (_c *UpstreamChangeEventCreate) SetType(v string) *UpstreamChangeEventCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetSummary sets the "summary" field.
func (_c *UpstreamChangeEventCreate) SetSummary(v string) *UpstreamChangeEventCreate {
	_c.mutation.SetSummary(v)
	return _c
}

// SetDetail sets the "detail" field.
func (_c *UpstreamChangeEventCreate) SetDetail(v map[string]interface{}) *UpstreamChangeEventCreate {
	_c.mutation.SetDetail(v)
	return _c
}

// SetNotified sets the "notified" field.
func (_c *UpstreamChangeEventCreate) SetNotified(v bool) *UpstreamChangeEventCreate {
	_c.mutation.SetNotified(v)
	return _c
}

// SetNillableNotified sets the "notified" field if the given value is not nil.
func (_c *UpstreamChangeEventCreate) SetNillableNotified(v *bool) *UpstreamChangeEventCreate {
	if v != nil {
		_c.SetNotified(*v)
	}
	return _c
}

// Mutation returns the UpstreamChangeEventMutation object of the builder.
func (_c *UpstreamChangeEventCreate) Mutation() *UpstreamChangeEventMutation {
	return _c.mutation
}

// Save creates the UpstreamChangeEvent in the database.
func (_c *UpstreamChangeEventCreate) Save(ctx context.Context) (*UpstreamChangeEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UpstreamChangeEventCreate) SaveX(ctx context.Context) *UpstreamChangeEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamChangeEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamChangeEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UpstreamChangeEventCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := upstreamchangeevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := upstreamchangeevent.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Notified(); !ok {
		v := upstreamchangeevent.DefaultNotified
		_c.mutation.SetNotified(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UpstreamChangeEventCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UpstreamChangeEvent.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UpstreamChangeEvent.updated_at"`)}
	}
	if _, ok := _c.mutation.ProviderID(); !ok {
		return &ValidationError{Name: "provider_id", err: errors.New(`ent: missing required field "UpstreamChangeEvent.provider_id"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "UpstreamChangeEvent.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := upstreamchangeevent.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "UpstreamChangeEvent.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Summary(); !ok {
		return &ValidationError{Name: "summary", err: errors.New(`ent: missing required field "UpstreamChangeEvent.summary"`)}
	}
	if _, ok := _c.mutation.Notified(); !ok {
		return &ValidationError{Name: "notified", err: errors.New(`ent: missing required field "UpstreamChangeEvent.notified"`)}
	}
	return nil
}

func (_c *UpstreamChangeEventCreate) sqlSave(ctx context.Context) (*UpstreamChangeEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UpstreamChangeEventCreate) createSpec() (*UpstreamChangeEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &UpstreamChangeEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(upstreamchangeevent.Table, sqlgraph.NewFieldSpec(upstreamchangeevent.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(upstreamchangeevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamchangeevent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ProviderID(); ok {
		_spec.SetField(upstreamchangeevent.FieldProviderID, field.TypeInt64, value)
		_node.ProviderID = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(upstreamchangeevent.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Summary(); ok {
		_spec.SetField(upstreamchangeevent.FieldSummary, field.TypeString, value)
		_node.Summary = value
	}
	if value, ok := _c.mutation.Detail(); ok {
		_spec.SetField(upstreamchangeevent.FieldDetail, field.TypeJSON, value)
		_node.Detail = value
	}
	if value, ok := _c.mutation.Notified(); ok {
		_spec.SetField(upstreamchangeevent.FieldNotified, field.TypeBool, value)
		_node.Notified = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamChangeEvent.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamChangeEventUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamChangeEventCreate) OnConflict(opts ...sql.ConflictOption) *UpstreamChangeEventUpsertOne {
	_c.conflict = opts
	return &UpstreamChangeEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamChangeEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamChangeEventCreate) OnConflictColumns(columns ...string) *UpstreamChangeEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamChangeEventUpsertOne{
		create: _c,
	}
}

type (
	// UpstreamChangeEventUpsertOne is the builder for "upsert"-ing
	//  one UpstreamChangeEvent node.
	UpstreamChangeEventUpsertOne struct {
		create *UpstreamChangeEventCreate
	}

	// UpstreamChangeEventUpsert is the "OnConflict" setter.
	UpstreamChangeEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamChangeEventUpsert) SetUpdatedAt(v time.Time) *UpstreamChangeEventUpsert {
	u.Set(upstreamchangeevent.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamChangeEventUpsert) UpdateUpdatedAt() *UpstreamChangeEventUpsert {
	u.SetExcluded(upstreamchangeevent.FieldUpdatedAt)
	return u
}

// SetProviderID sets the "provider_id" field.
func (u *UpstreamChangeEventUpsert) SetProviderID(v int64) *UpstreamChangeEventUpsert {
	u.Set(upstreamchangeevent.FieldProviderID, v)
	return u
}

// UpdateProviderID sets the "provider_id" field to the value that was provided on create.
func (u *UpstreamChangeEventUpsert) UpdateProviderID() *UpstreamChangeEventUpsert {
	u.SetExcluded(upstreamchangeevent.FieldProviderID)
	return u
}

// AddProviderID adds v to the "provider_id" field.
func (u *UpstreamChangeEventUpsert) AddProviderID(v int64) *UpstreamChangeEventUpsert {
	u.Add(upstreamchangeevent.FieldProviderID, v)
	return u
}

// SetType sets the "type" field.
func (u *UpstreamChangeEventUpsert) SetType(v string) *UpstreamChangeEventUpsert {
	u.Set(upstreamchangeevent.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *UpstreamChangeEventUpsert) UpdateType() *UpstreamChangeEventUpsert {
	u.SetExcluded(upstreamchangeevent.FieldType)
	return u
}

// SetSummary sets the "summary" field.
func (u *UpstreamChangeEventUpsert) SetSummary(v string) *UpstreamChangeEventUpsert {
	u.Set(upstreamchangeevent.FieldSummary, v)
	return u
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *UpstreamChangeEventUpsert) UpdateSummary() *UpstreamChangeEventUpsert {
	u.SetExcluded(upstreamchangeevent.FieldSummary)
	return u
}

// SetDetail sets the "detail" field.
func (u *UpstreamChangeEventUpsert) SetDetail(v map[string]interface{}) *UpstreamChangeEventUpsert {
	u.Set(upstreamchangeevent.FieldDetail, v)
	return u
}

// UpdateDetail sets the "detail" field to the value that was provided on create.
func (u *UpstreamChangeEventUpsert) UpdateDetail() *UpstreamChangeEventUpsert {
	u.SetExcluded(upstreamchangeevent.FieldDetail)
	return u
}

// ClearDetail clears the value of the "detail" field.
func (u *UpstreamChangeEventUpsert) ClearDetail() *UpstreamChangeEventUpsert {
	u.SetNull(upstreamchangeevent.FieldDetail)
	return u
}

// SetNotified sets the "notified" field.
func (u *UpstreamChangeEventUpsert) SetNotified(v bool) *UpstreamChangeEventUpsert {
	u.Set(upstreamchangeevent.FieldNotified, v)
	return u
}

// UpdateNotified sets the "notified" field to the value that was provided on create.
func (u *UpstreamChangeEventUpsert) UpdateNotified() *UpstreamChangeEventUpsert {
	u.SetExcluded(upstreamchangeevent.FieldNotified)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UpstreamChangeEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamChangeEventUpsertOne) UpdateNewValues() *UpstreamChangeEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(upstreamchangeevent.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamChangeEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UpstreamChangeEventUpsertOne) Ignore() *UpstreamChangeEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamChangeEventUpsertOne) DoNothing() *UpstreamChangeEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamChangeEventCreate.OnConflict
// documentation for more info.
func (u *UpstreamChangeEventUpsertOne) Update(set func(*UpstreamChangeEventUpsert)) *UpstreamChangeEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamChangeEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamChangeEventUpsertOne) SetUpdatedAt(v time.Time) *UpstreamChangeEventUpsertOne {
	return u.Update(func(s *UpstreamChangeEventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamChangeEventUpsertOne) UpdateUpdatedAt() *UpstreamChangeEventUpsertOne {
	return u.Update(func(s *UpstreamChangeEventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetProviderID sets the "provider_id" field.
func (u *UpstreamChangeEventUpsertOne) SetProviderID(v int64) *UpstreamChangeEventUpsertOne {
	return u.Update(func(s *UpstreamChangeEventUpsert) {
		s.SetProviderID(v)
	})
}

// AddProviderID adds v to the "provider_id" field.
func (u *UpstreamChangeEventUpsertOne) AddProviderID(v int64) *UpstreamChangeEventUpsertOne {
	return u.Update(func(s *UpstreamChangeEventUpsert) {
		s.AddProviderID(v)
	})
}

// UpdateProviderID sets the "provider_id" field to the value that was provided on create.
func (u *UpstreamChangeEventUpsertOne) UpdateProviderID() *UpstreamChangeEventUpsertOne {
	return u.Update(func(s *UpstreamChangeEventUpsert) {
		s.UpdateProviderID()
	})
}

// SetType sets the "type" field.
func (u *UpstreamChangeEventUpsertOne) SetType(v string) *UpstreamChangeEventUpsertOne {
	return u.Update(func(s *UpstreamChangeEventUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *UpstreamChangeEventUpsertOne) UpdateType() *UpstreamChangeEventUpsertOne {
	return u.Update(func(s *UpstreamChangeEventUpsert) {
		s.UpdateType()
	})
}

// SetSummary sets the "summary" field.
func (u *UpstreamChangeEventUpsertOne) SetSummary(v string) *UpstreamChangeEventUpsertOne {
	return u.Update(func(s *UpstreamChangeEventUpsert) {
		s.SetSummary(v)
	})
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *UpstreamChangeEventUpsertOne) UpdateSummary() *UpstreamChangeEventUpsertOne {
	return u.Update(func(s *UpstreamChangeEventUpsert) {
		s.UpdateSummary()
	})
}

// SetDetail sets the "detail" field.
func (u *UpstreamChangeEventUpsertOne) SetDetail(v map[string]interface{}) *UpstreamChangeEventUpsertOne {
	return u.Update(func(s *UpstreamChangeEventUpsert) {
		s.SetDetail(v)
	})
}

// UpdateDetail sets the "detail" field to the value that was provided on create.
func (u *UpstreamChangeEventUpsertOne) UpdateDetail() *UpstreamChangeEventUpsertOne {
	return u.Update(func(s *UpstreamChangeEventUpsert) {
		s.UpdateDetail()
	})
}

// ClearDetail clears the value of the "detail" field.
func (u *UpstreamChangeEventUpsertOne) ClearDetail() *UpstreamChangeEventUpsertOne {
	return u.Update(func(s *UpstreamChangeEventUpsert) {
		s.ClearDetail()
	})
}

// SetNotified sets the "notified" field.
func (u *UpstreamChangeEventUpsertOne) SetNotified(v bool) *UpstreamChangeEventUpsertOne {
	return u.Update(func(s *UpstreamChangeEventUpsert) {
		s.SetNotified(v)
	})
}

// UpdateNotified sets the "notified" field to the value that was provided on create.
func (u *UpstreamChangeEventUpsertOne) UpdateNotified() *UpstreamChangeEventUpsertOne {
	return u.Update(func(s *UpstreamChangeEventUpsert) {
		s.UpdateNotified()
	})
}

// Exec executes the query.
func (u *UpstreamChangeEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamChangeEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamChangeEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UpstreamChangeEventUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UpstreamChangeEventUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UpstreamChangeEventCreateBulk is the builder for creating many UpstreamChangeEvent entities in bulk.
type UpstreamChangeEventCreateBulk struct {
	config
	err      error
	builders []*UpstreamChangeEventCreate
	conflict []sql.ConflictOption
}

// Save creates the UpstreamChangeEvent entities in the database.
func (_c *UpstreamChangeEventCreateBulk) Save(ctx context.Context) ([]*UpstreamChangeEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UpstreamChangeEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpstreamChangeEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UpstreamChangeEventCreateBulk) SaveX(ctx context.Context) []*UpstreamChangeEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamChangeEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamChangeEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamChangeEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamChangeEventUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamChangeEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *UpstreamChangeEventUpsertBulk {
	_c.conflict = opts
	return &UpstreamChangeEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamChangeEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamChangeEventCreateBulk) OnConflictColumns(columns ...string) *UpstreamChangeEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamChangeEventUpsertBulk{
		create: _c,
	}
}

// UpstreamChangeEventUpsertBulk is the builder for "upsert"-ing
// a bulk of UpstreamChangeEvent nodes.
type UpstreamChangeEventUpsertBulk struct {
	create *UpstreamChangeEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UpstreamChangeEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamChangeEventUpsertBulk) UpdateNewValues() *UpstreamChangeEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(upstreamchangeevent.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamChangeEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UpstreamChangeEventUpsertBulk) Ignore() *UpstreamChangeEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamChangeEventUpsertBulk) DoNothing() *UpstreamChangeEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamChangeEventCreateBulk.OnConflict
// documentation for more info.
func (u *UpstreamChangeEventUpsertBulk) Update(set func(*UpstreamChangeEventUpsert)) *UpstreamChangeEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamChangeEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamChangeEventUpsertBulk) SetUpdatedAt(v time.Time) *UpstreamChangeEventUpsertBulk {
	return u.Update(func(s *UpstreamChangeEventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamChangeEventUpsertBulk) UpdateUpdatedAt() *UpstreamChangeEventUpsertBulk {
	return u.Update(func(s *UpstreamChangeEventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetProviderID sets the "provider_id" field.
func (u *UpstreamChangeEventUpsertBulk) SetProviderID(v int64) *UpstreamChangeEventUpsertBulk {
	return u.Update(func(s *UpstreamChangeEventUpsert) {
		s.SetProviderID(v)
	})
}

// AddProviderID adds v to the "provider_id" field.
func (u *UpstreamChangeEventUpsertBulk) AddProviderID(v int64) *UpstreamChangeEventUpsertBulk {
	return u.Update(func(s *UpstreamChangeEventUpsert) {
		s.AddProviderID(v)
	})
}

// UpdateProviderID sets the "provider_id" field to the value that was provided on create.
func (u *UpstreamChangeEventUpsertBulk) UpdateProviderID() *UpstreamChangeEventUpsertBulk {
	return u.Update(func(s *UpstreamChangeEventUpsert) {
		s.UpdateProviderID()
	})
}

// SetType sets the "type" field.
func (u *UpstreamChangeEventUpsertBulk) SetType(v string) *UpstreamChangeEventUpsertBulk {
	return u.Update(func(s *UpstreamChangeEventUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *UpstreamChangeEventUpsertBulk) UpdateType() *UpstreamChangeEventUpsertBulk {
	return u.Update(func(s *UpstreamChangeEventUpsert) {
		s.UpdateType()
	})
}

// SetSummary sets the "summary" field.
func (u *UpstreamChangeEventUpsertBulk) SetSummary(v string) *UpstreamChangeEventUpsertBulk {
	return u.Update(func(s *UpstreamChangeEventUpsert) {
		s.SetSummary(v)
	})
}

// UpdateSummary sets the "summary" field to the value that was provided on create.
func (u *UpstreamChangeEventUpsertBulk) UpdateSummary() *UpstreamChangeEventUpsertBulk {
	return u.Update(func(s *UpstreamChangeEventUpsert) {
		s.UpdateSummary()
	})
}

// SetDetail sets the "detail" field.
func (u *UpstreamChangeEventUpsertBulk) SetDetail(v map[string]interface{}) *UpstreamChangeEventUpsertBulk {
	return u.Update(func(s *UpstreamChangeEventUpsert) {
		s.SetDetail(v)
	})
}

// UpdateDetail sets the "detail" field to the value that was provided on create.
func (u *UpstreamChangeEventUpsertBulk) UpdateDetail() *UpstreamChangeEventUpsertBulk {
	return u.Update(func(s *UpstreamChangeEventUpsert) {
		s.UpdateDetail()
	})
}

// ClearDetail clears the value of the "detail" field.
func (u *UpstreamChangeEventUpsertBulk) ClearDetail() *UpstreamChangeEventUpsertBulk {
	return u.Update(func(s *UpstreamChangeEventUpsert) {
		s.ClearDetail()
	})
}

// SetNotified sets the "notified" field.
func (u *UpstreamChangeEventUpsertBulk) SetNotified(v bool) *UpstreamChangeEventUpsertBulk {
	return u.Update(func(s *UpstreamChangeEventUpsert) {
		s.SetNotified(v)
	})
}

// UpdateNotified sets the "notified" field to the value that was provided on create.
func (u *UpstreamChangeEventUpsertBulk) UpdateNotified() *UpstreamChangeEventUpsertBulk {
	return u.Update(func(s *UpstreamChangeEventUpsert) {
		s.UpdateNotified()
	})
}

// Exec executes the query.
func (u *UpstreamChangeEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UpstreamChangeEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamChangeEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamChangeEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
