// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/upstreamchangeevent"
)

// UpstreamChangeEvent is the model entity for the UpstreamChangeEvent schema.
type UpstreamChangeEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ProviderID holds the value of the "provider_id" field.
	ProviderID int64 `json:"provider_id,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// Summary holds the value of the "summary" field.
	Summary string `json:"summary,omitempty"`
	// Detail holds the value of the "detail" field.
	Detail map[string]interface{} `json:"detail,omitempty"`
	// Notified holds the value of the "notified" field.
	Notified     bool `json:"notified,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UpstreamChangeEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upstreamchangeevent.FieldDetail:
			values[i] = new([]byte)
		case upstreamchangeevent.FieldNotified:
			values[i] = new(sql.NullBool)
		case upstreamchangeevent.FieldID, upstreamchangeevent.FieldProviderID:
			values[i] = new(sql.NullInt64)
		case upstreamchangeevent.FieldType, upstreamchangeevent.FieldSummary:
			values[i] = new(sql.NullString)
		case upstreamchangeevent.FieldCreatedAt, upstreamchangeevent.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UpstreamChangeEvent fields.
func (_m *UpstreamChangeEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upstreamchangeevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case upstreamchangeevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case upstreamchangeevent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case upstreamchangeevent.FieldProviderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field provider_id", values[i])
			} else if value.Valid {
				_m.ProviderID = value.Int64
			}
		case upstreamchangeevent.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case upstreamchangeevent.FieldSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value.Valid {
				_m.Summary = value.String
			}
		case upstreamchangeevent.FieldDetail:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field detail", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Detail); err != nil {
					return fmt.Errorf("unmarshal field detail: %w", err)
				}
			}
		case upstreamchangeevent.FieldNotified:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field notified", values[i])
			} else if value.Valid {
				_m.Notified = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UpstreamChangeEvent.
// This includes values selected through modifiers, order, etc.
func (_m *UpstreamChangeEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UpstreamChangeEvent.
// Note that you need to call UpstreamChangeEvent.Unwrap() before calling this method if this UpstreamChangeEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UpstreamChangeEvent) Update() *UpstreamChangeEventUpdateOne {
	return NewUpstreamChangeEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UpstreamChangeEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UpstreamChangeEvent) Unwrap() *UpstreamChangeEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UpstreamChangeEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UpstreamChangeEvent) String() string {
	var builder strings.Builder
	builder.WriteString("UpstreamChangeEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("provider_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderID))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("summary=")
	builder.WriteString(_m.Summary)
	builder.WriteString(", ")
	builder.WriteString("detail=")
	builder.WriteString(fmt.Sprintf("%v", _m.Detail))
	builder.WriteString(", ")
	builder.WriteString("notified=")
	builder.WriteString(fmt.Sprintf("%v", _m.Notified))
	builder.WriteByte(')')
	return builder.String()
}

// UpstreamChangeEvents is a parsable slice of UpstreamChangeEvent.
type UpstreamChangeEvents []*UpstreamChangeEvent
