// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/upstreamusagecursor"
)

// UpstreamUsageCursor is the model entity for the UpstreamUsageCursor schema.
type UpstreamUsageCursor struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ProviderID holds the value of the "provider_id" field.
	ProviderID int64 `json:"provider_id,omitempty"`
	// CollectStartedAt holds the value of the "collect_started_at" field.
	CollectStartedAt *time.Time `json:"collect_started_at,omitempty"`
	// CollectedThroughDay holds the value of the "collected_through_day" field.
	CollectedThroughDay *time.Time `json:"collected_through_day,omitempty"`
	// BackfillDone holds the value of the "backfill_done" field.
	BackfillDone bool `json:"backfill_done,omitempty"`
	// BackfillOldestDay holds the value of the "backfill_oldest_day" field.
	BackfillOldestDay *time.Time `json:"backfill_oldest_day,omitempty"`
	// LastCollectedAt holds the value of the "last_collected_at" field.
	LastCollectedAt *time.Time `json:"last_collected_at,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError string `json:"last_error,omitempty"`
	// LastPartial holds the value of the "last_partial" field.
	LastPartial bool `json:"last_partial,omitempty"`
	// PartialReason holds the value of the "partial_reason" field.
	PartialReason string `json:"partial_reason,omitempty"`
	selectValues  sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UpstreamUsageCursor) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upstreamusagecursor.FieldBackfillDone, upstreamusagecursor.FieldLastPartial:
			values[i] = new(sql.NullBool)
		case upstreamusagecursor.FieldID, upstreamusagecursor.FieldProviderID:
			values[i] = new(sql.NullInt64)
		case upstreamusagecursor.FieldLastError, upstreamusagecursor.FieldPartialReason:
			values[i] = new(sql.NullString)
		case upstreamusagecursor.FieldCreatedAt, upstreamusagecursor.FieldUpdatedAt, upstreamusagecursor.FieldCollectStartedAt, upstreamusagecursor.FieldCollectedThroughDay, upstreamusagecursor.FieldBackfillOldestDay, upstreamusagecursor.FieldLastCollectedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UpstreamUsageCursor fields.
func (_m *UpstreamUsageCursor) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upstreamusagecursor.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case upstreamusagecursor.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case upstreamusagecursor.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case upstreamusagecursor.FieldProviderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field provider_id", values[i])
			} else if value.Valid {
				_m.ProviderID = value.Int64
			}
		case upstreamusagecursor.FieldCollectStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field collect_started_at", values[i])
			} else if value.Valid {
				_m.CollectStartedAt = new(time.Time)
				*_m.CollectStartedAt = value.Time
			}
		case upstreamusagecursor.FieldCollectedThroughDay:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field collected_through_day", values[i])
			} else if value.Valid {
				_m.CollectedThroughDay = new(time.Time)
				*_m.CollectedThroughDay = value.Time
			}
		case upstreamusagecursor.FieldBackfillDone:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field backfill_done", values[i])
			} else if value.Valid {
				_m.BackfillDone = value.Bool
			}
		case upstreamusagecursor.FieldBackfillOldestDay:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field backfill_oldest_day", values[i])
			} else if value.Valid {
				_m.BackfillOldestDay = new(time.Time)
				*_m.BackfillOldestDay = value.Time
			}
		case upstreamusagecursor.FieldLastCollectedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_collected_at", values[i])
			} else if value.Valid {
				_m.LastCollectedAt = new(time.Time)
				*_m.LastCollectedAt = value.Time
			}
		case upstreamusagecursor.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = value.String
			}
		case upstreamusagecursor.FieldLastPartial:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field last_partial", values[i])
			} else if value.Valid {
				_m.LastPartial = value.Bool
			}
		case upstreamusagecursor.FieldPartialReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field partial_reason", values[i])
			} else if value.Valid {
				_m.PartialReason = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UpstreamUsageCursor.
// This includes values selected through modifiers, order, etc.
func (_m *UpstreamUsageCursor) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UpstreamUsageCursor.
// Note that you need to call UpstreamUsageCursor.Unwrap() before calling this method if this UpstreamUsageCursor
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UpstreamUsageCursor) Update() *UpstreamUsageCursorUpdateOne {
	return NewUpstreamUsageCursorClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UpstreamUsageCursor entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UpstreamUsageCursor) Unwrap() *UpstreamUsageCursor {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UpstreamUsageCursor is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UpstreamUsageCursor) String() string {
	var builder strings.Builder
	builder.WriteString("UpstreamUsageCursor(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("provider_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderID))
	builder.WriteString(", ")
	if v := _m.CollectStartedAt; v != nil {
		builder.WriteString("collect_started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CollectedThroughDay; v != nil {
		builder.WriteString("collected_through_day=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("backfill_done=")
	builder.WriteString(fmt.Sprintf("%v", _m.BackfillDone))
	builder.WriteString(", ")
	if v := _m.BackfillOldestDay; v != nil {
		builder.WriteString("backfill_oldest_day=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastCollectedAt; v != nil {
		builder.WriteString("last_collected_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("last_error=")
	builder.WriteString(_m.LastError)
	builder.WriteString(", ")
	builder.WriteString("last_partial=")
	builder.WriteString(fmt.Sprintf("%v", _m.LastPartial))
	builder.WriteString(", ")
	builder.WriteString("partial_reason=")
	builder.WriteString(_m.PartialReason)
	builder.WriteByte(')')
	return builder.String()
}

// UpstreamUsageCursors is a parsable slice of UpstreamUsageCursor.
type UpstreamUsageCursors []*UpstreamUsageCursor
