// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/upstreamchangeevent"
)

// UpstreamChangeEventUpdate is the builder for updating UpstreamChangeEvent entities.
type UpstreamChangeEventUpdate struct {
	config
	hooks    []Hook
	mutation *UpstreamChangeEventMutation
}

// Where appends a list predicates to the UpstreamChangeEventUpdate builder.
func (_u *UpstreamChangeEventUpdate) Where(ps ...predicate.UpstreamChangeEvent) *UpstreamChangeEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UpstreamChangeEventUpdate) SetUpdatedAt(v time.Time) *UpstreamChangeEventUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProviderID sets the "provider_id" field.
func (_u *UpstreamChangeEventUpdate) SetProviderID(v int64) *UpstreamChangeEventUpdate {
	_u.mutation.ResetProviderID()
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *UpstreamChangeEventUpdate) SetNillableProviderID(v *int64) *UpstreamChangeEventUpdate {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// AddProviderID adds value to the "provider_id" field.
func (_u *UpstreamChangeEventUpdate) AddProviderID(v int64) *UpstreamChangeEventUpdate {
	_u.mutation.AddProviderID(v)
	return _u
}

// SetType sets the "type" field.
func (_u *UpstreamChangeEventUpdate) SetType(v string) *UpstreamChangeEventUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *UpstreamChangeEventUpdate) SetNillableType(v *string) *UpstreamChangeEventUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *UpstreamChangeEventUpdate) SetSummary(v string) *UpstreamChangeEventUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *UpstreamChangeEventUpdate) SetNillableSummary(v *string) *UpstreamChangeEventUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetDetail sets the "detail" field.
func (_u *UpstreamChangeEventUpdate) SetDetail(v map[string]interface{}) *UpstreamChangeEventUpdate {
	_u.mutation.SetDetail(v)
	return _u
}

// ClearDetail clears the value of the "detail" field.
func (_u *UpstreamChangeEventUpdate) ClearDetail() *UpstreamChangeEventUpdate {
	_u.mutation.ClearDetail()
	return _u
}

// SetNotified sets the "notified" field.
func (_u *UpstreamChangeEventUpdate) SetNotified(v bool) *UpstreamChangeEventUpdate {
	_u.mutation.SetNotified(v)
	return _u
}

// SetNillableNotified sets the "notified" field if the given value is not nil.
func (_u *UpstreamChangeEventUpdate) SetNillableNotified(v *bool) *UpstreamChangeEventUpdate {
	if v != nil {
		_u.SetNotified(*v)
	}
	return _u
}

// Mutation returns the UpstreamChangeEventMutation object of the builder.
func (_u *UpstreamChangeEventUpdate) Mutation() *UpstreamChangeEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UpstreamChangeEventUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamChangeEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UpstreamChangeEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamChangeEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UpstreamChangeEventUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := upstreamchangeevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamChangeEventUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := upstreamchangeevent.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "UpstreamChangeEvent.type": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamChangeEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamchangeevent.Table, upstreamchangeevent.Columns, sqlgraph.NewFieldSpec(upstreamchangeevent.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamchangeevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ProviderID(); ok {
		_spec.SetField(upstreamchangeevent.FieldProviderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProviderID(); ok {
		_spec.AddField(upstreamchangeevent.FieldProviderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(upstreamchangeevent.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(upstreamchangeevent.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Detail(); ok {
		_spec.SetField(upstreamchangeevent.FieldDetail, field.TypeJSON, value)
	}
	if _u.mutation.DetailCleared() {
		_spec.ClearField(upstreamchangeevent.FieldDetail, field.TypeJSON)
	}
	if value, ok := _u.mutation.Notified(); ok {
		_spec.SetField(upstreamchangeevent.FieldNotified, field.TypeBool, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamchangeevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UpstreamChangeEventUpdateOne is the builder for updating a single UpstreamChangeEvent entity.
type UpstreamChangeEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UpstreamChangeEventMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UpstreamChangeEventUpdateOne) SetUpdatedAt(v time.Time) *UpstreamChangeEventUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProviderID sets the "provider_id" field.
func (_u *UpstreamChangeEventUpdateOne) SetProviderID(v int64) *UpstreamChangeEventUpdateOne {
	_u.mutation.ResetProviderID()
	_u.mutation.SetProviderID(v)
	return _u
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_u *UpstreamChangeEventUpdateOne) SetNillableProviderID(v *int64) *UpstreamChangeEventUpdateOne {
	if v != nil {
		_u.SetProviderID(*v)
	}
	return _u
}

// AddProviderID adds value to the "provider_id" field.
func (_u *UpstreamChangeEventUpdateOne) AddProviderID(v int64) *UpstreamChangeEventUpdateOne {
	_u.mutation.AddProviderID(v)
	return _u
}

// SetType sets the "type" field.
func (_u *UpstreamChangeEventUpdateOne) SetType(v string) *UpstreamChangeEventUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *UpstreamChangeEventUpdateOne) SetNillableType(v *string) *UpstreamChangeEventUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetSummary sets the "summary" field.
func (_u *UpstreamChangeEventUpdateOne) SetSummary(v string) *UpstreamChangeEventUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *UpstreamChangeEventUpdateOne) SetNillableSummary(v *string) *UpstreamChangeEventUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetDetail sets the "detail" field.
func (_u *UpstreamChangeEventUpdateOne) SetDetail(v map[string]interface{}) *UpstreamChangeEventUpdateOne {
	_u.mutation.SetDetail(v)
	return _u
}

// ClearDetail clears the value of the "detail" field.
func (_u *UpstreamChangeEventUpdateOne) ClearDetail() *UpstreamChangeEventUpdateOne {
	_u.mutation.ClearDetail()
	return _u
}

// SetNotified sets the "notified" field.
func (_u *UpstreamChangeEventUpdateOne) SetNotified(v bool) *UpstreamChangeEventUpdateOne {
	_u.mutation.SetNotified(v)
	return _u
}

// SetNillableNotified sets the "notified" field if the given value is not nil.
func (_u *UpstreamChangeEventUpdateOne) SetNillableNotified(v *bool) *UpstreamChangeEventUpdateOne {
	if v != nil {
		_u.SetNotified(*v)
	}
	return _u
}

// Mutation returns the UpstreamChangeEventMutation object of the builder.
func (_u *UpstreamChangeEventUpdateOne) Mutation() *UpstreamChangeEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the UpstreamChangeEventUpdate builder.
func (_u *UpstreamChangeEventUpdateOne) Where(ps ...predicate.UpstreamChangeEvent) *UpstreamChangeEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UpstreamChangeEventUpdateOne) Select(field string, fields ...string) *UpstreamChangeEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UpstreamChangeEvent entity.
func (_u *UpstreamChangeEventUpdateOne) Save(ctx context.Context) (*UpstreamChangeEvent, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamChangeEventUpdateOne) SaveX(ctx context.Context) *UpstreamChangeEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UpstreamChangeEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamChangeEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UpstreamChangeEventUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := upstreamchangeevent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamChangeEventUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := upstreamchangeevent.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "UpstreamChangeEvent.type": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamChangeEventUpdateOne) sqlSave(ctx context.Context) (_node *UpstreamChangeEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamchangeevent.Table, upstreamchangeevent.Columns, sqlgraph.NewFieldSpec(upstreamchangeevent.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UpstreamChangeEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upstreamchangeevent.FieldID)
		for _, f := range fields {
			if !upstreamchangeevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upstreamchangeevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamchangeevent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ProviderID(); ok {
		_spec.SetField(upstreamchangeevent.FieldProviderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedProviderID(); ok {
		_spec.AddField(upstreamchangeevent.FieldProviderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(upstreamchangeevent.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(upstreamchangeevent.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Detail(); ok {
		_spec.SetField(upstreamchangeevent.FieldDetail, field.TypeJSON, value)
	}
	if _u.mutation.DetailCleared() {
		_spec.ClearField(upstreamchangeevent.FieldDetail, field.TypeJSON)
	}
	if value, ok := _u.mutation.Notified(); ok {
		_spec.SetField(upstreamchangeevent.FieldNotified, field.TypeBool, value)
	}
	_node = &UpstreamChangeEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamchangeevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
