// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/upstreamprovider"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// UpstreamProvider is the model entity for the UpstreamProvider schema.
type UpstreamProvider struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// SiteURL holds the value of the "site_url" field.
	SiteURL string `json:"site_url,omitempty"`
	// APIBaseURL holds the value of the "api_base_url" field.
	APIBaseURL string `json:"api_base_url,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Credentials holds the value of the "credentials" field.
	Credentials map[string]interface{} `json:"-"`
	// BalanceThreshold holds the value of the "balance_threshold" field.
	BalanceThreshold *float64 `json:"balance_threshold,omitempty"`
	// NotifyOnPriceChange holds the value of the "notify_on_price_change" field.
	NotifyOnPriceChange bool `json:"notify_on_price_change,omitempty"`
	// RefreshIntervalMinutes holds the value of the "refresh_interval_minutes" field.
	RefreshIntervalMinutes int `json:"refresh_interval_minutes,omitempty"`
	// LatestSnapshot holds the value of the "latest_snapshot" field.
	LatestSnapshot *domain.UpstreamSnapshot `json:"latest_snapshot,omitempty"`
	// LastRefreshedAt holds the value of the "last_refreshed_at" field.
	LastRefreshedAt *time.Time `json:"last_refreshed_at,omitempty"`
	// LastError holds the value of the "last_error" field.
	LastError string `json:"last_error,omitempty"`
	// ConsecutiveFailures holds the value of the "consecutive_failures" field.
	ConsecutiveFailures int `json:"consecutive_failures,omitempty"`
	// BalanceAlerted holds the value of the "balance_alerted" field.
	BalanceAlerted bool `json:"balance_alerted,omitempty"`
	// RefreshStartedAt holds the value of the "refresh_started_at" field.
	RefreshStartedAt *time.Time `json:"refresh_started_at,omitempty"`
	// Remark holds the value of the "remark" field.
	Remark       string `json:"remark,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UpstreamProvider) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upstreamprovider.FieldCredentials, upstreamprovider.FieldLatestSnapshot:
			values[i] = new([]byte)
		case upstreamprovider.FieldNotifyOnPriceChange, upstreamprovider.FieldBalanceAlerted:
			values[i] = new(sql.NullBool)
		case upstreamprovider.FieldBalanceThreshold:
			values[i] = new(sql.NullFloat64)
		case upstreamprovider.FieldID, upstreamprovider.FieldRefreshIntervalMinutes, upstreamprovider.FieldConsecutiveFailures:
			values[i] = new(sql.NullInt64)
		case upstreamprovider.FieldName, upstreamprovider.FieldType, upstreamprovider.FieldSiteURL, upstreamprovider.FieldAPIBaseURL, upstreamprovider.FieldStatus, upstreamprovider.FieldLastError, upstreamprovider.FieldRemark:
			values[i] = new(sql.NullString)
		case upstreamprovider.FieldCreatedAt, upstreamprovider.FieldUpdatedAt, upstreamprovider.FieldLastRefreshedAt, upstreamprovider.FieldRefreshStartedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UpstreamProvider fields.
func (_m *UpstreamProvider) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upstreamprovider.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case upstreamprovider.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case upstreamprovider.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case upstreamprovider.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case upstreamprovider.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case upstreamprovider.FieldSiteURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field site_url", values[i])
			} else if value.Valid {
				_m.SiteURL = value.String
			}
		case upstreamprovider.FieldAPIBaseURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_base_url", values[i])
			} else if value.Valid {
				_m.APIBaseURL = value.String
			}
		case upstreamprovider.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case upstreamprovider.FieldCredentials:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field credentials", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Credentials); err != nil {
					return fmt.Errorf("unmarshal field credentials: %w", err)
				}
			}
		case upstreamprovider.FieldBalanceThreshold:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_threshold", values[i])
			} else if value.Valid {
				_m.BalanceThreshold = new(float64)
				*_m.BalanceThreshold = value.Float64
			}
		case upstreamprovider.FieldNotifyOnPriceChange:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field notify_on_price_change", values[i])
			} else if value.Valid {
				_m.NotifyOnPriceChange = value.Bool
			}
		case upstreamprovider.FieldRefreshIntervalMinutes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_interval_minutes", values[i])
			} else if value.Valid {
				_m.RefreshIntervalMinutes = int(value.Int64)
			}
		case upstreamprovider.FieldLatestSnapshot:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field latest_snapshot", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.LatestSnapshot); err != nil {
					return fmt.Errorf("unmarshal field latest_snapshot: %w", err)
				}
			}
		case upstreamprovider.FieldLastRefreshedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_refreshed_at", values[i])
			} else if value.Valid {
				_m.LastRefreshedAt = new(time.Time)
				*_m.LastRefreshedAt = value.Time
			}
		case upstreamprovider.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = value.String
			}
		case upstreamprovider.FieldConsecutiveFailures:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field consecutive_failures", values[i])
			} else if value.Valid {
				_m.ConsecutiveFailures = int(value.Int64)
			}
		case upstreamprovider.FieldBalanceAlerted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field balance_alerted", values[i])
			} else if value.Valid {
				_m.BalanceAlerted = value.Bool
			}
		case upstreamprovider.FieldRefreshStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_started_at", values[i])
			} else if value.Valid {
				_m.RefreshStartedAt = new(time.Time)
				*_m.RefreshStartedAt = value.Time
			}
		case upstreamprovider.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				_m.Remark = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UpstreamProvider.
// This includes values selected through modifiers, order, etc.
func (_m *UpstreamProvider) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this UpstreamProvider.
// Note that you need to call UpstreamProvider.Unwrap() before calling this method if this UpstreamProvider
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UpstreamProvider) Update() *UpstreamProviderUpdateOne {
	return NewUpstreamProviderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UpstreamProvider entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UpstreamProvider) Unwrap() *UpstreamProvider {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UpstreamProvider is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UpstreamProvider) String() string {
	var builder strings.Builder
	builder.WriteString("UpstreamProvider(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	builder.WriteString("site_url=")
	builder.WriteString(_m.SiteURL)
	builder.WriteString(", ")
	builder.WriteString("api_base_url=")
	builder.WriteString(_m.APIBaseURL)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("credentials=<sensitive>")
	builder.WriteString(", ")
	if v := _m.BalanceThreshold; v != nil {
		builder.WriteString("balance_threshold=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("notify_on_price_change=")
	builder.WriteString(fmt.Sprintf("%v", _m.NotifyOnPriceChange))
	builder.WriteString(", ")
	builder.WriteString("refresh_interval_minutes=")
	builder.WriteString(fmt.Sprintf("%v", _m.RefreshIntervalMinutes))
	builder.WriteString(", ")
	builder.WriteString("latest_snapshot=")
	builder.WriteString(fmt.Sprintf("%v", _m.LatestSnapshot))
	builder.WriteString(", ")
	if v := _m.LastRefreshedAt; v != nil {
		builder.WriteString("last_refreshed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("last_error=")
	builder.WriteString(_m.LastError)
	builder.WriteString(", ")
	builder.WriteString("consecutive_failures=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConsecutiveFailures))
	builder.WriteString(", ")
	builder.WriteString("balance_alerted=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceAlerted))
	builder.WriteString(", ")
	if v := _m.RefreshStartedAt; v != nil {
		builder.WriteString("refresh_started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("remark=")
	builder.WriteString(_m.Remark)
	builder.WriteByte(')')
	return builder.String()
}

// UpstreamProviders is a parsable slice of UpstreamProvider.
type UpstreamProviders []*UpstreamProvider
