// Code generated by ent, DO NOT EDIT.

package upstreamprovider

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the upstreamprovider type in the database.
	Label = "upstream_provider"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldSiteURL holds the string denoting the site_url field in the database.
	FieldSiteURL = "site_url"
	// FieldAPIBaseURL holds the string denoting the api_base_url field in the database.
	FieldAPIBaseURL = "api_base_url"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCredentials holds the string denoting the credentials field in the database.
	FieldCredentials = "credentials"
	// FieldProxyID holds the string denoting the proxy_id field in the database.
	FieldProxyID = "proxy_id"
	// FieldBalanceThreshold holds the string denoting the balance_threshold field in the database.
	FieldBalanceThreshold = "balance_threshold"
	// FieldNotifyOnPriceChange holds the string denoting the notify_on_price_change field in the database.
	FieldNotifyOnPriceChange = "notify_on_price_change"
	// FieldRefreshIntervalMinutes holds the string denoting the refresh_interval_minutes field in the database.
	FieldRefreshIntervalMinutes = "refresh_interval_minutes"
	// FieldLatestSnapshot holds the string denoting the latest_snapshot field in the database.
	FieldLatestSnapshot = "latest_snapshot"
	// FieldLastRefreshedAt holds the string denoting the last_refreshed_at field in the database.
	FieldLastRefreshedAt = "last_refreshed_at"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldConsecutiveFailures holds the string denoting the consecutive_failures field in the database.
	FieldConsecutiveFailures = "consecutive_failures"
	// FieldBalanceAlerted holds the string denoting the balance_alerted field in the database.
	FieldBalanceAlerted = "balance_alerted"
	// FieldRefreshStartedAt holds the string denoting the refresh_started_at field in the database.
	FieldRefreshStartedAt = "refresh_started_at"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// EdgeProxy holds the string denoting the proxy edge name in mutations.
	EdgeProxy = "proxy"
	// Table holds the table name of the upstreamprovider in the database.
	Table = "upstream_providers"
	// ProxyTable is the table that holds the proxy relation/edge.
	ProxyTable = "upstream_providers"
	// ProxyInverseTable is the table name for the Proxy entity.
	// It exists in this package in order to avoid circular dependency with the "proxy" package.
	ProxyInverseTable = "proxies"
	// ProxyColumn is the table column denoting the proxy relation/edge.
	ProxyColumn = "proxy_id"
)

// Columns holds all SQL columns for upstreamprovider fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldType,
	FieldSiteURL,
	FieldAPIBaseURL,
	FieldStatus,
	FieldCredentials,
	FieldProxyID,
	FieldBalanceThreshold,
	FieldNotifyOnPriceChange,
	FieldRefreshIntervalMinutes,
	FieldLatestSnapshot,
	FieldLastRefreshedAt,
	FieldLastError,
	FieldConsecutiveFailures,
	FieldBalanceAlerted,
	FieldRefreshStartedAt,
	FieldRemark,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// TypeValidator is a validator for the "type" field. It is called by the builders before save.
	TypeValidator func(string) error
	// SiteURLValidator is a validator for the "site_url" field. It is called by the builders before save.
	SiteURLValidator func(string) error
	// DefaultAPIBaseURL holds the default value on creation for the "api_base_url" field.
	DefaultAPIBaseURL string
	// APIBaseURLValidator is a validator for the "api_base_url" field. It is called by the builders before save.
	APIBaseURLValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultNotifyOnPriceChange holds the default value on creation for the "notify_on_price_change" field.
	DefaultNotifyOnPriceChange bool
	// DefaultRefreshIntervalMinutes holds the default value on creation for the "refresh_interval_minutes" field.
	DefaultRefreshIntervalMinutes int
	// DefaultLastError holds the default value on creation for the "last_error" field.
	DefaultLastError string
	// DefaultConsecutiveFailures holds the default value on creation for the "consecutive_failures" field.
	DefaultConsecutiveFailures int
	// DefaultBalanceAlerted holds the default value on creation for the "balance_alerted" field.
	DefaultBalanceAlerted bool
	// DefaultRemark holds the default value on creation for the "remark" field.
	DefaultRemark string
)

// OrderOption defines the ordering options for the UpstreamProvider queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// BySiteURL orders the results by the site_url field.
func BySiteURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSiteURL, opts...).ToFunc()
}

// ByAPIBaseURL orders the results by the api_base_url field.
func ByAPIBaseURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIBaseURL, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByProxyID orders the results by the proxy_id field.
func ByProxyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProxyID, opts...).ToFunc()
}

// ByBalanceThreshold orders the results by the balance_threshold field.
func ByBalanceThreshold(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceThreshold, opts...).ToFunc()
}

// ByNotifyOnPriceChange orders the results by the notify_on_price_change field.
func ByNotifyOnPriceChange(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotifyOnPriceChange, opts...).ToFunc()
}

// ByRefreshIntervalMinutes orders the results by the refresh_interval_minutes field.
func ByRefreshIntervalMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefreshIntervalMinutes, opts...).ToFunc()
}

// ByLastRefreshedAt orders the results by the last_refreshed_at field.
func ByLastRefreshedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastRefreshedAt, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByConsecutiveFailures orders the results by the consecutive_failures field.
func ByConsecutiveFailures(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConsecutiveFailures, opts...).ToFunc()
}

// ByBalanceAlerted orders the results by the balance_alerted field.
func ByBalanceAlerted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalanceAlerted, opts...).ToFunc()
}

// ByRefreshStartedAt orders the results by the refresh_started_at field.
func ByRefreshStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefreshStartedAt, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// ByProxyField orders the results by proxy field.
func ByProxyField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProxyStep(), sql.OrderByField(field, opts...))
	}
}
func newProxyStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProxyInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ProxyTable, ProxyColumn),
	)
}
