// Code generated by ent, DO NOT EDIT.

package upstreamprovider

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldName, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldType, v))
}

// SiteURL applies equality check predicate on the "site_url" field. It's identical to SiteURLEQ.
func SiteURL(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldSiteURL, v))
}

// APIBaseURL applies equality check predicate on the "api_base_url" field. It's identical to APIBaseURLEQ.
func APIBaseURL(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldAPIBaseURL, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldStatus, v))
}

// BalanceThreshold applies equality check predicate on the "balance_threshold" field. It's identical to BalanceThresholdEQ.
func BalanceThreshold(v float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldBalanceThreshold, v))
}

// NotifyOnPriceChange applies equality check predicate on the "notify_on_price_change" field. It's identical to NotifyOnPriceChangeEQ.
func NotifyOnPriceChange(v bool) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldNotifyOnPriceChange, v))
}

// RefreshIntervalMinutes applies equality check predicate on the "refresh_interval_minutes" field. It's identical to RefreshIntervalMinutesEQ.
func RefreshIntervalMinutes(v int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldRefreshIntervalMinutes, v))
}

// LastRefreshedAt applies equality check predicate on the "last_refreshed_at" field. It's identical to LastRefreshedAtEQ.
func LastRefreshedAt(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldLastRefreshedAt, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldLastError, v))
}

// ConsecutiveFailures applies equality check predicate on the "consecutive_failures" field. It's identical to ConsecutiveFailuresEQ.
func ConsecutiveFailures(v int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldConsecutiveFailures, v))
}

// BalanceAlerted applies equality check predicate on the "balance_alerted" field. It's identical to BalanceAlertedEQ.
func BalanceAlerted(v bool) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldBalanceAlerted, v))
}

// RefreshStartedAt applies equality check predicate on the "refresh_started_at" field. It's identical to RefreshStartedAtEQ.
func RefreshStartedAt(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldRefreshStartedAt, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldRemark, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContainsFold(FieldName, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContainsFold(FieldType, v))
}

// SiteURLEQ applies the EQ predicate on the "site_url" field.
func SiteURLEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldSiteURL, v))
}

// SiteURLNEQ applies the NEQ predicate on the "site_url" field.
func SiteURLNEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldSiteURL, v))
}

// SiteURLIn applies the In predicate on the "site_url" field.
func SiteURLIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldSiteURL, vs...))
}

// SiteURLNotIn applies the NotIn predicate on the "site_url" field.
func SiteURLNotIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldSiteURL, vs...))
}

// SiteURLGT applies the GT predicate on the "site_url" field.
func SiteURLGT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldSiteURL, v))
}

// SiteURLGTE applies the GTE predicate on the "site_url" field.
func SiteURLGTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldSiteURL, v))
}

// SiteURLLT applies the LT predicate on the "site_url" field.
func SiteURLLT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldSiteURL, v))
}

// SiteURLLTE applies the LTE predicate on the "site_url" field.
func SiteURLLTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldSiteURL, v))
}

// SiteURLContains applies the Contains predicate on the "site_url" field.
func SiteURLContains(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContains(FieldSiteURL, v))
}

// SiteURLHasPrefix applies the HasPrefix predicate on the "site_url" field.
func SiteURLHasPrefix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasPrefix(FieldSiteURL, v))
}

// SiteURLHasSuffix applies the HasSuffix predicate on the "site_url" field.
func SiteURLHasSuffix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasSuffix(FieldSiteURL, v))
}

// SiteURLEqualFold applies the EqualFold predicate on the "site_url" field.
func SiteURLEqualFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEqualFold(FieldSiteURL, v))
}

// SiteURLContainsFold applies the ContainsFold predicate on the "site_url" field.
func SiteURLContainsFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContainsFold(FieldSiteURL, v))
}

// APIBaseURLEQ applies the EQ predicate on the "api_base_url" field.
func APIBaseURLEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldAPIBaseURL, v))
}

// APIBaseURLNEQ applies the NEQ predicate on the "api_base_url" field.
func APIBaseURLNEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldAPIBaseURL, v))
}

// APIBaseURLIn applies the In predicate on the "api_base_url" field.
func APIBaseURLIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldAPIBaseURL, vs...))
}

// APIBaseURLNotIn applies the NotIn predicate on the "api_base_url" field.
func APIBaseURLNotIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldAPIBaseURL, vs...))
}

// APIBaseURLGT applies the GT predicate on the "api_base_url" field.
func APIBaseURLGT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldAPIBaseURL, v))
}

// APIBaseURLGTE applies the GTE predicate on the "api_base_url" field.
func APIBaseURLGTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldAPIBaseURL, v))
}

// APIBaseURLLT applies the LT predicate on the "api_base_url" field.
func APIBaseURLLT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldAPIBaseURL, v))
}

// APIBaseURLLTE applies the LTE predicate on the "api_base_url" field.
func APIBaseURLLTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldAPIBaseURL, v))
}

// APIBaseURLContains applies the Contains predicate on the "api_base_url" field.
func APIBaseURLContains(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContains(FieldAPIBaseURL, v))
}

// APIBaseURLHasPrefix applies the HasPrefix predicate on the "api_base_url" field.
func APIBaseURLHasPrefix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasPrefix(FieldAPIBaseURL, v))
}

// APIBaseURLHasSuffix applies the HasSuffix predicate on the "api_base_url" field.
func APIBaseURLHasSuffix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasSuffix(FieldAPIBaseURL, v))
}

// APIBaseURLEqualFold applies the EqualFold predicate on the "api_base_url" field.
func APIBaseURLEqualFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEqualFold(FieldAPIBaseURL, v))
}

// APIBaseURLContainsFold applies the ContainsFold predicate on the "api_base_url" field.
func APIBaseURLContainsFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContainsFold(FieldAPIBaseURL, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContainsFold(FieldStatus, v))
}

// BalanceThresholdEQ applies the EQ predicate on the "balance_threshold" field.
func BalanceThresholdEQ(v float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldBalanceThreshold, v))
}

// BalanceThresholdNEQ applies the NEQ predicate on the "balance_threshold" field.
func BalanceThresholdNEQ(v float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldBalanceThreshold, v))
}

// BalanceThresholdIn applies the In predicate on the "balance_threshold" field.
func BalanceThresholdIn(vs ...float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldBalanceThreshold, vs...))
}

// BalanceThresholdNotIn applies the NotIn predicate on the "balance_threshold" field.
func BalanceThresholdNotIn(vs ...float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldBalanceThreshold, vs...))
}

// BalanceThresholdGT applies the GT predicate on the "balance_threshold" field.
func BalanceThresholdGT(v float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldBalanceThreshold, v))
}

// BalanceThresholdGTE applies the GTE predicate on the "balance_threshold" field.
func BalanceThresholdGTE(v float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldBalanceThreshold, v))
}

// BalanceThresholdLT applies the LT predicate on the "balance_threshold" field.
func BalanceThresholdLT(v float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldBalanceThreshold, v))
}

// BalanceThresholdLTE applies the LTE predicate on the "balance_threshold" field.
func BalanceThresholdLTE(v float64) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldBalanceThreshold, v))
}

// BalanceThresholdIsNil applies the IsNil predicate on the "balance_threshold" field.
func BalanceThresholdIsNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIsNull(FieldBalanceThreshold))
}

// BalanceThresholdNotNil applies the NotNil predicate on the "balance_threshold" field.
func BalanceThresholdNotNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotNull(FieldBalanceThreshold))
}

// NotifyOnPriceChangeEQ applies the EQ predicate on the "notify_on_price_change" field.
func NotifyOnPriceChangeEQ(v bool) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldNotifyOnPriceChange, v))
}

// NotifyOnPriceChangeNEQ applies the NEQ predicate on the "notify_on_price_change" field.
func NotifyOnPriceChangeNEQ(v bool) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldNotifyOnPriceChange, v))
}

// RefreshIntervalMinutesEQ applies the EQ predicate on the "refresh_interval_minutes" field.
func RefreshIntervalMinutesEQ(v int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldRefreshIntervalMinutes, v))
}

// RefreshIntervalMinutesNEQ applies the NEQ predicate on the "refresh_interval_minutes" field.
func RefreshIntervalMinutesNEQ(v int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldRefreshIntervalMinutes, v))
}

// RefreshIntervalMinutesIn applies the In predicate on the "refresh_interval_minutes" field.
func RefreshIntervalMinutesIn(vs ...int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldRefreshIntervalMinutes, vs...))
}

// RefreshIntervalMinutesNotIn applies the NotIn predicate on the "refresh_interval_minutes" field.
func RefreshIntervalMinutesNotIn(vs ...int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldRefreshIntervalMinutes, vs...))
}

// RefreshIntervalMinutesGT applies the GT predicate on the "refresh_interval_minutes" field.
func RefreshIntervalMinutesGT(v int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldRefreshIntervalMinutes, v))
}

// RefreshIntervalMinutesGTE applies the GTE predicate on the "refresh_interval_minutes" field.
func RefreshIntervalMinutesGTE(v int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldRefreshIntervalMinutes, v))
}

// RefreshIntervalMinutesLT applies the LT predicate on the "refresh_interval_minutes" field.
func RefreshIntervalMinutesLT(v int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldRefreshIntervalMinutes, v))
}

// RefreshIntervalMinutesLTE applies the LTE predicate on the "refresh_interval_minutes" field.
func RefreshIntervalMinutesLTE(v int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldRefreshIntervalMinutes, v))
}

// LatestSnapshotIsNil applies the IsNil predicate on the "latest_snapshot" field.
func LatestSnapshotIsNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIsNull(FieldLatestSnapshot))
}

// LatestSnapshotNotNil applies the NotNil predicate on the "latest_snapshot" field.
func LatestSnapshotNotNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotNull(FieldLatestSnapshot))
}

// LastRefreshedAtEQ applies the EQ predicate on the "last_refreshed_at" field.
func LastRefreshedAtEQ(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldLastRefreshedAt, v))
}

// LastRefreshedAtNEQ applies the NEQ predicate on the "last_refreshed_at" field.
func LastRefreshedAtNEQ(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldLastRefreshedAt, v))
}

// LastRefreshedAtIn applies the In predicate on the "last_refreshed_at" field.
func LastRefreshedAtIn(vs ...time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldLastRefreshedAt, vs...))
}

// LastRefreshedAtNotIn applies the NotIn predicate on the "last_refreshed_at" field.
func LastRefreshedAtNotIn(vs ...time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldLastRefreshedAt, vs...))
}

// LastRefreshedAtGT applies the GT predicate on the "last_refreshed_at" field.
func LastRefreshedAtGT(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldLastRefreshedAt, v))
}

// LastRefreshedAtGTE applies the GTE predicate on the "last_refreshed_at" field.
func LastRefreshedAtGTE(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldLastRefreshedAt, v))
}

// LastRefreshedAtLT applies the LT predicate on the "last_refreshed_at" field.
func LastRefreshedAtLT(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldLastRefreshedAt, v))
}

// LastRefreshedAtLTE applies the LTE predicate on the "last_refreshed_at" field.
func LastRefreshedAtLTE(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldLastRefreshedAt, v))
}

// LastRefreshedAtIsNil applies the IsNil predicate on the "last_refreshed_at" field.
func LastRefreshedAtIsNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIsNull(FieldLastRefreshedAt))
}

// LastRefreshedAtNotNil applies the NotNil predicate on the "last_refreshed_at" field.
func LastRefreshedAtNotNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotNull(FieldLastRefreshedAt))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContainsFold(FieldLastError, v))
}

// ConsecutiveFailuresEQ applies the EQ predicate on the "consecutive_failures" field.
func ConsecutiveFailuresEQ(v int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresNEQ applies the NEQ predicate on the "consecutive_failures" field.
func ConsecutiveFailuresNEQ(v int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresIn applies the In predicate on the "consecutive_failures" field.
func ConsecutiveFailuresIn(vs ...int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldConsecutiveFailures, vs...))
}

// ConsecutiveFailuresNotIn applies the NotIn predicate on the "consecutive_failures" field.
func ConsecutiveFailuresNotIn(vs ...int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldConsecutiveFailures, vs...))
}

// ConsecutiveFailuresGT applies the GT predicate on the "consecutive_failures" field.
func ConsecutiveFailuresGT(v int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresGTE applies the GTE predicate on the "consecutive_failures" field.
func ConsecutiveFailuresGTE(v int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresLT applies the LT predicate on the "consecutive_failures" field.
func ConsecutiveFailuresLT(v int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldConsecutiveFailures, v))
}

// ConsecutiveFailuresLTE applies the LTE predicate on the "consecutive_failures" field.
func ConsecutiveFailuresLTE(v int) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldConsecutiveFailures, v))
}

// BalanceAlertedEQ applies the EQ predicate on the "balance_alerted" field.
func BalanceAlertedEQ(v bool) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldBalanceAlerted, v))
}

// BalanceAlertedNEQ applies the NEQ predicate on the "balance_alerted" field.
func BalanceAlertedNEQ(v bool) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldBalanceAlerted, v))
}

// RefreshStartedAtEQ applies the EQ predicate on the "refresh_started_at" field.
func RefreshStartedAtEQ(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldRefreshStartedAt, v))
}

// RefreshStartedAtNEQ applies the NEQ predicate on the "refresh_started_at" field.
func RefreshStartedAtNEQ(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldRefreshStartedAt, v))
}

// RefreshStartedAtIn applies the In predicate on the "refresh_started_at" field.
func RefreshStartedAtIn(vs ...time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldRefreshStartedAt, vs...))
}

// RefreshStartedAtNotIn applies the NotIn predicate on the "refresh_started_at" field.
func RefreshStartedAtNotIn(vs ...time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldRefreshStartedAt, vs...))
}

// RefreshStartedAtGT applies the GT predicate on the "refresh_started_at" field.
func RefreshStartedAtGT(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldRefreshStartedAt, v))
}

// RefreshStartedAtGTE applies the GTE predicate on the "refresh_started_at" field.
func RefreshStartedAtGTE(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldRefreshStartedAt, v))
}

// RefreshStartedAtLT applies the LT predicate on the "refresh_started_at" field.
func RefreshStartedAtLT(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldRefreshStartedAt, v))
}

// RefreshStartedAtLTE applies the LTE predicate on the "refresh_started_at" field.
func RefreshStartedAtLTE(v time.Time) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldRefreshStartedAt, v))
}

// RefreshStartedAtIsNil applies the IsNil predicate on the "refresh_started_at" field.
func RefreshStartedAtIsNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIsNull(FieldRefreshStartedAt))
}

// RefreshStartedAtNotNil applies the NotNil predicate on the "refresh_started_at" field.
func RefreshStartedAtNotNil() predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotNull(FieldRefreshStartedAt))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.FieldContainsFold(FieldRemark, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UpstreamProvider) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UpstreamProvider) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UpstreamProvider) predicate.UpstreamProvider {
	return predicate.UpstreamProvider(sql.NotPredicates(p))
}
