// Code generated by ent, DO NOT EDIT.

package upstreamusagecursor

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the upstreamusagecursor type in the database.
	Label = "upstream_usage_cursor"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldProviderID holds the string denoting the provider_id field in the database.
	FieldProviderID = "provider_id"
	// FieldCollectStartedAt holds the string denoting the collect_started_at field in the database.
	FieldCollectStartedAt = "collect_started_at"
	// FieldCollectedThroughDay holds the string denoting the collected_through_day field in the database.
	FieldCollectedThroughDay = "collected_through_day"
	// FieldBackfillDone holds the string denoting the backfill_done field in the database.
	FieldBackfillDone = "backfill_done"
	// FieldBackfillOldestDay holds the string denoting the backfill_oldest_day field in the database.
	FieldBackfillOldestDay = "backfill_oldest_day"
	// FieldLastCollectedAt holds the string denoting the last_collected_at field in the database.
	FieldLastCollectedAt = "last_collected_at"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// FieldLastPartial holds the string denoting the last_partial field in the database.
	FieldLastPartial = "last_partial"
	// FieldPartialReason holds the string denoting the partial_reason field in the database.
	FieldPartialReason = "partial_reason"
	// Table holds the table name of the upstreamusagecursor in the database.
	Table = "upstream_usage_cursor"
)

// Columns holds all SQL columns for upstreamusagecursor fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldProviderID,
	FieldCollectStartedAt,
	FieldCollectedThroughDay,
	FieldBackfillDone,
	FieldBackfillOldestDay,
	FieldLastCollectedAt,
	FieldLastError,
	FieldLastPartial,
	FieldPartialReason,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultBackfillDone holds the default value on creation for the "backfill_done" field.
	DefaultBackfillDone bool
	// DefaultLastError holds the default value on creation for the "last_error" field.
	DefaultLastError string
	// DefaultLastPartial holds the default value on creation for the "last_partial" field.
	DefaultLastPartial bool
	// DefaultPartialReason holds the default value on creation for the "partial_reason" field.
	DefaultPartialReason string
	// PartialReasonValidator is a validator for the "partial_reason" field. It is called by the builders before save.
	PartialReasonValidator func(string) error
)

// OrderOption defines the ordering options for the UpstreamUsageCursor queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByProviderID orders the results by the provider_id field.
func ByProviderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderID, opts...).ToFunc()
}

// ByCollectStartedAt orders the results by the collect_started_at field.
func ByCollectStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCollectStartedAt, opts...).ToFunc()
}

// ByCollectedThroughDay orders the results by the collected_through_day field.
func ByCollectedThroughDay(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCollectedThroughDay, opts...).ToFunc()
}

// ByBackfillDone orders the results by the backfill_done field.
func ByBackfillDone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBackfillDone, opts...).ToFunc()
}

// ByBackfillOldestDay orders the results by the backfill_oldest_day field.
func ByBackfillOldestDay(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBackfillOldestDay, opts...).ToFunc()
}

// ByLastCollectedAt orders the results by the last_collected_at field.
func ByLastCollectedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastCollectedAt, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// ByLastPartial orders the results by the last_partial field.
func ByLastPartial(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastPartial, opts...).ToFunc()
}

// ByPartialReason orders the results by the partial_reason field.
func ByPartialReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPartialReason, opts...).ToFunc()
}
