// Code generated by ent, DO NOT EDIT.

package upstreamusagecursor

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldEQ(FieldUpdatedAt, v))
}

// ProviderID applies equality check predicate on the "provider_id" field. It's identical to ProviderIDEQ.
func ProviderID(v int64) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldEQ(FieldProviderID, v))
}

// CollectStartedAt applies equality check predicate on the "collect_started_at" field. It's identical to CollectStartedAtEQ.
func CollectStartedAt(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldEQ(FieldCollectStartedAt, v))
}

// CollectedThroughDay applies equality check predicate on the "collected_through_day" field. It's identical to CollectedThroughDayEQ.
func CollectedThroughDay(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldEQ(FieldCollectedThroughDay, v))
}

// BackfillDone applies equality check predicate on the "backfill_done" field. It's identical to BackfillDoneEQ.
func BackfillDone(v bool) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldEQ(FieldBackfillDone, v))
}

// BackfillOldestDay applies equality check predicate on the "backfill_oldest_day" field. It's identical to BackfillOldestDayEQ.
func BackfillOldestDay(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldEQ(FieldBackfillOldestDay, v))
}

// LastCollectedAt applies equality check predicate on the "last_collected_at" field. It's identical to LastCollectedAtEQ.
func LastCollectedAt(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldEQ(FieldLastCollectedAt, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldEQ(FieldLastError, v))
}

// LastPartial applies equality check predicate on the "last_partial" field. It's identical to LastPartialEQ.
func LastPartial(v bool) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldEQ(FieldLastPartial, v))
}

// PartialReason applies equality check predicate on the "partial_reason" field. It's identical to PartialReasonEQ.
func PartialReason(v string) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldEQ(FieldPartialReason, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldLTE(FieldUpdatedAt, v))
}

// ProviderIDEQ applies the EQ predicate on the "provider_id" field.
func ProviderIDEQ(v int64) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldEQ(FieldProviderID, v))
}

// ProviderIDNEQ applies the NEQ predicate on the "provider_id" field.
func ProviderIDNEQ(v int64) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldNEQ(FieldProviderID, v))
}

// ProviderIDIn applies the In predicate on the "provider_id" field.
func ProviderIDIn(vs ...int64) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldIn(FieldProviderID, vs...))
}

// ProviderIDNotIn applies the NotIn predicate on the "provider_id" field.
func ProviderIDNotIn(vs ...int64) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldNotIn(FieldProviderID, vs...))
}

// ProviderIDGT applies the GT predicate on the "provider_id" field.
func ProviderIDGT(v int64) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldGT(FieldProviderID, v))
}

// ProviderIDGTE applies the GTE predicate on the "provider_id" field.
func ProviderIDGTE(v int64) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldGTE(FieldProviderID, v))
}

// ProviderIDLT applies the LT predicate on the "provider_id" field.
func ProviderIDLT(v int64) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldLT(FieldProviderID, v))
}

// ProviderIDLTE applies the LTE predicate on the "provider_id" field.
func ProviderIDLTE(v int64) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldLTE(FieldProviderID, v))
}

// CollectStartedAtEQ applies the EQ predicate on the "collect_started_at" field.
func CollectStartedAtEQ(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldEQ(FieldCollectStartedAt, v))
}

// CollectStartedAtNEQ applies the NEQ predicate on the "collect_started_at" field.
func CollectStartedAtNEQ(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldNEQ(FieldCollectStartedAt, v))
}

// CollectStartedAtIn applies the In predicate on the "collect_started_at" field.
func CollectStartedAtIn(vs ...time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldIn(FieldCollectStartedAt, vs...))
}

// CollectStartedAtNotIn applies the NotIn predicate on the "collect_started_at" field.
func CollectStartedAtNotIn(vs ...time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldNotIn(FieldCollectStartedAt, vs...))
}

// CollectStartedAtGT applies the GT predicate on the "collect_started_at" field.
func CollectStartedAtGT(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldGT(FieldCollectStartedAt, v))
}

// CollectStartedAtGTE applies the GTE predicate on the "collect_started_at" field.
func CollectStartedAtGTE(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldGTE(FieldCollectStartedAt, v))
}

// CollectStartedAtLT applies the LT predicate on the "collect_started_at" field.
func CollectStartedAtLT(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldLT(FieldCollectStartedAt, v))
}

// CollectStartedAtLTE applies the LTE predicate on the "collect_started_at" field.
func CollectStartedAtLTE(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldLTE(FieldCollectStartedAt, v))
}

// CollectStartedAtIsNil applies the IsNil predicate on the "collect_started_at" field.
func CollectStartedAtIsNil() predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldIsNull(FieldCollectStartedAt))
}

// CollectStartedAtNotNil applies the NotNil predicate on the "collect_started_at" field.
func CollectStartedAtNotNil() predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldNotNull(FieldCollectStartedAt))
}

// CollectedThroughDayEQ applies the EQ predicate on the "collected_through_day" field.
func CollectedThroughDayEQ(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldEQ(FieldCollectedThroughDay, v))
}

// CollectedThroughDayNEQ applies the NEQ predicate on the "collected_through_day" field.
func CollectedThroughDayNEQ(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldNEQ(FieldCollectedThroughDay, v))
}

// CollectedThroughDayIn applies the In predicate on the "collected_through_day" field.
func CollectedThroughDayIn(vs ...time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldIn(FieldCollectedThroughDay, vs...))
}

// CollectedThroughDayNotIn applies the NotIn predicate on the "collected_through_day" field.
func CollectedThroughDayNotIn(vs ...time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldNotIn(FieldCollectedThroughDay, vs...))
}

// CollectedThroughDayGT applies the GT predicate on the "collected_through_day" field.
func CollectedThroughDayGT(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldGT(FieldCollectedThroughDay, v))
}

// CollectedThroughDayGTE applies the GTE predicate on the "collected_through_day" field.
func CollectedThroughDayGTE(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldGTE(FieldCollectedThroughDay, v))
}

// CollectedThroughDayLT applies the LT predicate on the "collected_through_day" field.
func CollectedThroughDayLT(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldLT(FieldCollectedThroughDay, v))
}

// CollectedThroughDayLTE applies the LTE predicate on the "collected_through_day" field.
func CollectedThroughDayLTE(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldLTE(FieldCollectedThroughDay, v))
}

// CollectedThroughDayIsNil applies the IsNil predicate on the "collected_through_day" field.
func CollectedThroughDayIsNil() predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldIsNull(FieldCollectedThroughDay))
}

// CollectedThroughDayNotNil applies the NotNil predicate on the "collected_through_day" field.
func CollectedThroughDayNotNil() predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldNotNull(FieldCollectedThroughDay))
}

// BackfillDoneEQ applies the EQ predicate on the "backfill_done" field.
func BackfillDoneEQ(v bool) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldEQ(FieldBackfillDone, v))
}

// BackfillDoneNEQ applies the NEQ predicate on the "backfill_done" field.
func BackfillDoneNEQ(v bool) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldNEQ(FieldBackfillDone, v))
}

// BackfillOldestDayEQ applies the EQ predicate on the "backfill_oldest_day" field.
func BackfillOldestDayEQ(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldEQ(FieldBackfillOldestDay, v))
}

// BackfillOldestDayNEQ applies the NEQ predicate on the "backfill_oldest_day" field.
func BackfillOldestDayNEQ(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldNEQ(FieldBackfillOldestDay, v))
}

// BackfillOldestDayIn applies the In predicate on the "backfill_oldest_day" field.
func BackfillOldestDayIn(vs ...time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldIn(FieldBackfillOldestDay, vs...))
}

// BackfillOldestDayNotIn applies the NotIn predicate on the "backfill_oldest_day" field.
func BackfillOldestDayNotIn(vs ...time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldNotIn(FieldBackfillOldestDay, vs...))
}

// BackfillOldestDayGT applies the GT predicate on the "backfill_oldest_day" field.
func BackfillOldestDayGT(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldGT(FieldBackfillOldestDay, v))
}

// BackfillOldestDayGTE applies the GTE predicate on the "backfill_oldest_day" field.
func BackfillOldestDayGTE(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldGTE(FieldBackfillOldestDay, v))
}

// BackfillOldestDayLT applies the LT predicate on the "backfill_oldest_day" field.
func BackfillOldestDayLT(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldLT(FieldBackfillOldestDay, v))
}

// BackfillOldestDayLTE applies the LTE predicate on the "backfill_oldest_day" field.
func BackfillOldestDayLTE(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldLTE(FieldBackfillOldestDay, v))
}

// BackfillOldestDayIsNil applies the IsNil predicate on the "backfill_oldest_day" field.
func BackfillOldestDayIsNil() predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldIsNull(FieldBackfillOldestDay))
}

// BackfillOldestDayNotNil applies the NotNil predicate on the "backfill_oldest_day" field.
func BackfillOldestDayNotNil() predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldNotNull(FieldBackfillOldestDay))
}

// LastCollectedAtEQ applies the EQ predicate on the "last_collected_at" field.
func LastCollectedAtEQ(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldEQ(FieldLastCollectedAt, v))
}

// LastCollectedAtNEQ applies the NEQ predicate on the "last_collected_at" field.
func LastCollectedAtNEQ(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldNEQ(FieldLastCollectedAt, v))
}

// LastCollectedAtIn applies the In predicate on the "last_collected_at" field.
func LastCollectedAtIn(vs ...time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldIn(FieldLastCollectedAt, vs...))
}

// LastCollectedAtNotIn applies the NotIn predicate on the "last_collected_at" field.
func LastCollectedAtNotIn(vs ...time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldNotIn(FieldLastCollectedAt, vs...))
}

// LastCollectedAtGT applies the GT predicate on the "last_collected_at" field.
func LastCollectedAtGT(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldGT(FieldLastCollectedAt, v))
}

// LastCollectedAtGTE applies the GTE predicate on the "last_collected_at" field.
func LastCollectedAtGTE(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldGTE(FieldLastCollectedAt, v))
}

// LastCollectedAtLT applies the LT predicate on the "last_collected_at" field.
func LastCollectedAtLT(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldLT(FieldLastCollectedAt, v))
}

// LastCollectedAtLTE applies the LTE predicate on the "last_collected_at" field.
func LastCollectedAtLTE(v time.Time) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldLTE(FieldLastCollectedAt, v))
}

// LastCollectedAtIsNil applies the IsNil predicate on the "last_collected_at" field.
func LastCollectedAtIsNil() predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldIsNull(FieldLastCollectedAt))
}

// LastCollectedAtNotNil applies the NotNil predicate on the "last_collected_at" field.
func LastCollectedAtNotNil() predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldNotNull(FieldLastCollectedAt))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldContainsFold(FieldLastError, v))
}

// LastPartialEQ applies the EQ predicate on the "last_partial" field.
func LastPartialEQ(v bool) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldEQ(FieldLastPartial, v))
}

// LastPartialNEQ applies the NEQ predicate on the "last_partial" field.
func LastPartialNEQ(v bool) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldNEQ(FieldLastPartial, v))
}

// PartialReasonEQ applies the EQ predicate on the "partial_reason" field.
func PartialReasonEQ(v string) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldEQ(FieldPartialReason, v))
}

// PartialReasonNEQ applies the NEQ predicate on the "partial_reason" field.
func PartialReasonNEQ(v string) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldNEQ(FieldPartialReason, v))
}

// PartialReasonIn applies the In predicate on the "partial_reason" field.
func PartialReasonIn(vs ...string) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldIn(FieldPartialReason, vs...))
}

// PartialReasonNotIn applies the NotIn predicate on the "partial_reason" field.
func PartialReasonNotIn(vs ...string) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldNotIn(FieldPartialReason, vs...))
}

// PartialReasonGT applies the GT predicate on the "partial_reason" field.
func PartialReasonGT(v string) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldGT(FieldPartialReason, v))
}

// PartialReasonGTE applies the GTE predicate on the "partial_reason" field.
func PartialReasonGTE(v string) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldGTE(FieldPartialReason, v))
}

// PartialReasonLT applies the LT predicate on the "partial_reason" field.
func PartialReasonLT(v string) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldLT(FieldPartialReason, v))
}

// PartialReasonLTE applies the LTE predicate on the "partial_reason" field.
func PartialReasonLTE(v string) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldLTE(FieldPartialReason, v))
}

// PartialReasonContains applies the Contains predicate on the "partial_reason" field.
func PartialReasonContains(v string) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldContains(FieldPartialReason, v))
}

// PartialReasonHasPrefix applies the HasPrefix predicate on the "partial_reason" field.
func PartialReasonHasPrefix(v string) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldHasPrefix(FieldPartialReason, v))
}

// PartialReasonHasSuffix applies the HasSuffix predicate on the "partial_reason" field.
func PartialReasonHasSuffix(v string) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldHasSuffix(FieldPartialReason, v))
}

// PartialReasonEqualFold applies the EqualFold predicate on the "partial_reason" field.
func PartialReasonEqualFold(v string) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldEqualFold(FieldPartialReason, v))
}

// PartialReasonContainsFold applies the ContainsFold predicate on the "partial_reason" field.
func PartialReasonContainsFold(v string) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.FieldContainsFold(FieldPartialReason, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UpstreamUsageCursor) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UpstreamUsageCursor) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UpstreamUsageCursor) predicate.UpstreamUsageCursor {
	return predicate.UpstreamUsageCursor(sql.NotPredicates(p))
}
